RigsOfRods/rigs-of-rods

source/main/physics/Beam.h

fixes issue #101
I must have not added the change for removing the default values on calcBeams/6 this caused the wrong calcBeams to be called  and resulted in it being called twice in a loop.

[fix] calling calcBeams twice, remove default parameters

---

bin/resources/mygui/settings.layout
source/configurator/Configurator.cpp
source/main/gameplay/Road2.cpp
source/main/gfx/ShadowManager.cpp
source/main/gui/panels/GUI_GameSettings.cpp
source/main/physics/air/AirBrake.cpp
source/main/physics/flex/FlexAirfoil.cpp
source/main/physics/flex/FlexBody.cpp
source/main/physics/flex/FlexMesh.cpp
source/main/physics/flex/FlexMeshWheel.cpp
source/main/physics/flex/FlexObj.cpp

Stencil shadows were scrapped in Ogre 2.0 and are not maintained in RoR. It is time for us to say goodbye, cut them and move on.

Remove stencil shadows

---

source/main/physics/collision/PointColDetector.cpp

This is a general cleanup of PointColDetector:
- Replaced bitwise tricks with clean and simple multiplication / math. This is 2015, not 1970 when programmers optimized code by hand this way. Our job today is to create sane and readable code and leave hacks to compilers.
- Using log2 for base-2 logarithms. **This change requires C++11**.
- Fixed coding style.
Peer review and comments welcome.

PointColDetector cleanup

---

source/main/physics/collision/PointColDetector.cpp
source/main/physics/collision/PointColDetector.h

This PR cleans up mechanism of ref list storage by replacing dynamic arrays with std::vector. Moreover, the lists are persistant now, which (eliminates race condition?) fixes #160.

[Cleanup] Point collision detector cleanup, fixes #160

---

.gitignore
BUILDING.md
CONTRIBUTING.md
README.md
bin/resources/scripts/races.as
source/main/gfx/OgreSubsystem.cpp
source/main/gui/OverlayWrapper.cpp
source/main/main_sim/main.cpp
source/main/physics/collision/Collisions.cpp

revert links to documentation to old infrastructure as the "new" docs section is now obsolete

revert links to documentation to old infrastructure

---

tools/linux/l10n/README.txt
tools/linux/l10n/compile_mo.sh
tools/linux/l10n/extract_pot.sh
tools/linux/l10n/merge_to_tx.sh

The Configurator uses its own gettext macro and thus needs special handling

[Tools] Adjust and add helper scripts for Configurator l10n

---

source/main/main_sim/MainThread.cpp

I found out a funny duplication in startup code. The RoRbot is created twice in singleplayer. The code snippet is exactly the same.
Removed the first one.

Tuesday's cleanup.

---

source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/collision/PointColDetector.cpp
source/main/physics/collision/PointColDetector.h
source/main/physics/input_output/RigSpawner.cpp

Reduced the complexity of the inter truck collision code:
* Only one interPointCD object per truck [instead of multiple objects]
* Each truck is only being worked on by a single thread pool worker [instead of multiple workers]
* One kdTree per truck [instead of one kdTree per worker thread]
* Less points per kdTree [per truck bounding box checks]
Removed all dead code in the PointColDetector

interPointCD / PointColDetector

---

source/main/datatypes/beam_t.h
source/main/datatypes/node_t.h
source/main/datatypes/wheel_t.h
source/main/gameplay/RoRFrameListener.cpp
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamFactory.cpp
source/main/physics/BeamFactory.h
source/main/physics/BeamForcesEuler.cpp
source/main/physics/input_output/RigSpawner.cpp
source/main/scripting/ScriptEngine.cpp

BeamForcesEuler and Sim-Core struct cleanup:
* Removed unused variables in the Sim-Core structs (`lastforce`, `minendmass`, `lastNormal`)
* Removed the `inverted_mass` variable in the node_t struct (now calculated on demand)
* Removed duplicate code in BeamForcesEuler (bounding box code)
* Removed all experimental (and unused) `INTRA_TRUCK_PARALLEL` related code
Beam and BeamFactory cleanup:
* Skeleton view cleanup
* Removed the beamThreadPool in favor of the gEnv->threadPool

[Cleanup] BeamForcesEuler, BeamFactory, Beam

---

source/main/physics/ApproxMath.h
source/main/physics/flex/FlexBody.cpp

#16 is not affected by this change
`approx_invSqrt` was a duplicate of `fast_invSqrt`
(For reference: https://github.com/RigsOfRods/rigs-of-rods/commit/78d492c2742e12b97dcde3084f7b5bcb12b033ee#commitcomment-14116146)

[Codechange] Reverted the approx_inv function

---

source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamData.h
source/main/physics/collision/PointColDetector.cpp
source/main/physics/collision/PointColDetector.h
source/main/physics/input_output/RigSpawner.cpp

**Beam.cpp:**
* Removed redundant intraPointCD objects
* Combined the Prepare, Compute and Final methods
Positive side effect: The interPointCD->update() method is now executed in the thread pool
**PointColDetector:**
* Simplified the bounding box calculation
* Removed redundant bounding box intersection checks

[Cleanup] truckCollision / PointColDetector

---

source/main/physics/Beam.cpp

[Bugfix] nullptr dereferencing in calcAnimators

---

source/main/physics/Beam.cpp
source/main/physics/Beam.h

[Bugfix] Fixes incorrect 'reset in place' alignment on some trailers/loads

---

CMakeDependenciesConfig.txt

- allows to build RoR on older Linux distributions with only Ogre 1.8 in the repositories
- allows Intel GPU users to opt for Ogre 1.8 instead of Ogre 1.9, @tritonas00 told me Ogre 1.9 doesn't work as well with the Intel graphics driver

[Fix] CMake/UNIX: Build with Ogre 1.8

---

source/main/RoRPrerequisites.h

RoR master will not build out of the box on Fedora 23.
1. Install MyGUI from the official repositories on Fedora 23. This is MyGUI 3.2.1.
2. Follow the steps to  build for Fedora on http://www.rigsofrods.com/wiki/pages/Compiling_Sources_under_Linux, using Fedora 23
RoR should build
RoR fails, due to defining `MYGUI_GET_SCANCODE(KEY)` to be `KEY.toValue()`, rather than `KEY.getValue()`
Fedora 23 64bit with Radeon R9 R390 and default open source device driver. Output of uname -a:
Linux wotan.home.gateway 4.2.8-300.fc23.x86_64 #1 SMP Tue Dec 15 16:49:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Patch provided here. ChangeLog record
* source/main/RoRPrerequisites.h: Definition for MYGUI_GET_SCANCODE
should change on version 3.2.1.
**Note.** A number of further changes are needed to complete the …

MyGUI API changes to use getValue in 3.2.1.

---

BUILDING.md
source/main/main_sim/MainThread.cpp
source/main/terrain/TerrainObjectManager.cpp

* Fixes compiler errors when building without Angelscript (#534)
* Additionally, to avoid crashing when loading terrains, in resources/particles/water.particle this needs to be removed:
```
affector FireExtinguisher
{
effectiveness 	1
}
```

[Fix] Build without Angelscript

---

source/main/physics/Beam.cpp

Nothing sexy, but it works on all trailers/loads I have tested so far.
* Should fix #503

[Bugfix] Fixes incorrect 'reset in place' alignment on most trailers/loads

---

source/main/datatypes/rig_t.h
source/main/physics/Beam.cpp
source/main/physics/input_output/RigSpawner.cpp

Fix flares out of bounds access detection.
Fixed in Beam::setCustomLightVisible and Beam::getCustomLightVisible.
This fix bug #459

[Fix] Crash in Multiplayer due to out of bounds access

---

source/main/scripting/OgreAngelscript.cpp

> On Linux/amd64 with GNUC a class is treated very differently if the copy constructor is declared or not. A class with a copy constructor is always passed through a reference even when the function is declared to pass the type by value. When the copy constructor is not declared, the compiler will pass the type in the CPU registers instead, if the class is small enough. The real complicated part is that when the type is passed in the CPU registers, it is split up by the type of each member, so integer members are passed in the general purpose registers, and float members are passed in the floating point registers. This is why AngelScript doesn't allow these types to be passed by value, the implementation to support that in the native calling convention is just too difficult.
> I've added …

[Fix] AS: Pass by value for Ogre types

---

CMakeDependenciesConfig.txt

There seems to be an assumption that Paged Geometry will be built from
source and installed in `/usr/local`.  However it can now be installed
from standard repositories.  So we need to ensure that it is also
searched for in `/usr`.
1. On Fedora 23 Install ogre-pagedgeometry-devel from the standard repositories
2. Build RoR following the instructions on http://www.rigsofrods.com/wiki/pages/Compiling_Sources_under_Linux#Building_the_source_code up to the point where ''cmake'' should be run.
3. Run `cmake .`
''cmake'' configures RoR with Paged Geometry support.
''cmake'' fails to detect that the Paged Geometry library is installed.
Fedora 23 64bit with Radeon R9 R390 and default open source device driver. Output of `uname -a`:
Linux wotan.home.gateway 4.2.8-300.fc23.x86_64 #1 SMP Tue Dec 15 …

Add system include and library directories for Paged Geometry

---

source/configurator/CMakeLists.txt

Attempting to build the configurator complains that the object files
created for the configurator contain relocations that are not suitable
for a shared object.  This is solved by adding `-fPIC` to the compile
flags for the configurator.
1. Build RoR from source for Fedora 23, following the instructions at http://www.rigsofrods.com/wiki/pages/Compiling_Sources_under_Linux.
RoR is successfully built.
After running `make`, the final stage of linking the configurator fails:
```
[ 98%] Linking CXX executable ../../bin/RoRConfig
/usr/bin/ld: CMakeFiles/RoRConfig.dir/Configurator.cpp.o: relocation R_X86_64_32 against `_ZTV10HtmlWindow' can not be used when making a shared object; recompile with -fPIC
CMakeFiles/RoRConfig.dir/Configurator.cpp.o: error adding symbols: Bad value
collect2: error: …
```

Fix linking problem with configurator.

---

source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamFactory.cpp
source/main/physics/BeamFactory.h

This only affects the **interTruckCollision**:
* Instead of having a fixed number of thread tasks and skipping trucks based on the thread index, we now have one thread task per simulated truck.
* The workload is distributed dynamically by the operating system.
Positive side effect: A better (more uniform) CPU usage when multiple vehicles collide.
**Edit 1:**
* Moved parts of the multi-threading logic from the Beam class into the BeamFactory class.
**Edit 2:**
* Fixes a bug where only one truck would be simulated when the thread pool is deactivated.

[Cleanup] Simplifies the overly complex threading logic

---

bin/resources/skeleton/config/input.map

[Bugfix] Fixes an input.map conflict (boat steering)

---

source/main/terrain/TerrainGeometryManager.cpp

The mapbin file should be written into the ~/.rigsofrods/cache folder, but it's not
The ResourceGroupManager is not able to find the cache file

[Codechange] Disables terrain caching on linux

---

source/rig_file_input_output/RigDef_Parser.cpp

The parser did not skip misplaced subsections.

[Bugfix] Fixes trailer explosion (#434)

---

source/main/datatypes/beam_t.h
source/main/datatypes/rig_t.h
source/main/physics/Beam.cpp
source/main/physics/BeamForcesEuler.cpp
source/main/physics/input_output/RigSpawner.cpp

**Before**: sizeof(beam_t) = **208**
**After**: sizeof(beam_t) = **164**
All frequently accessed data is within the first 64 Bytes of the struct.

[Codechange] Clearing out and reordering of the beam_t members 

---

source/main/datatypes/node_t.h
source/main/datatypes/rig_t.h
source/main/gameplay/RoRFrameListener.cpp
source/main/gameplay/SceneMouse.cpp
source/main/physics/Beam.cpp
source/main/physics/BeamData.h
source/main/physics/BeamForcesEuler.cpp
source/main/physics/collision/Collisions.cpp
source/main/physics/collision/Collisions.h
source/main/physics/input_output/RigSpawner.cpp
source/main/physics/water/Buoyance.cpp
source/main/physics/water/Buoyance.h

**Before**: sizeof(node_t) = **240**
**After**: sizeof(node_t) = **128**
All frequently accessed data is within the first 64 Bytes of the struct.

[Codechange] Clearing out and reordering of the node_t members

---

source/main/gui/panels/GUI_MainSelector.cpp
source/main/gui/panels/GUI_MainSelector.h

The search results are now arranged according to the position of the first search hit.
And additionally ranked by relevance in the following way:
* name
* filename
* description
* author name
* author email
* alphabetically
Example search: **Tra**
**Before:**
1. Muddy Russian Tracks
2. Train Valley
**After:**
1. Train Valley
2. Muddy Russian Tracks

[Feature] Sort GUI Selector search results by relevance

---

source/main/physics/Beam.cpp

Prevents asynchronous calls to updateSimpleSkeleton()

[Bugfix] Fixes crash when entering the skeletonview on a coupled train

---

source/main/gameplay/RoRFrameListener.cpp
source/main/gui/GUIMenu.cpp
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamFactory.cpp

The truck creation from the in-game menu now respects the lowest node.

[Bugfix] Fixes Otter.airplane spawn error (#447)

---

source/main/physics/Beam.cpp

The battery light should go off, once the engine is running (and the alternator kicks in).

[Codechange] Reverts the latest changes to the battery light

---

source/main/gameplay/RoRFrameListener.cpp
source/main/physics/Beam.cpp
source/main/physics/Beam.h

> Despite a truck not having wheels2, pressing [ or ] will still bring up the gauge, and will repeatedly loop the "air" trigger sound. https://github.com/RigsOfRods/rigs-of-rods/issues/446#issue-114336116
* Don't display the pressure gauge if the truck has no wheels2
* Don't play the 'air trigger' sound if the truck has no wheels2
Tested with this truck: http://www.rigsofrods.com/repository/view/4383
Related to: #446

[Bugfix] Disable pressure buttons on trucks without wheels2

---

source/main/physics/Beam.cpp

Not needed and has the potential of breaking pre-spawned trucks.

[Codechange] Reverts height offset for free positioned trucks

---

source/rig_file_input_output/RigDef_Parser.cpp

Allows ```texcoords``` and ```cabs``` section parsing outside of ```submesh``` sections.

[Bugfix] Fixes cabs parsing on IHwood trailer

---

source/main/physics/BeamForcesEuler.cpp

Aside from the fact that most trailers do not even have an engine, it makes no sense to request engine power in the first place.

[Bugfix] Ties no longer request engine power

---

source/main/gameplay/BeamEngine.cpp

This bug was introduced after the release of 0.38.67 and should therefore be fixed.
Reference: https://github.com/RigsOfRods/rigs-of-rods/commit/fa1916e24365be8920ec32f4f6cf4fa450bf6bd1#diff-d47d357a254e0b1523e9a63fa4af7382R93

[Bugfix] Fixes engoption 'stallRPM' not being set

---

source/main/datatypes/node_t.h
source/main/datatypes/rig_t.h
source/main/physics/BeamForcesEuler.cpp

This does the following:
* Let ```int iswheel``` and ```int locked``` become shorts, to make room for another float.
* Move ```float collRadius``` into the first 64 bytes
* Fill the freed-up bytes with ```float wettime```
In addition ```wetstate``` and ```wettime``` are updated only if there is water on the terrain.

[Cleanup] Moved wettime back into node_t

---

bin/resources/scripts/base.as

I think that 'shopplanes' was just a typo, those spawners used to be called 'shopplane'.
Reference: http://www.rigsofrods.com/wiki/index.php?title=Object_Format

[Bugfix] Fixes the airplane spawner on some original maps

---

source/main/gameplay/RoRFrameListener.cpp
source/main/gfx/DustManager.cpp
source/main/gfx/DustManager.h
source/main/gfx/DustPool.cpp
source/main/gfx/DustPool.h
source/main/physics/Beam.cpp
source/main/terrain/TerrainManager.cpp

Moved the particle update routine out of the beam class.
-> Fixes #531
-> Fixes the particle part of this https://github.com/RigsOfRods/rigs-of-rods/issues/376

[Bugfix] Stops particle generation in pause menu (or after truck removal)

---

source/main/physics/Beam.cpp
source/main/physics/Beam.h

Those functions are now only called from the main thread (at most once per frame).
Also removed the obsolete ```lockSkeletonchange``` safeguard.

[Cleanup] Reworked the way 'showSkeleton' and 'hideSkeleton' are called

---

source/main/physics/BeamFactory.cpp

[Codechange] Attempt to fix compilation on ARM

---

source/main/gameplay/LandVehicleSimulation.cpp

```tc_present``` represents the presence of the dash icon.
Reference: http://www.rigsofrods.com/wiki/pages/Truck_Description_File/#TractionControl

[Bugfix] Brings back the traction control toggle

---

source/main/resources/CacheSystem.cpp

Fixes: #468
Is there any reason not to fix it like that?

[Bugfix] 'Fixes' the mini picture generation on Ogre 1.9

---

bin/resources/skeleton/config/input.map
source/main/gameplay/BeamEngine.cpp

Broken by this commit: https://github.com/RigsOfRods/rigs-of-rods/commit/a5724b12413de63ddaba3d51288ccdd29643bd5c#diff-d47d357a254e0b1523e9a63fa4af7382R309
* Does this affect the current engine code in any way?
**Edit:** I'm now pretty sure that this line is unnecessary.

[Bugfix] Fixes broken cruise control feature

---

source/main/physics/input_output/RigSpawner.cpp

The old parser has always used the visual beam diameter set via the 'set_beam_defaults' command, not the default value.

[Bugfix] Make proper use of the 'set_beam_defaults' visual beam diameter

---

source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamForcesEuler.cpp

Greatly improves the overall behavior of the wheel <-> ground surface interaction.
* This only affects wheel nodes
* You can enable this by appending ```HighResWheelNodeCollisions=Yes``` to your ```RoR.cfg```.
This could become a new parameter for truck files.

[Feature] New RoR.cfg option for high resolution (wheel-)node collisions

---

source/main/datatypes/rig_t.h
source/main/datatypes/wheel_t.h
source/main/physics/BeamForcesEuler.cpp
source/main/physics/input_output/RigSpawner.cpp

Brakes in RoR apply torque against the direction of rotation of each wheel:
https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/physics/BeamForcesEuler.cpp#L729
However the rotary speed has no effect on the amount of torque which is applied. This is changed by this PR. It will fix the following issue:
* Greatly reduces brake induced skidding in parking positions.
Best example: [Bobcat Skid-Steer](http://www.rigsofrods.com/repository/view/1962)
* Prevents brakes from making wheels spin backwards.
Best example: [1974 Lotus 76/1](http://www.rigsofrods.com/threads/118984-Lotus-76-1-for-current-and-future-ror-versions-(Updated-for-test-build-4))
* Removes the (now unnecessary) [slopebrake](http://www.rigsofrods.com/wiki/pages/Truck_Description_File/#SlopeBrake).
* Fixes the …

[Codechange] Revamped the braking code

---

source/main/physics/BeamForcesEuler.cpp

The brakes are already unlocked in the LandVehicleSimulation logic.

[Bugfix] Prevents brakes from unlocking if you step on the gas

---

source/main/gameplay/BeamEngine.cpp
source/main/gameplay/LandVehicleSimulation.cpp

* Fixes cruise control conflicting with the auto transmission (```autocurAcc``` was not set correctly)
* Moves the ```is_Eletric``` engine type check outside of the actual shifting code
* Makes the auto clutch release much more realistic:
It now depends on the speed difference, clutch force and current engine power

[Codechange] Revamped the auto clutch code

---

source/main/resources/CacheSystem.cpp

Those 'unknown' cache entries will now show up in the 'Unsorted' category
Fixes: #631

[Bugfix] Removes duplicate 'unknown' categories from the MainSelector

---

source/main/gfx/camera/CameraBehaviorIsometric.cpp
source/main/gfx/camera/CameraBehaviorOrbit.cpp
source/main/gfx/camera/CameraBehaviorVehicleSpline.cpp

Added GUI notification messages:
* When the limited camera zoom range is enabled/disabled
* When the auto tracking (camera rail) is enabled/disabled

[Codechange] Added missing notifications messages in the camera manager

---

source/main/physics/collision/Collisions.cpp
source/main/physics/collision/Collisions.h

More robust solution for #643
Reverts: https://github.com/ulteq/rigs-of-rods/commit/1319fd755431f6623fa97baec223ba47b3bb4c42

[Bugfix] Fixes event cache not being cleared on exit

---

source/main/gfx/camera/CameraBehaviorOrbit.cpp
source/main/gfx/camera/CameraBehaviorOrbit.h

Rather than only allowing truck mesh clipping, we now also allow terrain clipping.
* ```RShift + Space``` is mainly used for taking screenshots (where you want arbitrary camera movement)

[Codechange] 'RShift + Space' disables both camera zoom and rotation limits

---

bin/resources/sounds/defaults.soundscript

Partly reverts this: https://github.com/RigsOfRods/rigs-of-rods/commit/64158020f70011583362cb25f6912161faa68d9d
* Doesn't seem to change the sound in vehicles which use the new turbo mode, but fixes the sound of all vehicles which use the old turbo mode.

[Bugfix] Fixes the gain of the turbo sounds (old turbomode)

---

source/main/gameplay/LandVehicleSimulation.cpp

Cruise control can be used to hold a steady engine rpm in neutral. Depressing the brake or clutch pedal should not toggle it off in that case.

[Codechange] Brake and clutch should not stop the rpm cruise control

---

source/rig_file_input_output/RigDef_Parser.cpp

The fourth node of the rotating plate was parsed incorrectly due to a typo.
Fixes: #381

[Bugfix] Fixes broken rotator parsing

---

source/main/physics/input_output/RigSpawner.cpp

The ```spring_rate``` was used as ```attachment_rate``` due to a typo.

[Bugfix] Fixes broken slidenode parsing

---

source/main/physics/BeamForcesEuler.cpp
source/rig_file_input_output/RigDef_Parser.cpp
source/rig_file_input_output/RigDef_Regexes.h

Parser compatibility fixes

---

source/main/gameplay/RoRFrameListener.cpp
source/main/gameplay/RoRFrameListener.h
source/main/gfx/AdvancedScreen.h
source/main/gui/GUIManager.cpp
source/main/gui/GUIManager.h
source/main/gui/panels/GUI_SimUtils.cpp
source/main/gui/panels/GUI_SimUtils.h

* Reduces the screenshot key bounce time by half
* Adds time stamps to the screenshot file name
* Automatically hides screen notifications before another screenshot is taken
* Gets rid of the camera stuttering when taking a screenshot (introduced by: 1ff982a4b8bee32d6caf715503c8c31b52350c63)
* Prevents recording partially updated trucks when taking a screenshot (introduced by: 1ff982a4b8bee32d6caf715503c8c31b52350c63)
Fixes: #360
Fixes: #473

[Codechange] Some screenshot taking improvements

---

source/main/physics/Beam.cpp

The height of pre-spawned trucks is relative to the lowestnode

[Bugfix] Fixes y-pos of pre spawned trucks

---

source/rig_file_input_output/RigDef_Parser.cpp

Unified the coding style
Prevents completly trashing the driving aid when syntax errors occur in the mode settings

[Cleanup] Anti lock brake and traction control parsing cleanup

---

source/main/physics/Beam.cpp

This might fix Bug #: 1013: http://www.rigsofrods.com/threads/111967-Bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1307247&viewfull=1#post1307247
**Edit:** Bug 1013 must be caused by sth. else.

[Codechange] lockNodes should not be changed outside of the truck parser

---

source/main/datatypes/rig_t.h
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamForcesEuler.cpp

Prevents unsynchronized read/write access to `p2->Forces`, when `p2truck != 0`.
Should fix: #465
Related with: #189

[Bugfix] Removes race condition in calcBeams

---

source/main/gui/panels/GUI_SimUtils.cpp
source/main/gui/panels/GUI_VehicleDescription.cpp

Show the beginning of the vehicle name instead of the end.
Fixes: #401
Bad solution, because it uses hard-coded values for [MyGUI::EditBox::setMaxTextLength(size_t 	_value)	
](http://mygui.info/docs/class_my_g_u_i_1_1_edit_box.html#a0931c6bc59eb4ca79b8c6d0e4f3bd466)

[Codechange] Trim vehicle name to fit into the 't' menus

---

source/rig_file_input_output/RigDef_Parser.cpp

Truly skip unsupported `rigidifiers` and `turboprops2` sections.
* Less warnings when parsing the [1949 Ford](http://www.rigsofrods.com/repository/view/2579).
Interpret `submesh` sections without subsections as `cab` subsection.
* Fixes `cab` parsing on the [Audio 80 Quattro](http://www.mediafire.com/?tc927day8vat1q7).

[Codechange] Some changes to the parser ('cab', 'rigidifiers', 'turboprops2')

---

source/main/gameplay/RoRFrameListener.cpp
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamForcesEuler.cpp
source/main/scripting/ScriptEngine.cpp

You can now translate and rotate the truck while pressing (and holding) the repair truck key.
This implements @Speciesx awesome idea on how to improve the reset in place feature.
Controls:
* `TRUCK_ACCELERATE` -> translate upward
* `TRUCK_BRAKE` -> translate downward
* `TRUCK_STEER_LEFT` -> rotate left
* `TRUCK_STEER_RIGHT` -> rotate right
* `CHARACTER_FORWARD` -> translate forward
* `CHARACTER_BACKWARDS` -> translate backward
* `CHARACTER_SIDESTEP_RIGHT` -> translate right
* `CHARACTER_SIDESTEP_LEFT` -> translate left

[Feature] Overworked the reset in place feature

---

source/main/gameplay/RoRFrameListener.cpp

The `std::asctime` output is less pretty, but good enough as fallback.

[Bugfix] Fixes build errors with older GCC versions

---

source/main/gameplay/RoRFrameListener.cpp
source/main/gfx/camera/CameraBehaviorStatic.cpp
source/main/gfx/camera/CameraBehaviorStatic.h

* Added a minimum update interval of two seconds
* Added line-of-sight checks (terrain only)
* Added truck movement prediction (for both new camera position and line-of-sight checks)
* Pressing `CAMERA_RESET` will initiate a camera position re-evaluation
Fixes: #403

[Feature] Overworked the cinematic camera

---

source/main/gameplay/RoRFrameListener.cpp
source/main/gameplay/RoRFrameListener.h

Prevents showing partially updated flexbodies in the pause menu.

[Bugfix] Finish flexbody update before entering the pause menu

---

source/main/gameplay/SceneMouse.cpp
source/main/gfx/camera/CameraBehaviorVehicle.cpp
source/main/gfx/camera/CameraBehaviorVehicle.h
source/main/physics/Beam.cpp
source/main/physics/Beam.h

You can now choose any node as orbit camera center by clicking on it with the middle mouse button.
Holding `LSHIFT` while clicking will keep your current camera position, otherwise you keep your relative angle to the orbit center.
If you want to disable the custom orbit center just click anywhere with the middle mouse button.
Fixes: #712

[Feature] Selectable orbit camera center

---

source/main/gameplay/RoRFrameListener.cpp

Fixes the flexbody artefacts during advanced reset in place

[Bugfix] Finish flexbody update before displacing a truck

---

source/main/gameplay/RoRFrameListener.cpp

Advanced repair will only be toggled on when you hold 'Backspace' without translating or rotating the truck for 1 seconds

[Codechange] Changed the advanced repair toggle behavior

---

source/main/gameplay/RoRFrameListener.cpp
source/main/gameplay/RoRFrameListener.h
source/main/gui/GUIManager.cpp
source/main/gui/GUIManager.h
source/main/gui/panels/GUI_SimUtils.cpp
source/main/gui/panels/GUI_SimUtils.h

The `COMMON_HIDE_GUI` event now hides:
* The current and all upcoming notice messages
* The fps box (if visible)
* The truck info box (if visible)
* The truck hud
Fixes: #240

[Codechange] Hiding the GUI will also hide the notice messages

---

source/main/gameplay/RoRFrameListener.cpp
source/main/physics/Beam.cpp

This also fixes the advanced repair rotation on big vehicles (and on slow rotations).
Rounding is no longer needed since the reset-in-place revamp: https://github.com/RigsOfRods/rigs-of-rods/pull/703

[Codechange] Rounding the truck rotation is no longer needed

---

source/rig_file_input_output/RigDef_Regexes.h

Example truck: http://www.rigsofrods.com/repository/view/5449
Reference:
http://www.rigsofrods.com/wiki/pages/Truck_Description_File#Commands
http://www.rigsofrods.com/wiki/pages/Truck_Description_File#Commands2

[Bugfix] Fixes commands parsing on some trucks

---

source/main/gameplay/RoRFrameListener.cpp
source/main/gameplay/RoRFrameListener.h

Doubling / halving the simulation speed now takes exactly 2 seconds.
Toggling the custom simulation speed on / off is no longer delayed.
It is now only limited by how fast you can press the `COMMON_RESET_SIMULATION_PACE` button.

[Codechange] Made the simulation speed modifiers fps independent

---

source/main/gfx/camera/CameraBehaviorVehicle.cpp
source/main/physics/Beam.cpp
source/main/physics/Beam.h

This re-implements the old "anti-jitter" `dt` calculation while maintaining a smooth orbit camera rotation when the simulation speed is changed.
Reverts this: RigsOfRods@059c8c9
Fixes: #734

[Codechange] 'Jitter' free slow motion capable orbit camera

---

source/main/resources/ContentManager.cpp

Already created and registered at https://github.com/mikadou/rigs-of-rods/blob/23a8968ff946b1b1a707a925f4be714770190db5/source/main/resources/ContentManager.cpp#L234

[Cleanup] Remove redundant ColoredTextAreaOverlayElementFactory

---

source/main/physics/Beam.cpp

Needs a lot of testing, to make sure it does not mess up any pre-spawned trucks.

[Feature] Avoid spawning trucks inside of meshes

---

source/main/gameplay/RoRFrameListener.cpp
source/main/gameplay/RoRFrameListener.h
source/main/gui/GUIMenu.cpp
source/main/main_sim/MainThread.cpp
source/main/physics/Beam.cpp

* Fixes the position of all kinds of pre-spawned trucks
* Fixes the position of trucks spawned in spawnboxes
* Fixes the position of trucks spawned on mesh terrains
Side-effect: Terrains without pre-spawned trucks won't automatically open a vehicle selector.
Plays nicely with: #752

[Bugfix] Fixed up the truck spawning code

---

source/main/physics/Beam.cpp
source/main/physics/BeamData.h
source/main/physics/collision/PointColDetector.cpp

One vehicle standing, one vehicle driving at 80 km/h. The screenshots show the state after the collision.
**Without this patch**: ![](http://abload.de/img/cc_oldh2qaw.jpg)
**With this patch**: ![](http://abload.de/img/cc_newgdqmz.jpg)

[Cleanup] Cleaned up the collcabrate calculation

---

source/rig_file_input_output/RigDef_Parser.cpp

[Bugfix] Fixes commands2 'affectEngine' and 'needsEngine' parsing

---

source/main/gfx/camera/CameraBehaviorStatic.cpp

Prevents premature or delayed updating of the camera position, when the simulation speed is modified.

[Codechange] Cinematic camera takes the simulation speed into account

---

source/main/main_sim/MainThread.cpp

Fixes the initial character orientation on maps like N-Labs or F1 Track
Temporary until we allow defining a spawn rotation in the terrn file

[Codechange] Emulates the character spawn rotation of older RoR versions

---

doc/angelscript/BeamClass.h
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/scripting/ScriptEngine.cpp

Now you can get a position of a node using:
```
BeamClass @np_truck0 = game.getTruckByNum(0);		
vector3 vec = np_truck0.getNodePosition(121);
```

Added angelscript function getNodePosition

---

source/main/physics/BeamFactory.cpp

I am trying to get rigs of rods working again on FreeBSD.
Since I get some linking error with 270e084 (like multiple definition of function located at paged geometry). That's why I am looking to build the latest commit instead.
I finished the build but I am still getting multiple definition of function.
Example:
```
/usr/local/lib/libMyGUI.OgrePlatform.a(MyGUI_OgreRenderManager.cpp.o): In function `MyGUI::OgreRenderManager::getTexture(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)':
/usr/ports/x11-toolkits/mygui-ogre/work/mygui-MyGUI3.2.2/Platforms/Ogre/OgrePlatform/src/MyGUI_OgreRenderManager.cpp:(.text+0x3060): multiple definition of `MyGUI::OgreRenderManager::getTexture(std::__1::basic_string<char, std::__1::char_traits<char>, …
```

Add FreeBSD specific include

---

source/rig_file_input_output/RigDef_File.h

The default group is `-1`.
Fixes: #829

[Bugfix] Fixes (default group) lockgroup parsing

---

source/main/gui/panels/GUI_RigEditorLandVehiclePropertiesWindow.cpp
source/main/gui/panels/GUI_RigEditorLandVehiclePropertiesWindow.h
source/main/physics/input_output/RigSpawner.cpp
source/main/physics/input_output/RigSpawner.h
source/main/resources/CacheSystem.cpp
source/main/rig_editor/RigEditor_Main.cpp
source/main/rig_editor/rig_data/RigEditor_MeshWheel2.cpp
source/main/rig_editor/rig_data/RigEditor_Rig.cpp
source/main/rig_editor/rig_data/RigEditor_Rig.h
source/main/rig_editor/rig_data/RigEditor_RigProperties.cpp
source/main/rig_editor/rig_data/RigEditor_RigProperties.h
source/rig_file_input_output/RigDef_File.h
source/rig_file_input_output/RigDef_Node.h
source/rig_file_input_output/RigDef_Parser.cpp
source/rig_file_input_output/RigDef_Parser.h
source/rig_file_input_output/RigDef_SequentialImporter.cpp
source/rig_file_input_output/RigDef_SequentialImporter.h
source/rig_file_input_output/RigDef_Serializer.cpp
source/rig_file_input_output/RigDef_Serializer.h
source/rig_file_input_output/RigDef_Validator.cpp
source/rig_file_input_output/RigDef_Validator.h

Since everyone use a newer compiler, i think we could replace `boost::shared_ptr` with `std::shared_ptr`.

replaced boost::shared_ptr with std::shared_ptr

---

cmake/DependenciesConfig.cmake

Added CMake option for building with ogre 1.8

Added CMake option for building with ogre 1.8

---

source/rig_file_input_output/RigDef_Parser.cpp
source/rig_file_input_output/RigDef_Parser.h
source/rig_file_input_output/RigDef_Regexes.h

I've replaced `boost::regex`, `boost::smatch` and `boost::ssub_match` with `std` and yes, ror still works.

replaced boost::regex with std::regex

---

source/main/physics/Beam.cpp
source/main/physics/input_output/RigSpawner.cpp
source/main/physics/input_output/RigSpawner.h

The truck nodes are now translated and rotated after the RigSpawner is done.
Fixes: #820 
Positive side effect: Trucks load a lot faster.

[Codechange] Overworked the truck rotation during spawning

---

source/configurator/CMakeLists.txt
source/main/CMakeLists.txt

Fixes linker error on Linux, when Ogre is build with Boost enabled:
```
/usr/bin/ld: CMakeFiles/RoRConfig.dir/Configurator.cpp.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
/usr/lib/libboost_system.so.1.60.0: error adding symbols: DSO missing from command line
```

[Codechange] Added linker flag '-lboost_system' on unix

---

source/main/MainThread.cpp
source/main/gameplay/RoRFrameListener.cpp
source/main/gameplay/RoRFrameListener.h
source/main/gfx/camera/CameraBehaviorOrbit.cpp
source/main/gfx/camera/CameraBehaviorOrbit.h
source/main/gfx/camera/CameraBehaviorVehicle.cpp
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamData.h
source/main/physics/BeamFactory.cpp
source/main/physics/BeamFactory.h
source/main/physics/BeamForcesEuler.cpp
source/main/scripting/ScriptEngine.cpp

Read this first: https://github.com/RigsOfRods/rigs-of-rods/pull/858#issuecomment-216222555
* Removed the BeamFactory worker thread
* Merged threadentry() with UpdatePhysicsSimulation()
* Moved UpdatePhysicsSimulation() from Beam to BeamFactory
* Fixed crash when `DisableThreadPool=Yes`
**Edit:**
* Moved all physics related updates into `BeamFactory::calcPhysics`
* Chopped the  `Beam::frameStep` into several smaller functions
* Added new `syncWithSimThread` method, which is now called at the beginning of the `RoRFrameListener::frameStarted()` method
* SimThread and MainThread no longer access the truck engine at the same time
* `updateFlexbodiesPrepare()` and `UpdateEvents()` no longer run in parallel with the SimThread

[Cleanup] Streamlined the physics simulation update routine

---

source/main/physics/Beam.h

Brings back the ZeroedMemoryAllocator temporarily
Fixes: #859

[Bugfix] Fixes segfault on auriga

---

source/main/gameplay/RoRFrameListener.cpp

Prevents spawning the truck at a wrong position after aborting the selector window.

[Bugfix] Always reset the reload box when the load selector is closed

---

source/main/physics/Beam.h

Beam.h:593:14: error: ‘shared_ptr’ is not a member of ‘std’

[Bugfix] Fixes build error with Ogre 1.8

---

source/main/MainThread.cpp
source/main/main.cpp

Adapted from @AnotherFoxGuy: https://github.com/RigsOfRods/rigs-of-rods/pull/807/commits/8dd75006c42cd054347f8ef27178a980edada9fa, https://github.com/RigsOfRods/rigs-of-rods/pull/807/commits/7d4f96f8561241db708cfb0814bce9f81d14c6c1 and https://github.com/RigsOfRods/rigs-of-rods/pull/807/commits/55add7cf8702fbaaeec93e255bd9cc657c1a1eec
Closes: https://github.com/RigsOfRods/rigs-of-rods/pull/807
>Now you can join an MP-server with
>```
>RoR.exe -joinserver="server:port"
>```
>for example
>```
>RoR.exe -joinserver="ror.ezzg.be:14151"
>```

[Feature] Added command line parameter '-joinserver'

---

source/main/physics/BeamFactory.cpp

Prevents calling methods on already deleted or soon to be deleted trucks
e.g. trucks with the following states: `NETWORKED_INVALID`, `RECYCLE`, `DELETED`

[Bugfix] Fixes multiplayer crash when other client disconnects

---

source/main/physics/BeamFactory.cpp

Fixes 'updateVisual' not being called on NETWORKED trucks

[Bugfix] Reverts updateVisual condition check

---

source/main/gameplay/RoRFrameListener.cpp
source/main/physics/BeamFactory.cpp
source/main/physics/BeamFactory.h

**Singleplayer:**
* Reloading a truck now properly deletes the old truck
**Multiplayer:**
* Fixes crash (on linux) when a remote player deletes trucks

[Codechange] Unified truck deletion methods

---

source/main/MainThread.cpp

Appending `SkipMainMenu=Yes` to your RoR.cfg file allows you to skip the main menu during startup.

[Feature] Added RoR.cfg option to skip the main menu

---

source/main/gameplay/BeamEngine.cpp

Prevents releasing the clutch without throttle input while standing still.
Only affects `AUTOMATIC` and `SEMIAUTO` transmission modes.

[Bugfix] Fixes truck starts moving when using commands

---

source/main/gameplay/RoRFrameListener.cpp
source/main/gui/panels/GUI_MainSelector.cpp
source/main/gui/panels/GUI_MainSelector.h

Selector window needs to be focused (can be achieved by pressing `/`).
`ESC` needs to be pressed twice, for some reason.

[Codechange] ESC cancels selector window

---

source/main/gui/DashBoardManager.cpp
source/main/physics/Beam.cpp

Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/905

[Bugfix] Fixes 'nullptr' dereferencing

---

source/main/gameplay/Character.cpp
source/main/gameplay/Character.h
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/terrain/map/SurveyMapTextureCreator.cpp

Appending `HideOwnNetLabel=Yes` to the RoR.cfg will hide your own net labels in multiplayer.
Related with: #479

[Feature] Added RoR.cfg option 'HideOwnNetLabel'

---

source/main/MainThread.cpp
source/main/gui/GUIMp.cpp
source/main/network/Network.cpp
source/main/network/Network.h
source/main/network/NetworkStreamManager.cpp
source/main/network/Streamable.cpp

* Simply run `GUI_Multiplayer::update` every two seconds
* Replaced mutex construct with std::atomic
* Removed duplicate `getUID()` method
* Only hold `m_send_work_mutex` when needed

[Cleanup] Minor network cleanup

---

source/main/network/Network.cpp
source/main/network/NetworkStreamManager.cpp
source/main/network/NetworkStreamManager.h
source/main/network/protocol/rornet.h
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamData.h
source/main/physics/BeamFactory.cpp
source/main/physics/BeamFactory.h
source/main/physics/BeamForcesEuler.cpp
source/main/scripting/ScriptEngine.cpp

[Codechange] Implements proper truck deletion in multiplayer

---

source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamFactory.cpp

Only affects the new keyboard shortcuts '[' and ']'

[Codechange] Skip preloaded trucks when cycling through all trucks

---

source/main/gui/GUIManager.cpp
source/main/gui/panels/GUI_GameChatBox.cpp

But only if you have enabled the 'auto-hide' chat box option.
The default key for hiding the GUI is `u`.

[Codechange] Hiding the GUI now also hides the chatbox

---

bin/resources/skeleton/config/input.map
source/main/gameplay/RoRFrameListener.cpp
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/utils/InputEngine.cpp
source/main/utils/InputEngine.h

The videocamera state is stored per truck
Default key: 'CTRL+V'

[Feature] Added key shortcut to toggle videocamera on/off

---

bin/resources/hydrax/HydraxDefault.hdx

Up to 30% more FPS when Hydrax is enabled, with negligible visual differences.
* [PG_Complexity=264](https://files.gitter.im/RigsOfRods/rigs-of-rods/SGz0/RoR_2016_05_25_13_57_19_242.jpg) ~ 75 FPS
* [PG_Complexity=200](https://files.gitter.im/RigsOfRods/rigs-of-rods/SGz0/RoR_2016_05_25_13_55_38_919.jpg) ~ 100 FPS

[Codechange] Reduced Hydrax 'PG_Complexity'

---

bin/resources/managed_materials/managed_submesh.material

The user will use in their material file:
```
import * from "managed_submesh.material"
//for the body of the submesh truck
material body : material RoR/Submesh/Body
{
//diffuse texture
set_texture_alias diffuse       image.dds
//toggles on with headlights
set_texture_alias emissive      image.dds
//reflective, based on type of material, can either be alpha based or grayscale
set_texture_alias reflective    image.dds
//prelighting or a/o, can be white to have none
set_texture_alias Lighting      image.dds
}
//for the wheels of the truck
material wheel : material RoR/Submesh/Wheels/Alpha
{
//diffuse texture
set_texture_alias diffuse       image.dds
//reflective, based on type of material, can either be alpha based or grayscale
set_texture_alias reflective    image.dds
//prelighting or a/o, …
```

Derbymutt managed submesh 1

---

source/main/gameplay/BeamEngine.cpp

Prevents being stuck in 'NEUTRAL'.

[Bugfix] Fixes truck reset not aborting switching operations

---

source/main/datatypes/node_t.h
source/main/gameplay/RoRFrameListener.cpp
source/main/gameplay/SceneMouse.cpp
source/main/gfx/VideoCamera.cpp
source/main/gfx/camera/CameraBehaviorVehicle.cpp
source/main/gfx/camera/CameraBehaviorVehicleCineCam.cpp
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamFactory.cpp
source/main/physics/BeamFactory.h
source/main/physics/air/AirBrake.cpp
source/main/physics/air/TurboJet.cpp
source/main/physics/collision/Collisions.cpp
source/main/physics/flex/FlexAirfoil.cpp
source/main/physics/flex/FlexBody.cpp
source/main/physics/flex/FlexMesh.cpp
source/main/physics/flex/FlexMeshWheel.cpp
source/main/physics/flex/FlexObj.cpp
source/main/physics/input_output/RigSpawner.cpp

Main product:
* Removed redundant `node_t` member `smoothpos`
* Removed unused `node_t` member `collRadius`
* Reduced the size of some `node_t` members
Secondary product:
* Refactored `updateTruckPosition` into `calculateAveragePosition` and `updateBoundingBox`
* Refactored `handleTruckPosition` into `preUpdatePhysics` and `postUpdatePhysics`
Both `preUpdatePhysics` and `postUpdatePhysics` are now run by the sim thread.

[Cleanup] Tidied up the 'node_t' struct some more

---

source/main/gui/panels/GUI_MainSelector.cpp

The key focus is now on the search line, when the selector is opened
You can now switch the focus back and forth between the search bar and the widget itself by pressing Tab

[Codechange] Overworked the main selector interaction

---

source/rig_file_input_output/RigDef_Regexes.h

Fixes parsing of commands with whitspaces in the description
Reference: https://github.com/RigsOfRods/rigs-of-rods/pull/1010#issuecomment-223228690

[Bugfix] Fixes Mitsubishi L200 DI-D parsing

---

bin/resources/skeleton/config/input.map
source/main/gameplay/RoRFrameListener.cpp
source/main/terrain/TerrainObjectManager.cpp
source/main/terrain/TerrainObjectManager.h
source/main/utils/InputEngine.cpp
source/main/utils/InputEngine.h

Controls:
* Toggle Editor `CTRL+Y` (`editor_out.cfg` is overwritten when you leave the terrain  #editor)
* Toggle object auto tracking (aligns the character with the currently selected object) `SPACE`
* Enter nearest object (in relation to character / free camera position) `Enter`
* Translate / Rotate object (similar to advanced truck reset)
* Cycle through all terrain objects `CTRL+[` and `CTRL+]`
* Cycle through all rotation axes `r`
* Reset the current object `i`
Structurally complete, but far from perfect.

[Feature] Implemented a simple terrain editor

---

bin/resources/mygui/VehicleDesc.layout
source/main/gui/panels/GUI_SimUtils.cpp

Before:
After:
**On a related note: Is `CodeGeneratorSettings` in `VehicleDesc.layout` needed?**

Fixed grammar mistakes in the vehicle description/information boxes

---

source/main/terrain/TerrainObjectManager.cpp
source/main/utils/WriteTextToTexture.cpp
source/main/utils/WriteTextToTexture.h

Things done:
- Updated the code copied from the ogre wiki (http://www.ogre3d.org/tikiwiki/tiki-index.php?page=HowTo%3A+Write+text+on+texture)
- Added 2 more variables to ```drawTextOnMeshTexture```
- Documented WriteTextToTexture.h
Variables added:
_drawTextOnMeshTexture x, y, w, h, r, g, b, a, option,_ **font size, font dpi,** _fontname, text_
_drawTextOnMeshTexture 0.1, 0.1, 0.9, 0.9, 1, 1, 1, 1, c,_ **20, 400,**  _CyberbitEnglish {{argument1}}_
Screenshot:
Fixes #1088

[Fix] Fixed text being small on Dynamic Signs

---

source/main/physics/Beam.h
source/main/physics/BeamFactory.cpp

[Bugfix] Fixes 'SLEEPING' vehicles spawn at (0,0,0)

---

source/main/audio/SoundManager.cpp

Fixes: #1054
Trivia: `recomputeAllSources()` used to be dead code until it was fixed in this commit: https://github.com/RigsOfRods/rigs-of-rods/commit/491c3ddbc35922f1729b4dbc830c9b35218eeafc Hence, it should not be a problem to disable it until we overwork the audio system.

[Bugfix] Hotfix for the sound loop issue

---

source/main/physics/Beam.cpp
source/main/physics/BeamData.h
source/main/physics/BeamForcesEuler.cpp
source/main/physics/input_output/RigSpawner.cpp
source/main/physics/input_output/RigSpawner.h

Fixes visual glitch when ties become visible

[Cleanup] Simplifies creation of visual beams

---

source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamData.h
source/main/physics/BeamFactory.h
source/main/physics/BeamForcesEuler.cpp
source/main/physics/input_output/RigSpawner.cpp
source/main/scripting/ScriptEngine.cpp

* Fixes the handling of inter-truck-beams (hooks and ties) on truck deletion.
* Fixes segfaults and state inconsistencies when trucks are removed or reset while they are hooked or tied to other trucks
* Fixes: #498
Side-effect: Skeleton view changes are now properly propagated through all interconnected trucks.

[Bugfix] Proper destruction of inter-truck-beams

---

source/main/resources/rig_def_fileformat/RigDef_Parser.cpp

Reference: https://github.com/only-a-ptr/ror-legacy-svn-trunk/blob/master/source/main/physics/input_output/SerializedRig.cpp#L1290

[Bugfix] Fixes 'set_node_defaults' options parsing

---

source/main/gui/panels/GUI_MainSelector.cpp

The 'skinzip' selector did not show up when closing the selector window by pressing 'Enter'

[Bugfix] Fixes broken 'skinzip' selection

---

source/main/utils/Settings.cpp

Also fixes some code formatting inconsistencies

[Cleanup] Fixes warning 'C4715'

---

source/main/terrain/TerrainManager.cpp

Fixes invisible water surface when 'Hydrax' is enabled
Reference: https://github.com/RigsOfRods/rigs-of-rods/commit/a10c5a86068352f8948019f853f75daca7efa7c4#diff-39389de445cad8e4eaae81a281ddaa24R357

[Bugfix] Fixes Hydrax

---

source/main/terrain/TerrainGeometryManager.cpp

Reverts: 02623cfbdfc750667677dfa555f2cfe04d5a8157 for performance reasons
Opens: #1053

[Codechange] Reactivates new heightfinder

---

source/main/physics/Beam.cpp
source/main/physics/BeamData.h
source/main/physics/BeamForcesEuler.cpp

removeInterTruckBeam() must be called from the sim-thread

[Bugfix] Fixes data race in 'hookToggle'

---

source/main/physics/BeamFactory.cpp

This only affects players with at least 6 cores

[Codechange] Optimized thread pool size calculation

---

source/main/gui/panels/GUI_MainSelector.cpp

The cancel button must not disconnect you from the server once you are past the main menu

[Bugfix] Fixes 'MainSelector' cancel button

---

source/main/physics/BeamFactory.cpp
source/main/physics/BeamFactory.h

* Trucks now stay active for at least 10 seconds before they go sleeping again.
* Trucks won't go sleeping if another `SIMULATED` truck is nearby.
But it also brings back parts of the 0.38.67 sleeping behavior:
* Sets of `SIMULATED` trucks can go sleeping if neither of them is active (player in them)

[Codechange] Reworked the sleeping mechanism

---

source/main/utils/Settings.cpp
source/main/utils/Settings.h

Makes 'FOV External' and 'FOV Internal' plain cvars.
Related with: #1163

[Bugfix] Fixes 'FOV' setting

---

source/main/physics/BeamFactory.cpp

This automatically activates all trucks which might soon get hit by any moving truck in the scene.

[Codechange] Allow snowball effect truck activation

---

source/main/gameplay/BeamEngine.cpp

Avoids invalid gearbox states (e.g. gearshift in `NEUTRAL` but gear 1 engaged).

[Bugfix] Avoid switching operations in neutral mode

---

source/main/resources/rig_def_fileformat/RigDef_File.h

Reference: https://github.com/only-a-ptr/ror-legacy-svn-trunk/blob/master/source/main/physics/input_output/SerializedRig.cpp#L4635

[Bugfix] Fixes 'ManagedMaterial' string comparison

---

source/main/physics/RigSpawner.cpp

Skip existing managed materials
Reference: https://github.com/only-a-ptr/ror-legacy-svn-trunk/blob/master/source/main/physics/input_output/SerializedRig.cpp#L4615

[Codechange] Recreate old parser behavior

---

source/main/physics/BeamForcesEuler.cpp

The steering wheel rotation angle (`hydrodirwheeldisplay`) must not be affected by animators.
Fixes: #1100

[Bugfix] Fixes conflict between animators and hydros

---

source/main/resources/rig_def_fileformat/RigDef_Parser.cpp

Reference:
a) https://github.com/only-a-ptr/ror-legacy-svn-trunk/blob/master/source/main/physics/input_output/SerializedRig.cpp#L4609-L4616
b) https://github.com/only-a-ptr/ror-legacy-svn-trunk/blob/master/source/main/physics/input_output/SerializedRig.cpp#L4928-L4929
b) can only be reached if a) passes.

[Codechange] Changes 'ParseManagedMaterials' error handling

---

source/main/physics/collision/DynamicCollisions.cpp

Typo was introduced by this commit: fa85f6a412c6c8999b59c0a6c2a15cb7c252b0f8

[Bugfix] Fixed a typo

---

source/main/gameplay/BeamEngine.cpp

Switching through the gearbox modes (automatic, semiautomatic, manual ...) no longer messes with the current gear selection.

[Codechange] 'toggleAutoMode' improvement

---

source/main/gui/Dashboard.cpp

Problem: duplicate RTT texture "dashtexture". It's strange that OGRE didn't complain when re-creating texture with the same name.
Fixes #1148

[Bugfix] Dashboard frozen after map switch

---

source/main/datatypes/rig_t.h
source/main/gameplay/BeamEngine.h
source/main/gameplay/LandVehicleSimulation.cpp
source/main/physics/Beam.cpp

* Speed and RPM hold now take the engine characteristics into account
* The automatic throttle input is now much smoother
* It is now much easier to set the desired target speed or RPM
The default cruise control keyboard shortcuts look like this:
```
TRUCK_CRUISE_CONTROL           Keyboard             EXPL+SPACE 
TRUCK_CRUISE_CONTROL_READJUST  Keyboard             EXPL+CTRL+SPACE 
TRUCK_CRUISE_CONTROL_ACCL      Keyboard             EXPL+CTRL+R 
TRUCK_CRUISE_CONTROL_DECL      Keyboard             EXPL+CTRL+F 
```

[Codechange] Improved cruise control feature

---

source/main/gameplay/Character.cpp
source/main/gameplay/Character.h
source/main/gameplay/RoRFrameListener.cpp

* Avoids getting stuck in the vehicle selector window when you cancel it
This moves the character back to where he was before he entered the collision box that triggers the vehicle selection.

[Bugfix] Fixes SelectorWindow loop on some maps

---

source/main/gameplay/Character.cpp

You can now always free yourself from being stuck in the ground by pressing and holding the 'Jump' button.

[Bugfix] Prevents character getting stuck in the ground

---

source/main/physics/Beam.cpp

The game was often crashing with:
*** buffer overflow detected ***: /home/pp/rigs-of-rods/install/bin/RoR terminated
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x790cb)[0x7f971d3a30cb]
/lib/x86_64-linux-gnu/libc.so.6(__fortify_fail+0x54)[0x7f971d4442c4]
/lib/x86_64-linux-gnu/libc.so.6(+0x118240)[0x7f971d442240]
/lib/x86_64-linux-gnu/libc.so.6(+0x1177f9)[0x7f971d4417f9]
/lib/x86_64-linux-gnu/libc.so.6(_IO_default_xsputn+0xa9)[0x7f971d3a7a09]
/lib/x86_64-linux-gnu/libc.so.6(_IO_vfprintf+0xcda)[0x7f971d3785aa]
/lib/x86_64-linux-gnu/libc.so.6(__vsprintf_chk+0x84)[0x7f971d441884]
/lib/x86_64-linux-gnu/libc.so.6(__sprintf_chk+0x7d)[0x7f971d4417dd]
/home/pp/rigs-of-rods/install/bin/RoR(_ZN4Beam16updateDashBoardsEf+0x11f1)[0x558165626261] …

[Bugfix] Fix buffer overflow crash

---

source/main/gui/panels/GUI_GameSettings.cpp

Fixed SpeedUnit setting

---

source/configurator/Configurator.cpp

Disabled "Allow DirectX9Ex" setting

---

source/main/gui/TruckHUD.cpp
source/main/gui/panels/GUI_DebugOptions.cpp
source/main/physics/BeamFactory.cpp
source/main/physics/BeamForcesEuler.cpp

When building for openSUSE I discovered some warnings (one of them is considered an error by RPMLint).
**First kind of warning:**
> I: Program causes undefined operation
>    (likely same variable used twice and post/pre incremented in the same expression).
>    e.g. x = x++; Split it in two operations.
> W: rigsofrods sequence-point
Triggered by:
1. `TruckHUD.cpp`: It is not defined which value `overlayElement` should have after the `=`.
(Because it is not defined which `=` should be done first).
2. `BeamForcesEuler.cpp`, same kind of issue: It is not defined which should be executed first so `contacted` might be set by `(contacted = ... )` before the  code at the right side of the `|` operator is executed, or it might be executed after that part so the right side can result in two …

Fixed compiler warnings and undefined operation

---

cmake/GenerateVersionInfo.cmake
source/configurator/Configurator.cpp
source/main/gui/panels/GUI_GameAbout.cpp
source/main/gui/panels/GUI_GameConsole.cpp
source/main/utils/PlatformUtils.cpp
source/main/utils/Utils.cpp
source/version_info/RoRVersion.cpp.in
source/version_info/RoRVersion.h

Use [SOURCE_DATE_EPOCH](https://reproducible-builds.org/specs/source-date-epoch/) environment variable if available to force build date and time.
This allows packagers to override `__DATE__` and `__TIME__` to make the build deterministic (build of same source will result in same binary), for more information please have look at:
https://reproducible-builds.org/

Buildsystem allow reproducible builds

---

CMakeLists.txt

This should help to keep the AppVeyor build logs readable

Added CMake option to disable all compiler warnings

---

source/main/terrain/OgreTerrainPSSMMaterialGenerator.cpp

this allows pssm to work on terrains with 6 materials. for backwards compatibility.
the problems stem with limiting the blend maps, this can cause some uneven material edges.
this needs to be discussed and balanced.

pssm material allowance

---

source/main/physics/RigSpawner.cpp

I encountered an issue with flexbodywheels - if the flexbody fails to spawn for any reason, the wheel will become dysfunctional - it won't not respond to traction or braking.
This bug was introduced with recent fixes of mesh/material management (https://github.com/RigsOfRods/rigs-of-rods/pull/1271)

FlexBodyWheel fix: flexbody fault should not break the wheel.

---

source/main/physics/flex/FlexObj.cpp
source/main/physics/flex/FlexObj.h

Crash occured when spawning an actor (=truck, load, boat, whatever) with exactly 1 "submesh" in truckfile.
Fixes
* #1256 - Crash on loading map "miniredmars" - a contained truckfile 'boobytrap.load' triggered it.
* #540 - Loading problems of Manitou_731.zip
Works OK for me, but @tritonas00 reports crash from 'bombinette.load' in "miniredmars" map.

Fixed crash when loading "miniredmars" map.

---

source/main/ForwardDeclarations.h
source/main/gameplay/RoRFrameListener.cpp
source/main/gameplay/RoRFrameListener.h
source/main/gfx/EnvironmentMap.cpp
source/main/gfx/EnvironmentMap.h
source/main/terrain/TerrainManager.cpp
source/main/terrain/TerrainManager.h

Fixes the old bug where reflections of first terrain used would remain in all other terrains until game restart.
Additionally, removes weird old code I found - when player doesn't drive a vehicle, RoR would render the envmap at middle of the map in 50m height.  After this change, the rendering will simply stop, so when you exit a vehicle, it will retain it's reflections.

Improved Envmap (realtime reflections)

---

source/main/resources/rig_def_fileformat/RigDef_Parser.cpp

This restores old behavior (version 0.4.0.7 and earlier).
Fixes #1260
Very minor change, just to close one issue ticket.

:bug: Truckfile/add_animation 'event' now case insensitive

---

source/main/physics/collision/Collisions.cpp
source/main/physics/collision/Collisions.h
source/main/terrain/TerrainManager.cpp
source/main/terrain/TerrainObjectManager.cpp

I think I nailed it. The messy code in 'Collisions.h/cpp' made it hard to see what's going on (I'm looking at you, estama!), but I figured it out. I quickly tested by driving Desperado buggy on Auriga - everything seemed to work just fine.
* The collision box limit is now 1 million
* The collision triangle limit is now 4 billion
* The memory is dynamically sized - you can forget the 'collision-tris' entry from .terrn2
* The `COLL: The hashtable is full` error is history.
Fixes #1395

Removed collision object count limits on maps

---

source/main/CMakeLists.txt
source/main/gui/panels/GUI_TeleportWindow.cpp
source/main/resources/otc_fileformat/OTCFileformat.cpp
source/main/resources/otc_fileformat/OTCFileformat.h
source/main/resources/terrn2_fileformat/Terrn2Fileformat.cpp
source/main/resources/terrn2_fileformat/Terrn2Fileformat.h
source/main/terrain/TerrainGeometryManager.cpp
source/main/terrain/TerrainGeometryManager.h
source/main/terrain/TerrainManager.cpp
source/main/terrain/TerrainObjectManager.cpp
source/main/terrain/TerrainObjectManager.h
source/main/utils/Utils.cpp
source/main/utils/Utils.h

New features:
This will enable porting the remaining 0.38 maps (such as ashes48's "around the mountain") that were blocked by lack of custom material support.
This is Auriga-0.4 map hacked to use it's heightmap for ground texture:
```
[General]
CustomMaterial=TEST_MAT_heightmap_for_texture
```
Until now, the minimap relied on "Survey map" feature which can be disabled in config, thus making Teleport minimap blank.
Again, Auriga-0.4 with it's heightmap used for Teleport minimap:
```
[Teleport]
NavigationMapImage=31-heightmap.png
```

Terrn2: 2 new options

---

source/main/terrain/TerrainGeometryManager.cpp

Apparently function `Ogre::TerrainMaterialGenerator::Profile::setLightmapEnabled()` is only present in v1.9
1.9 docs: https://www.ogre3d.org/docs/api/1.9/class_ogre_1_1_terrain_material_generator_1_1_profile.html
1.8 docs: https://www.ogre3d.org/docs/api/1.8/class_ogre_1_1_terrain_material_generator_1_1_profile.html

Build fix for OGRE 1.8

---

source/main/Application.cpp

If `RoR.cfg` does not contain the `EnvmapUpdateRate` line (the Configurator does not write this value, so RoR writes it once you exit) the default value would be set to 0, thus causing vehicles to not have any reflections:
This sets the default value to `2` (from here: https://github.com/RigsOfRods/rigs-of-rods/wiki/GVars:-global-(console)-variables)

Fixed `EnvmapUpdateRate` default value

---

source/main/physics/Beam.cpp

This makes the visual node debug readable on complex n/b's, using the same size values found in 0.36's source (https://github.com/only-a-ptr/ror-legacy-svn-trunk/blob/dcb83de66935cb6b82d153fea2838e166419a7ac/build/main/source/Beam.cpp#L9633)

Made node debug size smaller

---

source/main/Application.cpp
source/main/Application.h
source/main/gameplay/RoRFrameListener.cpp
source/main/gfx/camera/CameraManager.cpp
source/main/gfx/camera/CameraManager.h
source/main/gui/panels/GUI_GameSettings.cpp
source/main/utils/Settings.cpp

Added new GVar "gfx_enable_dof" and corresponding widget in GameSettings GUI window.
Also fixes #1355 - The DOF rendering listeners were attached to OGRE before RoRFrameListener was ready. Upon rendering the "loading..." window, the listeners attempted to access the non-existent RoRFrameListener (m_sim_controller) -> :boom:

DOF effect re-enabled + added to settings window.

---

source/main/resources/CacheSystem.cpp

PROBLEM: Our old GUI system (MyGUI) throws when a non-UTF8 string is supplied for display. OGRE's resource system apparently returns paths as narrow strings which are encoded in 8bit codepage under Windows.
NOTE: This is a very quick+dirty hotfix. UTF8 handling in RoR is a big mess :(
Fixes #1436

HOTFIX: Crash when resource ZIP name contains Unicode

---

source/main/GlobalEnvironment.h
source/main/gameplay/RoRFrameListener.cpp
source/main/gfx/EnvironmentMap.cpp
source/main/gfx/GfxActor.cpp
source/main/gfx/HydraxWater.cpp
source/main/gfx/SkyManager.cpp
source/main/gfx/SkyManager.h
source/main/main.cpp
source/main/resources/ContentManager.cpp
source/main/resources/ContentManager.h
source/main/scripting/GameScript.cpp
source/main/terrain/TerrainManager.cpp

It turned out there was a bug in loading resources based on configuration, so this crash could also happen if you toggled other effects. Kudos to @Speciesx for discovering and reporting.

BUGFIX: Crashes when changing sky type in Settings

---

source/main/gfx/HydraxWater.cpp
source/main/gfx/HydraxWater.h
source/main/gfx/IWater.h
source/main/gfx/Water.cpp
source/main/gfx/Water.h

Caused by generated textures not being properly unloaded.
Finally resolves a very old ticket by Max98: https://github.com/RigsOfRods/rigs-of-rods/issues/50

BUGFIX: Fixed HQ water glitch when re-entering simulation

---

source/main/physics/Beam.cpp

For some reason, skidmark-handler is never created for flexbodywheels. This causes crash when simulation logic attempts to update them.
I'm quickly patching it around by adding "was skidmark handler created?" check in simulation logic. Skidmarks are currently broken in several ways and fixing is in progress, see https://github.com/RigsOfRods/rigs-of-rods/pull/1404

HOTFIX: Crash with flexbodywheels and skidmarks enabled

---

source/main/gui/panels/GUI_GameConsole.cpp

The same as #1409, but now with backwards compatibility for console commands
---------------------
This command spawns an odef object at the player's position 
For instance, ```spawnobject opentruckshop``` spawns a opentruckshop at the player's position
This can be useful for quickly adding new objects and moving them with the [terrain editor](http://docs.rigsofrods.org/terrain-creation/editing-terrain-objects/)

Added console command spawnobject

---

source/main/gui/panels/GUI_GameConsole.cpp
source/main/physics/BeamForcesEuler.cpp
source/main/physics/flex/FlexAirfoil.cpp

RoR now prints both user-defined node number (unavailable for named nodes and generated nodes) and index in internal node-array. Related to #1467 
Also contains some unrelated bugfixes which just came to my attention.

Improved beam break/deform console logging

---

source/main/gameplay/AutoPilot.cpp
source/main/gameplay/AutoPilot.h
source/main/gui/OverlayWrapper.cpp
source/main/physics/Beam.cpp
source/main/terrain/TerrainObjectManager.cpp
source/main/terrain/TerrainObjectManager.h

This feature was broken for a very long time. If you enable the NAV mode in an airplane it will try to land on the closest airport equipped with locators (poles with red and white stripes).
See also http://docs.rigsofrods.org/gameplay/aircraft-handling/.

Fix NAV autopilot (Instrument Landing System)

---

source/main/utils/Settings.cpp

Try this earlier, before falling back to the generic App::sys_process_dir/..
I didn't test this, but the problem seems obvious on my Fedora 26 install:
App::sys_process_dir/.. will always exist (given that the binary is there), thus
the /usr/share/... path (where the resources are) will never be probed/ selected.

Try Linux specific /usr/share resources path earlier

---

README.md

@only-a-ptr The Gitter room should probably be deleted since none of the developers is using it

📚 Replaced Gitter badge with Discord

---

source/main/physics/BeamForcesEuler.cpp

When the beam deform/break debug logging was improved in #1470, apparently the `RoR::Log(msg.ToCStr());` line was missing which caused the deform debug to log nothing.

Fixed beam deform debug logging

---

source/main/Application.cpp

Added the missing `s` to the GVar name for backwards compatibility, see [this forum post](https://forum.rigsofrods.org/showrooms/184-1982-di-sportster-post1985.html#post1985).
Also now enabled by default as it improves the handling of every vehicle massively and makes the [now dead](https://github.com/RigsOfRods/rigs-of-rods/issues/1438) `SlopeBrake` truckfile section obsolete.

Fixed `HighResWheelNodeCollisions` setting name

---

source/main/gui/panels/GUI_SimUtils.cpp

Just a personal touch, so someone can know what gear they are in when they are using the in-cab camera, which disables the gear/speed/RPM HUD.

Made a current gear entry in the truck information panel.

---

source/main/gameplay/Character.cpp

I simply forgot to increment the counter :blush:
Fixes #1527

Hotfix: Multiplayer crash when 2nd client joins

---

source/configurator/CMakeLists.txt

Built deps and ror with and without boost and boost-libs, tested on Arch.

removed leftover boost from configurator (Linux)

---

source/main/physics/RigSpawner.cpp

Fixes the following issue:
> Load gavril omega or skyvan and press Backspace to reset -> segfault. Happens in master also.
https://pastebin.com/DBQqDhzj
https://www.dropbox.com/s/poo57yd8b8e5w1s/gavrilomega.zip?dl=1
Did we remove the custom zero allocator?

Fix segfault on truck respawn

---

source/main/physics/RigSpawner.cpp

Hotfix: segfault when custom particle init fails

---

source/main/gameplay/RoRFrameListener.cpp

Pressing 'COMMON_ENTER_NEXT_TRUCK' (default: CTRL+]) segfaults if you press it before spawning any trucks.

Fixed segfault in 'SetPlayerActor'

---

source/main/physics/Beam.h

This fixes the orbit camera angle on trucks with `ar_camera_node_pos[0] == 0`.

Fixed 'IsNodeValid()' helper function

---

source/configurator/CMakeLists.txt
source/main/CMakeLists.txt
source/main/gameplay/BeamEngine.cpp
source/main/gameplay/Landusemap.cpp
source/main/gameplay/Landusemap.h
source/main/gfx/Skidmark.cpp
source/main/gfx/hydrax/GodRaysManager.cpp
source/main/gfx/skyx/VClouds/Lightning.cpp
source/main/gui/panels/GUI_GameConsole.cpp
source/main/physics/Beam.cpp
source/main/physics/RigSpawner.cpp
source/main/scripting/CBytecodeStream.cpp
source/main/scripting/ScriptEngine.cpp
source/main/terrain/TerrainObjectManager.cpp
source/main/utils/CollisionTools.cpp
source/main/utils/InputEngine.cpp
source/main/utils/InputEngine.h
source/main/utils/PlatformUtils.cpp
source/main/utils/SHA1.cpp

[WIP] Highlights:
- Made the CMakeLists.txt disable resource files '.rc'  when building with clang-cl.exe (Windows) since they are not supported, and small code changes to avoid compile-time errors: https://github.com/RigsOfRods/rigs-of-rods/commit/8a45d34a177cd472750fa4ed41edcb6292a95083
- Removed, commented or moved some variables to either optimize the code a bit or remove unused variables: https://github.com/RigsOfRods/rigs-of-rods/commit/8c2caa35a478bf9f54cc2961544815fd3545085f https://github.com/RigsOfRods/rigs-of-rods/commit/d9484519ca73d75c996b641b544ae0a042b54c43

Variable cleanup and optimization and clang-cl related fixes

---

source/main/datatypes/node_t.h
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamFactory.cpp
source/main/physics/BeamForcesEuler.cpp
source/main/physics/RigSpawner.cpp
source/main/physics/RigSpawner.h

* New prediction method - OLD: "current aabb padded by node 0 velocity", NEW: "for each node, account current + future position (add velocity)".
* Removed duplicate code in ActorSpawner, Created new unified Actor method.
* Clarified 'bounding box ID' node attribute, added INVALID_BBOX constant.
* Improved spawning partial collision boxes - instead of clearing the std::vector and re-inserting AABBs every step, only insert on spawn and then reset+rebuild in-place.

Improved collision bounding boxes

---

source/main/gameplay/BeamEngine.cpp

Reverts: https://github.com/RigsOfRods/rigs-of-rods/commit/027d9044f4075439bb0662272ea3182c3456b698
Thanks for reporting this bug @Blue_Pads

Fixed broken auto-clutch logic

---

source/main/gfx/GfxActor.cpp
source/main/physics/RigSpawner.cpp

I'm unable to find a better solution. But this seems to work fine.
Truck file: http://archives.rigsofrods.net/repo/files/repofiles-1st-batch/58dcfc39b7024d3eacb3d70d8dca3bc9709ed7ae_UnimogU5000Dakar.zip
Underlying issue:
```
error loading mesh: dashboard1.mesh: OGRE EXCEPTION(2:InvalidParametersException):
Couldn't read 16 bit header value from input stream.
```

Fixed 'Unimog U5000 Dakar' segfaults

---

source/main/gfx/DustManager.cpp
source/main/terrain/map/SurveyMapEntity.cpp
source/main/terrain/map/SurveyMapEntity.h
source/main/terrain/map/SurveyMapManager.cpp
source/main/terrain/map/SurveyMapManager.h
source/main/terrain/map/SurveyMapTextureCreator.cpp
source/main/terrain/map/SurveyMapTextureCreator.h

Reason for the bug: `mMapTextureCreator->update()` was called too early.
- Removed obsolete methods
- Removed `mMapTextureNeedsUpdate` logic

Fixed survey / teleport map

---

source/main/gameplay/RoRFrameListener.cpp
source/main/gameplay/RoRFrameListener.h
source/main/gui/panels/GUI_MainSelector.cpp
source/main/gui/panels/GUI_MainSelector.h
source/main/gui/panels/GUI_TopMenubar.cpp
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamData.h
source/main/physics/BeamFactory.cpp
source/main/physics/BeamFactory.h
source/main/physics/BeamForcesEuler.cpp
source/main/physics/RigSpawner.cpp
source/main/physics/RigSpawner_ProcessControl.cpp
source/main/scripting/GameScript.cpp
source/main/scripting/ScriptEngine.cpp
source/main/terrain/TerrainObjectManager.cpp
source/main/utils/profiler/RigLoadingProfilerControl.h

Our spawning logic is very convoluted, there are lots of special cases and redundant reset requests that likely cancel each other out. My plan:
* Add queues for actor changes {spawn/modify/remove}
* Add 'pending player vehicle change' mechanism
* Process the queues + pending changes in one place -> less callbacks and ad-hoc state updates.
* Create unified 'spawn request' ticket which keeps all input data.
Known bugs:
* Terrain-preloaded actors are visible in top menubar. EDIT: this is upstream glitch, actually
* Not very thoroughly tested - expect glitches

Unified actor-spawn/change API (using queues)

---

source/main/gameplay/RoRFrameListener.cpp
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamFactory.cpp
source/main/physics/BeamForcesEuler.cpp

- Fixes position/rotation creep during interactive truck reset
- You no longer get stuck in the permanent interactive truck reset mode unintended

Interactive truck reset fix

---

source/main/gameplay/RoRFrameListener.cpp
source/main/gfx/GfxActor.cpp
source/main/physics/Beam.cpp

Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/1615

Fixed skeleton view

---

source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/RigSpawner.cpp

Instead of trying to find an appropriate dir node each time getDirection() is called we now precalculate it, together with a quaternion that fixes the axis alignment.
This greatly improves the interactive truck reset feature and the camera alignment on loads without a cinecam.

Much improved automatic camera reference generation

---

source/main/physics/collision/PointColDetector.cpp

This allows you to freely position your truck without having to worry about touching other vehicles

Disabled submesh collisions during truck reset

---

source/main/gameplay/BeamEngine.cpp
source/main/gameplay/BeamEngine.h
source/main/physics/RigSpawner.cpp

Fixes trucks like the `international-4400-single-axle-rollback.truck` which define a stall rpm higher than the idle rpm.

Improved 'Stall RPM' option parsing

---

source/main/datatypes/node_t.h
source/main/gfx/GfxActor.cpp
source/main/physics/Beam.cpp
source/main/physics/BeamForcesEuler.cpp
source/main/physics/collision/Collisions.cpp
source/main/physics/collision/Collisions.h
source/main/physics/collision/DynamicCollisions.cpp

Both `nd_last_collision_gm` and `nd_last_collision_slip` are currently used exclusively for GFX effects due to ground collisions.

Simplified collision state update logic

---

source/main/physics/collision/Collisions.cpp

This prevents vehicles from exploding when they impact surfaces with a high hydrodynamic friction coefficient.
A friction coefficient of 5 is still more than enough for all everyday situations.

Limits the hydrodynamic friction force

---

source/main/terrain/TerrainManager.cpp
source/main/terrain/TerrainManager.h

Both the collision and the script subsystem need to be initialized after the terrain geometry is loaded.
This fixes the segfault on the CPU Benchmark terrain.

Fixed the terrain initialization order

---

source/main/Application.cpp
source/main/Application.h
source/main/gfx/GfxActor.cpp
source/main/gui/panels/GUI_GameSettings.cpp
source/main/physics/BeamFactory.cpp
source/main/physics/BeamFactory.h
source/main/utils/Settings.cpp

The physics worker thread is now handled by the thread pool:
- Gets rid of the dummy thread pool which was used as a background worker thread
- Makes the `DisableThreadPool` setting obsolete
- Renamed `NumThreadsInThreadPool` into `NumWorkerThreads`
- Introduces `GVarPod_APS<int> app_num_workers`
- Converts `GVarPod_A<bool> app_multithread` into `GVarPod_APS<bool> app_async_physics`
Reference: https://github.com/only-a-ptr/rigs-of-rods/pull/22

Simplified threading logic

---

source/main/physics/collision/Collisions.cpp
source/main/physics/collision/Collisions.h

Performance was literally lying on the ground waiting to be picked up. :man_facepalming:
This simply hides the costly matrix multiplication behind a bounding box check.
| ------------- | ------------- |
| ![before](https://user-images.githubusercontent.com/9437207/46875539-35c0fd80-ce3c-11e8-9cba-ed062a33ee23.jpg) | ![after](https://user-images.githubusercontent.com/9437207/46875542-36f22a80-ce3c-11e8-8210-65688fdfb13e.jpg) |

Much improved mesh collision performance

---

source/main/physics/collision/Collisions.cpp

The debug visualization should only be visible if the cell_id matches.

Fixed collision debug visualization

---

source/main/physics/collision/Collisions.cpp
source/main/physics/collision/Collisions.h

Decent performance gain by skipping entire cells based on the maximum height of their collision tris/boxes.

Improved mesh collision lookup performance

---

source/main/physics/collision/Collisions.cpp
source/main/physics/collision/Collisions.h

Shamelessly based on the idea of @only-a-ptr:
> Exactly. We need to use something like std::unordered_set<collision_box_t*> m_occupied_collision_boxes
Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/1627

Fixed FPS drop on train spawners

---

source/main/physics/BeamForcesEuler.cpp

Prevents the Gavril Omega Six from sliding on ground on the simple2 spawn.
Reference: https://github.com/RigsOfRods/rigs-of-rods/commit/d11a88142f737528638bd357c38d717c85cebba6#diff-4003254e55aec2c60d21228f375f2a2dL1153
Please don't ask me what this actually does.

Brought seemingly necessary hack back

---

source/main/gameplay/LandVehicleSimulation.cpp

This bug made it hard to enable the RPM hold mode of the cruise control feature.

Fixed bug in the RPM hold feature

---

source/main/physics/BeamFactory.cpp

The sleep counter should be reset if the average movement velocity reaches the threshold.

Fixed a minor issue in the sleeping logic

---

source/main/gameplay/RoRFrameListener.cpp
source/main/gameplay/RoRFrameListener.h
source/main/gfx/camera/CameraManager.cpp
source/main/gui/OverlayWrapper.cpp

It's now working somewhat like you would expect and fixes the dashboard visibility logic,
which broke here: https://github.com/RigsOfRods/rigs-of-rods/commit/1b50c147a73be01c316d7df237f567207789d77e#diff-8a886433b2467e133b491db2b4ec51ffL1761

Improved the hide gui logic

---

source/main/gameplay/BeamEngine.cpp
source/main/physics/BeamForcesEuler.cpp

The bug was hidden by the previous idle mixture logic (https://github.com/RigsOfRods/rigs-of-rods/commit/912be9ec1ecce946707db36232b944cad6408831)
This indirectly fixes the idle mixture calculation, which results in a correct idle rpm, which fixes the broken engine triggers. It also makes the rpm hold feature behave better.
In addition it prevents bad interaction between manual inputs and engine trigger inputs.

Fixed nasty bug in the idle mixture calculation

---

source/main/gameplay/LandVehicleSimulation.cpp

`brake` and `accl` have a reverse meaning in reverse gear if arcade controls are enabled.

Fixed arcade control braking in reverse gear

---

resources/skeleton/config/input.map
source/main/datatypes/node_t.h
source/main/datatypes/wheel_t.h
source/main/gameplay/RoRFrameListener.cpp
source/main/gfx/GfxActor.cpp
source/main/gfx/GfxActor.h
source/main/gui/panels/GUI_TopMenubar.cpp
source/main/physics/Beam.cpp
source/main/physics/BeamForcesEuler.cpp
source/main/physics/collision/Collisions.cpp
source/main/utils/InputEngine.cpp
source/main/utils/InputEngine.h

Adds a wheel debug view mode:
- Reference arm system (including reaction forces)
- Wheel speed
- Torque
- Slip
Adds keyboard shortcuts:
- `COMMON_TOGGLE_DEBUG_VIEW` -> On/Off toggle for the current debug view
- `COMMON_CYCLE_DEBUG_VIEWS` -> Cycles through the different debug view modes
Removes keyboard shortcut:
- `COMMON_SHOW_SKELETON` -> On/Off toggle for the skeleton debug view

✨ Added wheel debug info mode

---

source/main/physics/BeamForcesEuler.cpp
source/main/physics/RigSpawner.cpp

- Fixes the `proped_wheel_pair` logic from the old parser
- Fixes code reshape mishap from: https://github.com/RigsOfRods/rigs-of-rods/commit/8b65c1fdb9d3ac85d133f928057a9311bc817b05#diff-11319c6cae8caeca2be4dde205bd243bR527

Fixed legacy differential code

---

source/main/datatypes/wheel_t.h
source/main/physics/Beam.h
source/main/physics/BeamForcesEuler.cpp
source/main/physics/Differentials.cpp
source/main/physics/Differentials.h
source/main/physics/RigSpawner.cpp

This unifies the old-style and new-style drivetrain code.
- Viscous mode is used by default when no axles section is present
- Axles are now built in the RigSpawner if no axles section is present
- Engine torque is still doubled when an axles section is present
- Wheel and axles code is now cleanly separated

Unified existing drivetrain code

---

source/main/gameplay/RoRFrameListener.cpp

Only update the camera data in the SoundScriptManager if the camera actually received an update.

Minor cleanup in 'UpdateSimulation'

---

source/main/physics/BeamForcesEuler.cpp
source/main/physics/RigSpawner.cpp
source/main/physics/air/TurboProp.cpp
source/main/physics/collision/Collisions.cpp
source/main/physics/collision/Collisions.h
source/main/physics/collision/DynamicCollisions.cpp

This redesign aims to provide realistic submesh collisions. Realistic with respect to:
- Conservation of momentum
- Conservation of energy
- Friction
The previous collision model had serious design errors:
- The mass of the cab nodes was assumed to be always equal to the mass of the contacter. :man_facepalming:
- The order of execution was wrong. Collisions need to be resolved after 'CalcBeams' and before 'CalcNodes' or else friction won't work correctly.
:man_facepalming:
- The implementation of the cab options `p` and `u` was an expression of the purest stupidity.
:man_facepalming:
```
p: [ Version 0.36a+ ] Makes the force required to pierce the submesh ten times bigger.
u: [ Version 0.36a+ ] Makes it impossible to pierce the submesh.
```
This gets us rid of all the magic numbers in the …

Submesh collision redesign

---

source/main/physics/Beam.h
source/main/physics/BeamFactory.cpp
source/main/physics/BeamFactory.h
source/main/physics/BeamForcesEuler.cpp

- Moves `ForwardCommand` out of the tight physics loop into the `ActorManager`, where it really belongs.
- Fixes a logical mistake in the brake/light forward mechanism that caused it to run more often than needed.
- Introduces a smart range limitation for the command forwarding mechanism.

Smart range limitation of ForwardCommands

---

source/main/physics/BeamFactory.cpp
source/main/physics/BeamForcesEuler.cpp

This workaround is required because we had to change the execution order of 'calcNodes' and 'calcBeams' in https://github.com/RigsOfRods/rigs-of-rods/pull/1661/commits/212a0a97a6b7735ad0a7a4037c44fc195d820dff
Test procedure: Stack two 20ft Containers on top of each other and watch the beam debug view.

Fixed the auto locking mechanism

---

source/main/gameplay/BeamEngine.cpp

This should allow to build much stronger clutches without the risk of destroying the vehicle during acceleration. It also improves the clutch behavior in manual transmission mode.

Attempt to improve the clutch force logic

---

source/main/physics/RigSpawner_ProcessControl.cpp

This breaks the M-26 Pershing, but I think we can live with that.

Fixed the 'set_collision_range' directive

---

source/main/gameplay/RoRFrameListener.cpp
source/main/gameplay/RoRFrameListener.h

This will repurpose the replay hotkeys to pause / resume the physics simulation and advance the physics simulation time on a frame by frame basis.

✨ Added a proper way to pause the physics simulation

---

source/main/physics/Beam.cpp
source/main/physics/Differentials.h
source/main/physics/RigSpawner.cpp
source/main/resources/rig_def_fileformat/RigDef_File.h
source/main/resources/rig_def_fileformat/RigDef_Parser.cpp
source/main/resources/rig_def_fileformat/RigDef_Serializer.cpp

- Allows for multiple alternate ratios
- Allows to disable 2WD mode entirely
Example section:
```
transfercase
;default driven axle, alternate axle, has 2wd mode, has 2wd lo mode, alternate ratio(s)
2, 1, 1, 0, 4.11, 3.1, 2.72
```

Expanded the transfercase section

---

source/main/gfx/Water.cpp
source/main/terrain/map/SurveyMapTextureCreator.cpp
source/main/terrain/map/SurveyMapTextureCreator.h

Fixes:
- View obstruction by fog
- Water flickering when the map is opened
- Ugly water rendering when using the speed optimized water rendering option

Fixed overview map glitches

---

source/main/gameplay/BeamEngine.cpp
source/main/gameplay/BeamEngine.h
source/main/gameplay/LandVehicleSimulation.cpp
source/main/gui/panels/GUI_SimUtils.cpp
source/main/physics/RigSpawner.cpp
source/main/resources/rig_def_fileformat/RigDef_File.cpp
source/main/resources/rig_def_fileformat/RigDef_File.h
source/main/resources/rig_def_fileformat/RigDef_Parser.cpp
source/main/resources/rig_def_fileformat/RigDef_Serializer.cpp

- Introduces a new `braking torque` parameter to the `engoption` section.
- Fixes the lack of "engine braking" in low rpm scenarios when the ignition is on.
- Greatly reduces the impact of the braking logic on the torque curve.
- Improves the torque / power output info in the SimUtils overlay.

Revamped engine braking logic

---

source/main/resources/rig_def_fileformat/RigDef_File.cpp

The default values should be handled by the BeamEngine and not by the parser.

Avoid defining engoption defaults in two places

---

source/main/physics/SlideNode.cpp

Using 'fast_normalise' for those computations was a pretty bad idea in the first place.

Fixed the SlideNode math

---

source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamFactory.cpp
source/main/physics/BeamForcesEuler.cpp

The slide-node forces need to be updated after the intra-truck collisions are handled and before the inter-truck collisions are handled.

Fixed submesh-collision behavior of slidenodes

---

source/main/physics/Beam.cpp
source/main/physics/BeamForcesEuler.cpp

This extra step is required because we once again had to reorder the function calls in `CalcForcesEulerCompute` in order to fix the slide-node collisions.

Fixed the mesh contact logic

---

source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamData.h
source/main/physics/BeamForcesEuler.cpp
source/main/physics/RigSpawner.cpp

Triggers no longer share their `bounded` type with shocks2.
For reference: https://github.com/only-a-ptr/ror-legacy-svn-trunk/commit/74e77fa3017e7e9d464658d1bf2952647e1ad9a6

Separation of the trigger code from CalcShocks2

---

source/main/physics/collision/Collisions.cpp

Inspired by the code we were previously using: https://github.com/RigsOfRods/rigs-of-rods/blob/cd0e9ebc574f975301552919d125800871e1a1bd/source/main/physics/collision/DynamicCollisions.cpp#L114
I don't like it, but it works exceptionally well, with minimal effort.

Poor man's solution for the submesh overpenetration issue

---

source/main/gfx/GfxActor.cpp
source/main/physics/Beam.cpp
source/main/physics/BeamForcesEuler.cpp

- Fixed the shock velocity calculation
- Fixed the damping unit (needs to be N/(m/s))
- Added boundary limits similar to 'shocks1'
- Clamped the shock velocity to 0.1 m/s - 20 m/s.
- Simplified the extension / compression detection
- Improved the shocks debug view output

Improved the shocks3 logic

---

source/main/main.cpp

Fixes the logic which controls the effects of the 'Network enable' and 'Preselected Map' settings.
The terrain selector window should only be shown if the server does not enforce a terrain and we do not have a pre-selected terrain.

Fixed multiplayer selector window logic

---

source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamFactory.cpp

The actor stream setup was never executed due to a flaw in the `ar_uses_networking` logic.

Fixed broken actor stream setup

---

source/main/gfx/DustManager.cpp
source/main/gfx/GfxActor.cpp
source/main/gfx/GfxActor.h
source/main/physics/RigSpawner.cpp
source/main/physics/flex/FlexBody.h

This exploits the fact that not all flexbodies require the same amount of computation time.
The result is a decent FPS improvement (5-7%) on low core count (2-4) CPUs on trucks like the `Tatra-T813-Dakar`.

Optimized ComputeFlexbody execution order

---

source/main/terrain/map/SurveyMapTextureCreator.cpp

Far clip is zero when the sight range is unlimited.

Fixed the overview map projection axis

---

source/main/gameplay/RoRFrameListener.cpp
source/main/physics/Beam.cpp
source/main/physics/Beam.h

Pressing `SPACE` in the interactive-truck-reset mode will automatically align the truck with the nearest multiple of 45 degrees.

✨ Truck rotation with angle snapping

---

source/main/gfx/GfxActor.cpp
source/main/gfx/GfxActor.h

It broke during the recent changes to the brakeforce logic in: https://github.com/RigsOfRods/rigs-of-rods/pull/1749

Fixed the brake pedal animation

---

source/main/datatypes/wheel_t.h
source/main/physics/Beam.h
source/main/physics/BeamForcesEuler.cpp
source/main/physics/RigSpawner.cpp

What this does:
- It completely removes the backspin during braking
- It completely removes any creeping when parking on a slope
- It makes all the anti-jitter / anti-skidding magic obsolete
How it does that:
- It calculates the mass of the rotating parts of the wheel
- It records the external forces (`retorque`) that act on the wheel
- It calculates the force required to counteract those and the momentum
We can built upon the `retorque` concept in other parts of the code (limited slip differentials, true clutch slipping, ...).

✨ Godlike brakes

---

source/main/gfx/GfxActor.cpp

The segfault happens when you spawn the `767 AA Airliner`, go back to menu, then spawn the `767 AA Airliner` again.
```
Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
Ogre::Mesh::createSubMesh (this=0x0)
at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreMesh.cpp:92
92            mSubMeshList.push_back(sub);
#0  Ogre::Mesh::createSubMesh (this=0x0)
#1  0x000055555583880d in Airbrake::Airbrake (this=0x55555af25ac0)
#2  0x0000555555827e20 in ActorSpawner::ProcessAirbrake (...)
#3  0x0000555555836aeb in ActorSpawner::SpawnActor (this=this@entry=0x7fffffffd660)
```

Fixed AirBrake segfault

---

source/main/physics/RigSpawner.cpp

Fixes crash when trying to load the Hillclimber Buggy:
```
RuntimeAssertionException: resource name must not be empty in createResource
```
The problem seems to be that:
```
vcam.vcam_material->getTechnique(0)->getPass(0)->getTextureUnitState(0)->getTextureName()
```
returns an empty string.

Fixed the Hillclimber Buggy

---

source/main/network/Network.cpp

Coverity Scan reports:
```
overrun-buffer-arg: Overrunning buffer pointed to by bufferContent of 16384 bytes
by passing it to a function which accesses it at byte offset 16399
using argument len (which evaluates to 16384).
```

Fixed out of bounds access

---

source/main/datatypes/node_t.h
source/main/gameplay/RoRFrameListener.cpp
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamFactory.cpp
source/main/physics/RigSpawner.cpp

The initial node positions (`initial_pos`) are only used during truck reset and don't need to be part of the node struct.
The `wheelid` became obsolete during the drive train refactoring.
The `iswheel` documentation was incorrect.

'node_t' cleanup

---

source/main/gameplay/AircraftSimulation.cpp
source/main/gameplay/AircraftSimulation.h
source/main/gameplay/LandVehicleSimulation.cpp
source/main/gameplay/LandVehicleSimulation.h
source/main/gameplay/RoRFrameListener.cpp
source/main/physics/BeamFactory.cpp

This separates the driving aids logic (anti-rollback, cruise control, ...) from the input event handling and fixes the issue that the driving aids were only working on the player vehicle.

Fixed driving aids on non-player truck vehicles

---

source/main/utils/Utils.cpp
source/main/utils/Utils.h

Much faster than SHA1. Perfect fit for content hashing (detection of duplicates, ...).

✨ Introduced Ogre::FastHash wrappers

---

source/main/resources/CacheSystem.cpp

How to reproduce:
1. Rebuild the cache
2. Load [Aspen Grove](https://github.com/RigsOfRods/rigs-of-rods/files/2619701/AspenGrove.zip) without restarting the game
```
FATAL ERROR: An internal error occured in Rigs of Rods.
Technical details below: 
ItemIdentityException: ParticleSystem template with name 'tracks/TurbopropSmoke' already exists. in ParticleSystemManager::createTemplate at /home/archie/ror-dependencies/Source/ogre/OgreMain/src/OgreParticleSystemManager.cpp (line 199)
```
@only-a-ptr I don't know if this is the correct way of fixing it. I also experimented around with `destroyParticleSystem`, but that didn't work.

Fixed crash to desktop after regen

---

source/main/scripting/GameScript.cpp
source/main/scripting/OgreScriptBuilder.cpp
source/main/scripting/OgreScriptBuilder.h
source/main/scripting/ScriptEngine.cpp
source/main/scripting/ScriptEngine.h

The old caching code looked like this: https://github.com/RigsOfRods/rigs-of-rods/blame/40099732e94646c925cde042535abc326a8517eb/source/main/scripting/ScriptEngine.cpp#L900-L911, but I can't imagine that it ever worked the way it was implemented.

Removed logically dead code

---

source/main/datatypes/node_t.h
source/main/gameplay/SceneMouse.cpp
source/main/gfx/GfxActor.cpp
source/main/physics/Beam.cpp
source/main/physics/BeamForcesEuler.cpp
source/main/physics/RigSpawner.cpp
source/main/scripting/ScriptEngine.cpp

Positive side effect: The true wheel nodes indices made their way back into the node details debug overlay.
@only-a-ptr Do we really have to keep track of which nodes are auto-generated an which are not? I don't think so, but I might be wrong.

Removed unnecessary double id from the node struct

---

source/main/physics/BeamFactory.cpp

Performance degrades noticeably, beyond 8 threads, both on Ryzen and Skylake.

Limit the default thread pool size

---

source/main/terrain/TerrainGeometryManager.cpp
source/main/terrain/TerrainGeometryManager.h
source/main/terrain/TerrainManager.cpp
source/main/terrain/TerrainManager.h

@only-a-ptr, you're right. It was a bad idea to add code which might be useful in the future.
Reverts: https://github.com/RigsOfRods/rigs-of-rods/pull/1851

Removed 'GetMaxHeight' helper

---

source/main/terrain/TerrainGeometryManager.cpp
source/main/terrain/TerrainGeometryManager.h

We do not seem to support any alignments other than [`ALIGN_X_Z`](https://ogrecave.github.io/ogre/api/1.11/class_ogre_1_1_terrain.html#aca4fcebfb7ed4684682347d325477e91).

Removed terrain alignment logic

---

source/main/terrain/TerrainGeometryManager.cpp
source/main/terrain/TerrainGeometryManager.h

This results in a 20% faster terrain height lookup.
We do not need to clamp the values, because we quit early in those cases: https://github.com/ulteq/rigs-of-rods/blob/a4f1fc636aa3196b36aff539df22e3cb2a3d5e16/source/main/terrain/TerrainGeometryManager.cpp#L221

Optimized the terrain height lookup

---

source/main/Application.cpp
source/main/Application.h
source/main/gui/panels/GUI_GameSettings.cpp
source/main/resources/ContentManager.cpp
source/main/utils/Settings.cpp

- Lowered the default value from 8 to 4
Lower values (2 or 4) drastically improve the performance on certain maps when playing on an integrated GPU.

Made the 'Anisotropy' setting adjustable

---

source/main/Application.cpp
source/main/Application.h
source/main/gfx/OgreSubsystem.cpp
source/main/gui/panels/GUI_GameSettings.cpp
source/main/utils/Settings.cpp

Neither can we change the render system on the fly, nor can we force Ogre to write a different render system to the `ogre.cfg` on the fly. This seems to be the easiest workaround ...

Fixed the render system selection logic

---

source/main/resources/otc_fileformat/OTCFileformat.cpp

Fixes #1870 (Mountainside terrain crash on loading)

Hotfix: parsing whitespace-only lines in *page*.otc

---

source/main/gameplay/RoRFrameListener.cpp
source/main/gameplay/RoRFrameListener.h

Probably just a leftover from using an `Ogre::Timer` in the past.

Simplified the race time calculation

---

source/main/gui/panels/GUI_GameSettings.cpp

`app_rendersys_override` might be `NULL` as of: https://github.com/RigsOfRods/rigs-of-rods/pull/1904

Fixed the render setting selection logic

---

source/main/gameplay/RoRFrameListener.cpp
source/main/gui/OverlayWrapper.cpp
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/RigSpawner.cpp
source/main/physics/RigSpawner.h
source/main/scripting/ScriptEngine.cpp

Replaces the archaic collision avoidance logic which was built around fixed reference nodes (`ar_lowest_node`, `ar_lowest_contacting_node`) with some more robust code.

🔧 Simplified and improved the lowest node logic

---

resources/scripts/races.as
source/main/gameplay/RoRFrameListener.cpp
source/main/gameplay/ScriptEvents.h
source/main/physics/Beam.cpp
source/main/scripting/GameScript.cpp
source/main/scripting/GameScript.h
source/main/scripting/ScriptEngine.cpp

* Automatically stops the currently active race if you `reset`, `delete` or `teleport` the vehicle you started the race with.
* Automatically disables slow- / fast motion while any race is active.
* Fixes a bug in the race cancellation logic (which prevents you from restarting a race)

🔧 Proper race stoppage logic

---

source/main/gfx/OgreSubsystem.cpp
source/main/main.cpp
source/main/utils/PlatformUtils.cpp

* Automatically restores partially destructed user directories (it recreates the file structure)
* Replaces the dummy render system selection window with a proper error message
* Prevents `CreateDirectoryW` throwing asserts if the folder already exists
Related with: https://github.com/RigsOfRods/rigs-of-rods/pull/1937
Closes: https://github.com/RigsOfRods/rigs-of-rods/pull/1988
Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/1935
Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/1433

Automatic skeleton integrity verification on startup

---

source/main/terrain/TerrainGeometryManager.cpp

Improves the collision behavior on maps like Minima which have water outside of the actual terrain boundaries.

🎮 Use the 'WaterBottomLine' as collision boundary

---

tools/blender/ror_export.py
tools/blender/ror_import.py

Features:
- Full vertex group support
- Automatic column alignment
- Sophisticated vertex position rounding
- Full preservation of the original truck file
- Automatic beam sorting based on the vertex groups
- All node, beam and cab options are preserved during import / export
- All `set_node_defaults`, `set_beam_defaults` and `set_beam_defaults_scale` entries are preserved
Repository entry: https://www.rigsofrods.org/forum/resources/blender-import-export-plugin.25/

✨ Added blender 2.79 import/export plugins

---

source/main/terrain/TerrainGeometryManager.cpp
source/main/terrain/TerrainGeometryManager.h

This automatically optimizes the terrain height lookup on maps with a flat height map.
Examples: N-Labs, Minima, Penguinville, Community Map, ...

🔧 Auto-detect flat height maps

---

source/main/main.cpp
source/main/resources/ContentManager.cpp

Fixes: `Texture 'error.png' not found` in main menu
Fixes: `Texture 'user_go.png' not found` in main menu
Fixes: `Texture 'us.png' not found` in the multiplayer "lobby"
Closes: https://github.com/RigsOfRods/rigs-of-rods/pull/2009

🐛 Fixed various 'Texture ... not found' errors

---

source/main/physics/RigSpawner.cpp
source/main/physics/RigSpawner.h

Example spawner log output:
```
WARNING (Keyword rotators_2) Off-centered axis on base plate of rotator 1
WARNING (Keyword rotators_2) Off-centered axis on rotating plate of rotator 1
WARNING (Keyword rotators_2) Misaligned plates on rotator 1
```

🔧 Automatic rotators(2) structure verification

---

source/main/physics/Beam.cpp

Fixes an issue that caused trucks like the Bobcat S770 Skid Loader, which use the 'c' flag on node 0, to spawn mid air.

🐛 Fixed logical error in the 'Get...Height' helpers

---

source/main/resources/ContentManager.cpp

Reverts: https://github.com/RigsOfRods/rigs-of-rods/pull/2018, because it hinders common content creator workflow.

🔧 Less strict cache validation

---

source/main/Application.cpp
source/main/Application.h
source/main/gui/panels/GUI_GameSettings.cpp
source/main/resources/CacheSystem.cpp
source/main/utils/Settings.cpp

* Brings back the `-checkcache` command line argument
* Adds a new `Trigger cache update (and quit)` button to the (diag) settings
In an ideal world we would be able to update the cache without having to restart the game.

🎮 Reimplemented the cache regen logic

---

source/main/utils/Settings.cpp

`gvar.GetStored()` equals `gvar.GetActive()` if there is no stored value.

📐 Minor cleanup

---

source/main/gameplay/BeamEngine.cpp

This will prevent the automatic transmission from unnecessary gear shifts, when there are high lateral forces.

🎮 Automatic gear shifting now takes acceleration forces into account

---

source/main/physics/BeamForcesEuler.cpp

Affected trucks: `Ultra Bouncer`, `Grave Digger 16 Revamp v2 (crappy breakable)` and others.
Fixes: https://github.com/RigsOfRods/rigs-of-rods/pull/1121

🐛 Fixed the commands2 auto center logic

---

source/main/physics/RigSpawner.cpp

Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/1609

🐛 Fixed managed-materials not working on beams

---

source/main/gfx/Water.cpp

Reflection was disabled when under water - the underwater camera now sees the world with refraction.

🎮 Improved water reflections

---

source/main/gfx/camera/CameraManager.cpp
source/main/gfx/camera/CameraManager.h

* The terrain mesh is now taken into account when chosing a new position
* The zoom ratio (fov) is now adjustable via 'Right MB + Wheel Up/Down'
* Middle mouse click will reset any camera mode back to normal
* Made the camera persistent across vehicle changes

✨ Revamped the static camera

---

source/main/gfx/GfxActor.cpp
source/main/gui/panels/GUI_TopMenubar.cpp

Empty debug view layers are now:
* Hidden from the top menu
* Skipped by the debug view cycle (`CTRL+K`)

🔧 Hide/Skip empty debug view layers

---

source/main/datatypes/node_t.h
source/main/physics/RigSpawner.cpp
source/main/physics/collision/PointColDetector.cpp

Only 'upgrade' ground contactable nodes, which are either part of a collision triangle or part of the rim, to contacters.
This:
* Reduces the performance impact of the new logic
* Allows you to define nodes which can contact the ground, but not submesh

🔧 Contacter logic improvements

---

source/main/resources/CacheSystem.cpp

Fixes a 10 year old [typo](https://github.com/ulteq/ror-legacy-svn-trunk/blame/321a7a3c5dd53da89773bc3132298007903b6a2a/build/main/source/CacheSystem.cpp#L697) in the old 'duplicate' detection routine.
Example output:
```
* incremental check (5/5): duplicates ...
- duplicate: 8d25UID-smallisland.terrn2 <--> SmallIsland.terrn2
- /home/ulteq/.rigsofrods/packs/smallisland.zip
- /home/ulteq/.rigsofrods/packs/Smallisland.zip
```

✨ Much improved duplicate detection logic

---

source/main/gameplay/RoRFrameListener.cpp
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamData.h
source/main/physics/BeamFactory.cpp

This solves the issue by reusing the unique id, which is used to generade managed materials, when reloading a truck from disk.

🐛 Fixed material issues during truck reload (from disk)

---

source/main/gameplay/RoRFrameListener.cpp
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamData.h
source/main/physics/BeamFactory.cpp

This reverts commit 6ca096683d00456b6b5586da715139947f8b5dd4 (which was a really bad idea).
Related with: https://github.com/RigsOfRods/rigs-of-rods/issues/2067

Revert "🐛 Fixed material issues during truck reload (from disk)"

---

source/main/datatypes/wheel_t.h
source/main/gfx/GfxActor.cpp
source/main/physics/Beam.cpp
source/main/physics/BeamFactory.cpp
source/main/physics/RigSpawner.cpp
source/main/physics/RigSpawner.h
source/main/physics/collision/DynamicCollisions.cpp

Singleplayer:
- All wheel (tyre & rim) nodes now carry the `iswheel` flag
- All rim nodes now carry the `nd_rim_node` flag
Multiplayer:
- Rim nodes are now treated similar to tyre nodes
|:---------:| :------:|
| ![rim_before](https://user-images.githubusercontent.com/9437207/51110340-a7706500-17f8-11e9-8151-6f634f5ec90e.png) | ![rim_after](https://user-images.githubusercontent.com/9437207/51110343-a9d2bf00-17f8-11e9-9994-748f7fecfcfc.png) |

🐛 Fixed rim node synchronization in multiplayer

---

source/main/physics/BeamSlideNode.cpp

`ToggleSlideNodeLock` can also be called on non-player actors.

🐛 Fixed minor slidenodes bug

---

resources/skeleton/config/input.map
source/main/gameplay/RoRFrameListener.cpp
source/main/gameplay/RoRFrameListener.h
source/main/gfx/GfxActor.cpp
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamData.h
source/main/physics/BeamForcesEuler.cpp
source/main/physics/collision/Collisions.cpp
source/main/utils/InputEngine.cpp
source/main/utils/InputEngine.h

The new soft reset allows you to translate and rotate entire groups of actors without doing an actual reset.
The new pause mode allows you to 'freeze / unfreeze' the physics of individual actors and fits the new save games feature perfectly.
Shortcuts:
- `TRUCK_TOGGLE_PHYSICS` (Default: 'END')
- `COMMON_TOGGLE_RESET_MODE` (Default: 'EXPL+APOSTROPHE')

✨ Soft truck reset & per truck pause mode

---

resources/skeleton/config/input.map
source/main/gameplay/RoRFrameListener.cpp
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamFactory.cpp
source/main/physics/Savegame.cpp
source/main/utils/InputEngine.cpp
source/main/utils/InputEngine.h

You can now toggle the trailer parking brake independently from the towing truck.
- Default keyboard shortcut: `V`
This also works with no towing truck connected, if you enter the trailer.

🎮 New trailer parking brake logic

---

source/main/gui/panels/GUI_TextureToolWindow.cpp
source/main/gui/panels/GUI_TextureToolWindow.h
source/main/utils/Utils.cpp

- Fixes crash with textures of size 0
- Preselects the 'Dynamic Textures only' checkbock
- Preselects the 'MapRttTex' texture, if it exists
- Lists all textures when you open the window
- Sorts the textures by name

🐛 Fixed the texture tool

---

source/main/gameplay/RoRFrameListener.cpp

Partial terrain / vehicle names are now enough to define a preselected terrain / vehicle.
`./RoR -map f1 -truck gts` will spawn a `ViperGTS.car` on `2af11UID-f1_testtrack.terrn2`.

🎮 Improved preset text matching

---

source/main/gfx/DustManager.cpp
source/main/physics/BeamFactory.cpp

Fixes a small issue with: https://github.com/RigsOfRods/rigs-of-rods/pull/2115 (skidmarks were rendered during truck reset)

🔧 Fixed particle issue during truck reset

---

source/main/gameplay/RoRFrameListener.cpp
source/main/gameplay/RoRFrameListener.h
source/main/gui/panels/GUI_LoadingWindow.cpp
source/main/gui/panels/GUI_LoadingWindow.h
source/main/terrain/TerrainGeometryManager.cpp

Also removes the limit of having at most 5 loading window updates per second.

📐 Loading window cleanup

---

source/main/resources/ContentManager.cpp

We still look for content in `/packs`, `/vehicles` and `/terrains`, but we no longer create those folders automatically during installation.

🔧 Backwards compatibility

---

source/main/gameplay/RoRFrameListener.cpp

Example:
* `./RoR -map f1 -truck gts` spawns a `ViperGTS.car` with `1996_Wheels`

🎮 Automatically chose valid a section config

---

source/main/gameplay/Character.cpp

| ------------- | ------------- |
| ![temp](https://user-images.githubusercontent.com/9437207/51805121-e5926d80-2269-11e9-8f02-167297582f79.png) | ![temp](https://user-images.githubusercontent.com/9437207/51805131-0ce93a80-226a-11e9-85e5-7ad29ebeda5c.png) |
But don't ask me why this is fixing it ...

🐛 Fixed broken transmission labels in multiplayer

---

source/main/terrain/TerrainManager.cpp

Terrain actors used to be spawned while the loading bar was still showing:
```
Initializing Overview Map Subsystem
```

🔧 Better terrain init logging

---

source/main/physics/BeamFactory.cpp
source/main/resources/CacheSystem.cpp

It used to be `entry.fname == filename || entry.fname_without_uid == filename`, and we also do it like this here: https://github.com/RigsOfRods/rigs-of-rods/blob/54e81c4316dfbd821d94f1ccfbc65fbb37066d20/source/main/resources/CacheSystem.cpp#L1064

🔧 Fixed some minor truck filename issues

---

tools/blender/ror_export.py
tools/blender/ror_import.py

- Fixes the `set_beam_defaults` formatting during export (after edge deletion)
- Removes duplicate `;grp:` lines after the node / beam sections

🔧 Minor python plugin improvements

---

source/main/resources/rig_def_fileformat/RigDef_Parser.cpp
source/main/resources/rig_def_fileformat/RigDef_Parser.h

The old parser did exit the current section on the following keywords:
* author
* description
* fileformatversion
* fileinfo
* minimass

🐛 Fixed 'Globals' section parsing logic

---

source/main/gameplay/Character.cpp

The player entity should be invisible when the environment texture is rendered.
Fixes: #1985

🐛 Fixed player model reflection issue

---

source/main/gameplay/RoRFrameListener.cpp

`./rorserver -terrain f1_testtrack` is now enough to set `2af11UID-f1_testtrack.terrn2`.

🔧 Server terrain name completion

---

source/main/gameplay/Character.cpp
source/main/network/Network.cpp
source/main/network/Network.h
source/main/network/RoRnet.h
source/main/physics/Beam.cpp

Not all `MSG2_STREAM_DATA` packets are allowed to be discarded.
This was the root of the first segfault in: https://github.com/RigsOfRods/rigs-of-rods/issues/2178
Requires: https://github.com/RigsOfRods/ror-server/pull/72

🐛 Fixed major flaw in the packet discard logic

---

source/main/MainMenu.cpp
source/main/gameplay/RoRFrameListener.cpp
source/main/gui/panels/GUI_MainSelector.cpp
source/main/resources/CacheSystem.cpp
source/main/resources/CacheSystem.h

* 'snow.terrn2' would have been looked up as '31-snow.terrn2' even though both exist.
* `FindEntryByFilename` must not be case sensitive for backwards compatibility.

🐛 Fixed bug in the cache entry lookup

---

source/main/resources/CacheSystem.cpp
source/main/resources/ContentManager.cpp

* Prevents duplicate cache entries when having zip archives in subdirectories
* Fixes support for content in subdirectories of zip archives
Closes: https://github.com/RigsOfRods/rigs-of-rods/pull/2225

🐛 Fixed bad resource handling of subdirectories

---

source/main/gameplay/RoRFrameListener.cpp
source/main/gameplay/RoRFrameListener.h
source/main/gui/panels/GUI_MainSelector.cpp
source/main/gui/panels/GUI_MainSelector.h
source/main/network/RoRnet.h
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamData.h
source/main/physics/BeamFactory.cpp
source/main/physics/Savegame.cpp
source/main/utils/Settings.cpp

* Renames actor config into section config (everywhere)
* Actor can have any amount of sections, but only one can be selected
* Requires slight changes to the savegame file format and the net protocol
We were sending 8000 bytes of data during actor stream setup for sth. that takes 64 bytes at most. The longest section name in my cache is 31 characters long.

📐 Section config cleanup

---

source/main/gui/panels/GUI_TopMenubar.cpp

Relevant when having to deal with a long actor list on a small screen.

🔧 Allow scrollbar in top menu

---

tools/blender/ror_export.py

- Exporting no longer modifies the current object mode
- New edges now inherit existing set_beam_defaults (fixes the empty line issue)

🔧 Blender (export) plugin improvement

---

source/main/gameplay/RoRFrameListener.cpp

- Auto exits the terrain editor when you enter a vehicle

🔧 Fixed the terrain editor enter/exit logic

---

source/main/gameplay/RoRFrameListener.cpp
source/main/gameplay/RoRFrameListener.h
source/main/network/Network.cpp

- Update the player list each frame (smoother frametimes)
- Keep the simulation running when the selector window is open (prevents network desync)

🔧 Network fixes

---

source/main/physics/BeamFactory.cpp

The registration result was associated with the wrong actor. The stream id is not unique.

🐛 Fixed the stream register result registration

---

source/main/utils/SHA1.cpp
source/main/utils/SHA1.h
source/main/utils/Utils.cpp

Detected by Visual Studio 2017. The output buffer was 1 NULL-character too short.

Fix stack buffer overrun in SHA1 hashing.

---

source/main/gameplay/RoRFrameListener.cpp
source/main/physics/Beam.cpp
source/main/physics/BeamFactory.cpp
source/main/physics/BeamFactory.h

The network buffer length calculation failed when some clients needed much longer than others to spawn a new actor.

🐛 Fixed the vehicle implosion in multiplayer

---

source/main/gameplay/RoRFrameListener.cpp

The `H` position output is now using the same formatting as the terrain editor.

🔧 Position output format upgrade

---

source/main/gui/panels/GUI_TopMenubar.cpp
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamFactory.cpp
source/main/physics/BeamFactory.h
source/main/utils/Utils.h

We can just delete remote trucks the moment we detect that they're no compatible with what we have installed locally.
| Missing content | Content mismatch |
| :-: | :-: |
| ![temp2](https://user-images.githubusercontent.com/9437207/52974353-81bf1880-33c1-11e9-82a4-fa485bc4f754.png) | ![temp1](https://user-images.githubusercontent.com/9437207/52974352-81bf1880-33c1-11e9-8bd7-f4690441f5c5.png) |

🔧 Simplified invalid actor logic and revamped actor spawn info

---

source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamConstants.h
source/main/physics/RigSpawner.cpp
source/main/physics/RigSpawner_ProcessControl.cpp
source/main/resources/rig_def_fileformat/RigDef_File.cpp
source/main/resources/rig_def_fileformat/RigDef_File.h
source/main/resources/rig_def_fileformat/RigDef_Node.h
source/main/resources/rig_def_fileformat/RigDef_Parser.cpp
source/main/resources/rig_def_fileformat/RigDef_Parser.h
source/main/resources/rig_def_fileformat/RigDef_Prerequisites.h
source/main/resources/rig_def_fileformat/RigDef_Serializer.cpp

Test load: 
[MultiMiniMass_Test_Load.zip](https://github.com/RigsOfRods/rigs-of-rods/files/2875354/MultiMiniMass_Test_Load.zip)
Section minimass got options:
```
; option n = filler, does nothing
minimass
10.0, n
; option d = sets new default value, like `set_node_defaults`
minimass
4.0, d
```

Truckfile now supports multiple `minimass` sections.

---

source/main/gfx/GfxActor.cpp

Minor glitch in code, discovered by Debug mode in Visual Studio.
~I need a vehicle to test texture blending w/water.~
Update: tested with http://www.austingratzer.com/rigs/downloads.php?do=file&id=146, working

🐛 Fixed array index issue in GfxActor

---

source/main/physics/Beam.cpp
source/main/resources/rig_def_fileformat/RigDef_File.cpp
source/main/resources/rig_def_fileformat/RigDef_File.h
source/main/resources/rig_def_fileformat/RigDef_Parser.cpp
source/main/resources/rig_def_fileformat/RigDef_Parser.h
source/main/resources/rig_def_fileformat/RigDef_Regexes.h

* Added directive `set_default_minimass 1.23` which replaces `minimass` with `d` flag. The directive can be used in-between defining nodes, like `set_node_defaults`.
* Added `minimass` option `l` which will disable the minimass check for all nodes with 'l' (load weight) option. Suggested by @DODgecharger: https://github.com/RigsOfRods/rigs-of-rods/issues/2255#issue-410565608; https://github.com/RigsOfRods/rigs-of-rods/pull/2276#issuecomment-465442036 (at bottom)
[SetDefaultMinimass_TestLoad.zip](https://github.com/RigsOfRods/rigs-of-rods/files/2885636/SetDefaultMinimass_TestLoad.zip)

Truckfile: improved minimass handling

---

source/main/gui/panels/GUI_GameConsole.cpp
source/main/terrain/TerrainManager.h

`setwaterlevel default` allows you to reset the water level back to the default height.

🔧 Improved 'setwaterlevel' console command

---

source/main/CMakeLists.txt
source/main/gui/GUIInputManager.cpp
source/main/gui/GUIManager.cpp
source/main/gui/GUIManager.h
source/main/gui/panels/GUI_NodeBeamUtils.cpp
source/main/gui/panels/GUI_NodeBeamUtils.h
source/main/gui/panels/GUI_TopMenubar.cpp
source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamFactory.cpp

The code is relatively ugly, but the feature is so amazing that we should have it in 0.4.8.
Features:
- Live editing of actor mass, and beams / shocks / wheels springiness and damping.
- Automated search for optimal springiness and damping values.

✨ Node / Beam tuning utility

---

source/main/gui/GUIInputManager.cpp

Needed because `IsVisible_TopMenubar()` can return `true` in main menu.
Fixes: https://github.com/RigsOfRods/rigs-of-rods/pull/2296

🐛 Fixed glitch in the input grabbing logic

---

source/main/gfx/GfxActor.cpp

🔧 Hide disabled hydros from skeleton view

---

source/main/scripting/GameScript.cpp
source/main/scripting/GameScript.h

Fixes many possible crashes if multiplayer server uses script functions in inappropriate time (i.e. getting simulation time in main menu)

ScriptEngine: Added missing safety checks

---

source/main/Application.cpp

It's 2019, we can handle higher default settings.
Before:
After:
Changes made:
- Screenshot format set to PNG
- Set volume to `1` (max) (fixes #2331)
- Caelum sky
- Anisotropic texture filtering
- Full vegetation
- Reflection + refraction (speed optimized) water
- Sightrange set to 5000 (unlimited)
- Reflection update rate set to `1`
- Races enabled

Better default graphic settings

---

source/main/gameplay/Character.cpp

Fixes https://github.com/RigsOfRods/rigs-of-rods/issues/2326
Before:
After:

Hide character netlabel when entering a vehicle with seat prop

---

source/main/main.cpp

Top 2 lines are new - i felt the info was missing:
```
18:35:18: [RoR] Rigs of Rods (www.rigsofrods.org) version 0.4.8.0-dev-11e17a3b-dirty
18:35:18: [RoR] Current date: 2019-05-05
18:35:18: [RoR|GVar]        sys_config_dir:  SetActive(), new: "C:\Users\Petr\Documents\Rigs of Rods 0.4\config", old: ""
18:35:18: [RoR|GVar]         sys_cache_dir:  SetActive(), new: "C:\Users\Petr\Documents\Rigs of Rods 0.4\cache", old: ""
18:35:18: [RoR|GVar]     sys_savegames_dir:  SetActive(), new: "C:\Users\Petr\Documents\Rigs of Rods 0.4\savegames", old: ""
18:35:18: [RoR|GVar]    sys_screenshot_dir:  SetActive(), new: "C:\Users\Petr\Documents\Rigs of Rods 0.4\screenshots", old: ""
18:35:18: [RoR|GVar]     sys_resources_dir:  SetActive(), new: "D:\Build\rigs-of-rods-Debug\bin\resources", old: ""
```

Version+current date now written to RoR.log

---

source/main/resources/CacheSystem.cpp
source/main/resources/ContentManager.cpp
source/main/resources/ContentManager.h

Works around insufficient sanity checking in OGRE - OGRE docs say material name is required, but the script compiler only logs 'Error' but accepts the material anyway, causing OGRE to trigger an assertion when attempting to create the material.
Fixes  #2349

Gracefully handle invalid materials with empty names

---

source/main/gfx/Renderdash.h
source/main/physics/RigSpawner.cpp

The texture-substitution used for .skin files was extended to also use 'builtins'
Fixes #2346

Allow mods to use "dashtexture" (from "renderdash")

---

resources/overlays/3d_dashboard_needles.overlay

- Restores original positions/sizes
- Fixed https://github.com/RigsOfRods/rigs-of-rods/issues/2343  
Problem was that everything where under the same wrapper/panel (introduced in https://github.com/RigsOfRods/rigs-of-rods/commit/5090df0e37677131aacce0b0b80b17c752f7e421)

:bug: Fixed missing gear indicator

---

resources/materials/ror.material
resources/overlays/directionarrow.overlay
source/main/Application.cpp
source/main/Application.h
source/main/gui/OverlayWrapper.cpp
source/main/gui/panels/GUI_GameSettings.cpp
source/main/utils/Settings.cpp

- Restores original direction arrow position
- Reverts https://github.com/RigsOfRods/rigs-of-rods/commit/6afaa854b99ab80b24dbc16e52e6bbd14a54ed62
Back then ulteq struggled to bring back the direction arrow in it's [overlay](https://github.com/RigsOfRods/rigs-of-rods/blob/master/resources/overlays/directionarrow.overlay) so he came up with an alternative way https://github.com/RigsOfRods/rigs-of-rods/commit/6afaa854b99ab80b24dbc16e52e6bbd14a54ed62 (attached directly to vehicle) which was a bit annoying sometimes so he also added a switch to turn it off.
The problem was wrong `zorder` value in the overlay

Moved direction arrow back to it's overlay

---

source/main/Application.cpp
source/main/Application.h
source/main/gfx/ShadowManager.cpp
source/main/gfx/ShadowManager.h
source/main/gui/panels/GUI_GameSettings.cpp
source/main/utils/Settings.cpp
source/main/utils/Settings.h

- Removed texture shadows. They are broken since 0.3x and they make the game crash or glitch
- Added `requires restart` info in the Shadow type selector
Fixes #2390 
Closes #2355 
Closes #84
Don't see a reason of keeping a broken feature for years. We should keep only PSSM and improve it.
@only-a-ptr thoughts?

Removed broken texture shadows

---

source/main/Application.h
source/main/MainMenu.cpp
source/main/gameplay/RoRFrameListener.cpp
source/main/gui/GUIManager.cpp
source/main/gui/GUIManager.h
source/main/network/Network.cpp
source/main/network/Network.h

@tritonas00 Thanks for bringing #2309 into my attention, I looked at it with fresh eyes and... 🤢
Status: on Win10 x64, with RoR & rorserver built as Debug/x64:
* Upon server kick, RoR returns to main menu and displays message from server.
* Reconnecting works cleanly
* Exiting game works cleanly
More work is needed, though: When server is abruptly terminated, RoR silently exits. Also `CheckConnectingState()` should not do destructive reading as it does now - there should be separate notification queue instead.

Fixed multiplayer kick handling

---

source/main/gui/panels/GUI_TopMenubar.cpp

**Issue**
Spawn the same vehicle twice or more in multiplayer, go to `Vehicles` drop down menu and try to switch between them by clicking on the entries. Only the first spawned vehicle works, others not.
**Problem**
Entries must have a unique name like in single player
**Solution**
Added hidden numbers and user uniqueid on MP actor list. Now each entry name is unique and you can switch between all actors.

Fixed switching actors on multiplayer

---

cmake/3rdparty/pmm.cmake

This fixes a bug in PMM that when one of the cmake_multi builds failed, it would continue instead of reporting the error

🔧 Update PMM to 1.6.0

---

source/main/physics/Beam.cpp
source/main/physics/Beam.h
source/main/physics/BeamData.h
source/main/physics/BeamFactory.cpp
source/main/physics/BeamFactory.h
source/main/physics/BeamForcesEuler.cpp
source/main/physics/CmdKeyInertia.cpp
source/main/physics/CmdKeyInertia.h
source/main/physics/RigSpawner.cpp
source/main/physics/RigSpawner.h

I noticed we're loading and parsing it three times when spawning any actor - for no reason (it's not configurable per actor, there's only one global config file).
UPDATE: With the last commit there's also minor performance improvement:

Load 'inertia_models.cfg' just once.

---

source/main/physics/RigSpawner.cpp
source/main/physics/RigSpawner.h
source/main/resources/ContentManager.cpp

Turns out I already resolved the same issue for 'exhausts', but I didn't for 'particles'. Now I unified the setup for both, always using correct (actor-specific) OGRE resource group.
I'm not sure how to test, though. The [DAF-semi-air](https://github.com/RigsOfRods/rigs-of-rods/issues/2344#issue-430077406) trucks don't use 'particles' keyword, only 'exhausts'. The [PittsSpecial](https://github.com/RigsOfRods/rigs-of-rods/issues/2344#issuecomment-489357708) does use 'particles', but those don't seem to show up when toggled.

Fixed custom particle name conflicts between actors

---

source/main/physics/Beam.cpp
source/main/physics/BeamData.h
source/main/physics/RigSpawner.cpp
source/main/resources/rig_def_fileformat/RigDef_File.cpp
source/main/resources/rig_def_fileformat/RigDef_File.h
source/main/resources/rig_def_fileformat/RigDef_Parser.cpp
source/main/resources/rig_def_fileformat/RigDef_Serializer.cpp

This flag makes hooks lock only to ropables instead of all nodes (default). It's been non-configurable for years and nobody noticed. Also, you can already define hook-able nodes using `lockgroups` and `lockgroup_default_nolock`
This is a diabolical PR to https://github.com/RigsOfRods/rigs-of-rods/pull/2421

Removed dead hook flag 'lock nodes'

---

resources/mygui/Utils.layout
resources/overlays/various.overlay
source/main/gui/panels/GUI_MultiplayerClientList.cpp

- Smaller notifications widget on Top Center
- Minimap now overlaps the client list
- Moved best lap time beside the timer
Should be good for now to declutter [this mess](https://user-images.githubusercontent.com/2660424/66669468-429b4b80-ec60-11e9-9c12-2dc53a62409b.png)

Declutter widgets

---

source/main/Application.cpp

- Set input grabbing to 'All' (None/Dynamic causes two mouse cursors to appear, we get reports about this almost daily)
- Enabled PSSM
- Set flares mode to 'All vehicles, all lights'

Improved default settings

---

source/main/terrain/TerrainObjectManager.cpp

Currently, all objects cast shadows except for grass. When you try to enable shadows on a terrain that features a skybox, a shadow will cast across the entire terarin, thus preventing shadows from functioning.  
This fixes that by adding a new `nocast` option to the odef file format which disables casting of shadows for the object. Allows terrains to utilize a skybox or other large objects while retaining shadow support:
Example usage:
```
AHSkyBox.mesh
1.0, 1.0, 1.0
nocast
end
```
There's probably a better way, but this works. (my coding knowledge is extremely limited lol)

 Added odef option to disable shadow casting

---

source/main/utils/InputEngine.cpp

This hides the Windows cursor when input grabbing is set to None or Dynamic. (both appear to be identical..)
Was fixed on Linux in https://github.com/RigsOfRods/rigs-of-rods/commit/d027ad1ed7a992f35b901e3d2e4f3e3ce3f44d44

Fixed double cursor on Windows

---

source/main/gui/GUIUtils.cpp
source/main/gui/GUIUtils.h

Problem: The settings GUI was only updating 'Active' value, but the FOV settings were of type `GVar_APS`, meaning state 'Stored' needed to be updated separately.
Solution: added function overload which handles `GVar_APS` entries.
Fixes #2478

Fixed FOV changes in Settings GUI not saved to RoR.cfg

---

source/main/gameplay/RoRFrameListener.cpp
source/main/physics/Savegame.cpp
source/main/resources/CacheSystem.cpp
source/main/resources/CacheSystem.h
source/main/resources/ContentManager.cpp
source/main/resources/ContentManager.h
source/main/scripting/LocalStorage.cpp
source/main/scripting/LocalStorage.h
source/main/utils/ImprovedConfigFile.h
source/main/utils/InputEngine.cpp
source/main/utils/InputEngine.h
source/main/utils/SHA1.cpp
source/main/utils/SHA1.h
source/main/utils/Settings.cpp
source/main/utils/Utils.cpp
source/main/utils/Utils.h

See #2353
I removed the TODO items, most of them were long obsolete, also I fixed several other things not even listed.
The coverage is still not 100% (for example Flexbody cache may still cause issues), but the rest is important enough to merge now.
1. Set up Conan, see https://github.com/RigsOfRods/rigs-of-rods/wiki/Compile-(Linux)#installing-the-dependencies
2. Clone https://github.com/AnotherFoxGuy/conan-OGRE and modify it by adding `cmake.definitions['CMAKE_CXX_FLAGS'] = '-D_OGRE_FILESYSTEM_ARCHIVE_UNICODE'`
3. Create the modified package `conan create . demo/testing`
4. Edit RoR's conanfile.txt: change OGRE reference to `OGRE/1.11.6@demo/testing` 
5. Use CMake to configure RoR, it will invoke Conan to fetch dependencies

Full support for Unicode file paths

---

source/main/gameplay/RoRFrameListener.cpp
source/main/gui/panels/GUI_TopMenubar.cpp
source/main/gui/panels/GUI_TopMenubar.h

@tritonas00 @CuriousMike56 My take at #2434, what do you think? The 'J' is read dynamically from 'input.map'.

Created special 'physics paused' state box

---

source/main/network/Network.cpp

The 'crash' was SocketW calling `abort()` - it does that :(
Also fixed reading server ban message - the original code was garbage and showed gibberish text on screen.
Fixes #2475
Update: Fixed my own fault when handing the message.
Update2: Removed the ban message altogether, server doesn't support them anyway.

Fixed crash when joining server where you're banned

---

source/main/gui/panels/GUI_ConsoleView.cpp
source/main/gui/panels/GUI_ConsoleView.h
source/main/gui/panels/GUI_GameChatBox.cpp

Added `cvw_filter_type_cmd`, enabled in console and disabled in chat/notifications so when you enter a command in console it will not printed as notification.

Αdded 'commands' filter

---

source/main/gui/panels/GUI_MainSelector.cpp

It was very hard to read
Before
After

Changed Source/Filename text color in selector

---

source/main/gui/panels/GUI_SurveyMap.cpp

Texture was updated all the time, we need it only when we zoom.

Fixed fps drop with small survey map

---

source/main/gui/panels/GUI_MultiplayerClientList.cpp
source/main/gui/panels/GUI_SurveyMap.cpp

- Fixes black "artifact" when opening survey map
- Sets correct multiplayer client list initial window size and fixes same "artifact" when new clients added/removed
~~@only-a-ptr i know this will make you 🤢, i'm sure there is better way :smiley:~~
I think its ok now

Survey map and MP client list window fixes

---

source/main/gui/panels/GUI_ConsoleView.cpp
source/main/gui/panels/GUI_ConsoleView.h
source/main/gui/panels/GUI_GameChatBox.cpp
source/main/gui/panels/GUI_GameChatBox.h

- Added notices/chat/warning icons
Logic already used in `GUI_MultiplayerClientList`, but here uses filters to fetch and draw icons.
Icons draw only for default enabled chat filters (notices/chat/warnings) and disabled in console, so we don't hurt performance.
- Added a nice initial message when you load a terrain for first time
- Removed chat filtering options: It was available only in multiplayer and enabling extra filters causes too much spam unlike in console where they make total sense. Currently default enabled filters are all we need.
- Reduced max chat/notification lines to 15
- Added an extra space between chat message input box and messages draw area to prevent overlapping when messages go to full bottom

[WIP] Added notification/chat icons and other improvements

---

source/main/gui/panels/GUI_MainSelector.cpp
source/main/gui/panels/GUI_MainSelector.h

This will select the default skin if no one is selected, but i don't know how to show it as an entry also.
It should always be available on top of the skinzips list.
(Example: 767 airplane)

Re added 'Default' skin in selector

---

source/main/gui/panels/GUI_ConsoleWindow.cpp
source/main/gui/panels/GUI_ConsoleWindow.h

Keep auto scrolling until we change scrollbar position (so we can see older messages undistracted), then continue auto scrolling when we move scrollbar at full bottom.
Restores @only-a-ptr original code, with some improvements:
In original code you had to move scrollbar at full bottom once to start auto scrolling. Now it happens automagically.

Enhanced console auto scrolling

---

source/main/gui/panels/GUI_ConsoleView.cpp
source/main/gui/panels/GUI_MultiplayerClientList.cpp

Fixes issue where icons in chat/notifications and client list got deformed/oversized:
Apparently we need to set size manually.

Fixed icon deformation

---

source/main/scripting/GameScript.cpp

it seems ` mse->eventMask` needs reset everytime races are loaded

Fixed races stoppage logic

---

source/main/Application.cpp
source/main/Application.h
source/main/gui/panels/GUI_TopMenubar.cpp
source/main/physics/BeamForcesEuler.cpp
source/main/utils/Settings.cpp

Currently, steering on keyboard slows down when a vehicle is traveling at high speed. This adds the ability to toggle that limitation through the dropdown Settings menu, enabled by default for backwards compatibility.  Making it much easier for keyboard players to drift or race high-downforce vehicles like the MeanMachine. 
When disabled, hydros will always move at a constant rate, regardless of wheel speed.
Video demos:
https://streamable.com/5pd58t
https://streamable.com/9wpwhz

Added setting to toggle keyboard hydro speed coupling

---

source/main/gui/panels/GUI_SurveyMap.cpp

- Fixed teleport in big map when cropped
- Fixed `mMapCenterOffset` was not reset when a new terrain is loaded
- Fixed `Overview map icons` and `Declutter overview map` settings options
First hides all icons, second hides only terrain icons
- Fixed big map when terrain has no heightmap

Survey map fixes

---

source/main/Application.cpp
source/main/Application.h
source/main/gui/panels/GUI_GameSettings.cpp
source/main/physics/Beam.cpp
source/main/utils/Settings.cpp

fixes https://github.com/RigsOfRods/rigs-of-rods/issues/2527
`RoR.cfg` option: `Blinker Lock Range`

Made blinker lock range configurable

---

resources/skeleton/config/Bluetooth_XINPUT_compatible_input_device.map
resources/skeleton/config/Logitech_Formula_Force_EX_USB.map
resources/skeleton/config/Logitech_G27_Racing_Wheel_USB.map
resources/skeleton/config/Logitech_G29_Driving_Force_Racing_Wheel_USB.map
resources/skeleton/config/Logitech_G29_Driving_Force_Racing_Wheel_USB.txt
resources/skeleton/config/RGT_Force_Feedback_Pro.map
resources/skeleton/config/Wireless_Controller.map

- Updated Xbox and G29 input maps to latest version from https://forum.rigsofrods.org/resources/xbox-one-360-ps4-controller-input-map.146/ and https://forum.rigsofrods.org/resources/logitech-g29-input-map.516/
- Added wireless PS4 controller input map
- Fixed differential lock event name

Updated input maps

---

source/main/gui/panels/GUI_TopMenubar.cpp
source/main/gui/panels/GUI_TopMenubar.h

In single player you can now remove individual actors via the vehicles menu by clicking the X button
fixes https://github.com/RigsOfRods/rigs-of-rods/issues/1616

Added remove button to Vehicles menu

---

source/main/gui/panels/GUI_ConsoleView.cpp
source/main/gui/panels/GUI_ConsoleView.h
source/main/gui/panels/GUI_GameChatBox.cpp
source/main/gui/panels/GUI_GameChatBox.h

- Implemented chat history
By pressing Y now you can see and scroll through chat messages. It shows only chat messages for a cleaner output.
- Fixes and cleanups suggested by Petr

Chat history and fixes

---

resources/skeleton/config/input.map

This fixes the toggle physics and replay mode keys conflicting. Also added a notice about adding other device inputs to input.map.
However, with this fix the physics paused notification shows EXPL:
The EXPL 'key' needs to be suppressed first before this can be merged.

Fixed toggle physics and replay mode keys conflicting

---

source/main/gameplay/RoRFrameListener.cpp

from discord:
>hm. it seems the lower FOV key (numpad 7) doesn't work now
ctrl+numpad7 to increase FOV works
Seems it was a typo

Fixed EV_COMMON_FOV_LESS not working

---

source/main/physics/Beam.h
source/main/physics/BeamFactory.cpp
source/main/resources/CacheSystem.cpp

This prevents an unhandled exception (aka "crash" because it terminates RoR) when an invalid spawn request is received in multiplayer, see #2410

Hotfix: make "resource name is empty string" non-fatal

---

source/main/system/CVar.cpp
source/main/system/CVar.h

Might not be the best solution.
Fixes #2386 (again)

Prevent logging of 'mp_player_token' and 'mp_server_password'

---

cmake/DependenciesConfig.cmake

Cloudsmith doesn't download the correct packages for the Conan OS/compiler settings

⏪ Revert "migrate Conan packages to Cloudsmith" 

---

source/main/CMakeLists.txt

This hopefully reduces Windows/Linux discrepances.
Found thanks to: https://github.com/RigsOfRods/rigs-of-rods/issues/2565#issuecomment-717489222
```
// Example program
#include <iostream>
#include <string>
#include <vector>
struct Message
{
Message(std::string const& _desc):  description(_desc) {}
Message(void* _data):  payload(_data) {}
std::string description;
void*       payload      = nullptr;
};
int main()
{
// Output:
// 'desc:abcd, payload:0000000000000000' with /permissive-
// 'desc:, payload:00007FF67BC932B0' without it.
Message m("abcd");
std::cout << "desc:" << m.description<<", payload:" << m.payload;
}
```

CMake/MSVC: disable non-standard behavior

---

source/main/CMakeLists.txt

Cmake commands `add_compile_options/add_compile_definitions` must be called BEFORE a target is defined! See https://cmake.org/cmake/help/v3.18/prop_dir/COMPILE_OPTIONS.html#prop_dir:COMPILE_OPTIONS.
After defining target, you must use `target_compile_options/target_compile_definitions`.
Fixes:
* `WIN32_LEAN_AND_MEAN` is now effective
* `/wd4305 /wd4244 -DNOMINMAX /permissive-` are effective again
*  `/wd4193` was removed because I find that warning meaningful

Hotfix: Cmake - corrected windows compiler defs and options

---

source/main/gui/panels/GUI_MultiplayerSelector.cpp
source/main/main.cpp

Reported on discord. 
Reverts https://github.com/RigsOfRods/rigs-of-rods/pull/2608/commits/4c3b21a85bcbf8fb1f190c3fd4e5219b8efa3662 but this time hides main menu last, to prevent it appearing while connecting. It seems the order was just wrong.

Fixed main menu not appearing after closing multiplayer selector using escape

---

source/main/gui/panels/GUI_ConsoleView.cpp
source/main/gui/panels/GUI_ConsoleView.h
source/main/gui/panels/GUI_GameChatBox.cpp

When chat input box is visible resize the window a bit to match line height. Works with scrolling also.
Also disables scrolling in chat input box window.

Prevent partially visible chat history messages

---

source/main/gfx/GfxActor.cpp
source/main/gfx/GfxActor.h
source/main/gfx/GfxScene.cpp
source/main/gfx/Renderdash.cpp
source/main/gfx/Renderdash.h

Separated out from #2630
Original problem: Windows/Direct3D9 renderer: when player enters any vehicle, DearIMGUI colors temporarily change (looks like a hue shift). Leaving the vehicle restores them. Memory stays intact.
Orig. solution: make renderdash RTT manually updated, see commits below.
Consequence: some GUI indicators break for no apparent reason (both Windows/Linux). Code flow is unchanged. See https://github.com/RigsOfRods/rigs-of-rods/pull/2630#issuecomment-753672831

Nonsense issues with Renderdash

---

source/main/gui/panels/GUI_FrictionSettings.cpp

Make sure the vector is empty before adding things in it
Fixes https://github.com/RigsOfRods/rigs-of-rods/issues/2665

Fixed corrupted ground type entries on resume

---

source/main/Application.h
source/main/GameContext.cpp
source/main/gui/GUIManager.cpp
source/main/gui/panels/GUI_GameMainMenu.cpp
source/main/gui/panels/GUI_GamePauseMenu.cpp
source/main/gui/panels/GUI_GameSettings.cpp
source/main/gui/panels/GUI_TopMenubar.cpp
source/main/main.cpp
source/main/scripting/GameScript.cpp

Fixes issue with "Skip main menu" setting not working.
Remake of #2680

Added  MSG_GUI_[OPEN/CLOSE]` for main menu and selector.

---

source/main/network/Network.cpp
source/main/physics/ActorManager.cpp

Requested from discord
Before:
After:
Also cleaned up extra leading spaces in `putNetMessage` messages since we already have the required space in https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/gui/panels/GUI_ConsoleView.cpp#L188
Now all `putNetMessage` messages are consistent

Removed extra username text from join/leave messages

---

source/main/main.cpp

Reported from discord
Disconnect If we are trying to connect to a server and terrain is not found

Disconnect if terrain not found

---

source/main/gui/panels/GUI_MainSelector.cpp

So it doesn't overlapped from new sized button

Reduced selector combo box size

---

source/main/main.cpp
source/main/terrain/TerrainEditor.cpp

Reported from discord
- Fixed ImGui mouse index (middle button -> 2)
- Fixed closing editor (`UpdateSimInputEvents` was running only in `RUNNING` state)

Terrain editor fixes

---

source/main/main.cpp

Reported from discord.
Loading a savegame with different terrain than the running one while on multiplayer causes unpredictable behavior (server will kick you for too many actors or if it loads other players can't see you)
With this PR it loads only the savegame which matches the running terrain or else:

Dont load savegame with different terrain in MP

---

source/main/GameContext.cpp
source/main/GameContext.h
source/main/main.cpp

Reported from discord:
> You can't advance time while in free cam mode anymore

Update sky input events in free cam mode

---

source/main/physics/Actor.cpp

Reported from discord:
> there’s this bug with the reverse beep being triggered every frame when the remote vehicle engine is not running

Fixed incorrect reverse light sound updating over network

---

source/main/network/Network.cpp

Reported from discord.
Happened when online players are more than our colors (25) https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/network/Network.cpp#L98
Before
After
`ZERO` worked when client list panel/chat was an overlay and had white background

Fixed black username color on black background

---

source/main/physics/Actor.cpp

Player A: Spawn sisu and trailer, lock them and wait
Player B: Spawn sisu and trailer, lock them and put reverse
Player A segfaults:
```
Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
0x00005555558160f4 in RoR::Actor::CalcNetwork (this=this@entry=0x5555611245f0)
at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/Actor.cpp:621
621        if (m_net_reverse_light && ar_engine->IsRunning())
(gdb) bt
#0  0x00005555558160f4 in RoR::Actor::CalcNetwork (this=this@entry=0x5555611245f0)
at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/Actor.cpp:621
#1  0x0000555555832e16 in RoR::ActorManager::UpdateActors (this=0x555555be3e40 <RoR::App::g_game_context+64>, player_actor=0x55555df12190)
at …
```

Fixed segfault with remote locked actors and reverse

---

source/main/resources/odef_fileformat/ODefFileFormat.cpp
source/main/resources/odef_fileformat/ODefFileFormat.h
source/main/terrain/TerrainObjectManager.cpp

Accidentally dropped while creating standalone ODEF parser, see https://github.com/RigsOfRods/rigs-of-rods/commit/2046c336068ffd0e024c6b5710fe2113c14cf559
Test map: https://sim-monsters.com/files/file/3309-tampa-2020-show-1/ - uses custom skybox ODEF, so without 'nocast' everything is shadowed.
Kudos @tritonas00 for discovering.

Hotfix: restored 'nocast' keyword in ODEF fileformat - resolves PSSM issues

---

source/main/scripting/GameScript.cpp
source/main/scripting/GameScript.h

Reported from discord.
Terrain scripts failed to load (example: f1 testtrack AI) because of `HaveSimController()` ('sim controller' era) always returning false. Old code: https://github.com/RigsOfRods/rigs-of-rods/commit/e38258daae7521d0fef45fff5d2f07bd69d2aaa9#diff-9cfc58687c99b253aa6c6cbbaf960563da42d5e587fcb7f645de60c915726d89L971

Removed outdated HaveSimController()

---

source/main/Application.h
source/main/GameContext.cpp
source/main/gui/panels/GUI_MainSelector.cpp
source/main/main.cpp
source/main/physics/SimData.h
source/main/resources/CacheSystem.cpp
source/main/resources/CacheSystem.h

Lightweight alternative to #2677
Closes #2674

Reloading vehicle now reloads everything (both ZIP and dir)

---

source/main/physics/Actor.cpp

Reported from discord.
`default_diesel_force.wav` defined in
https://github.com/RigsOfRods/rigs-of-rods/blob/master/resources/sounds/defaults.soundscript#L25
with gain source `injector_ratio` defined in 
https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/audio/SoundScriptManager.cpp#L980
modulated in
https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/gameplay/EngineSim.cpp#L268
for local actors only
https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/physics/ActorManager.cpp#L1016
which means for remote actors it was always on and loud (despite engine on/off)

Modulate SS_MOD_INJECTOR (aka default_diesel_force.wav) on remote actors also

---

source/main/resources/CacheSystem.cpp

Reported from discord
Till now RoR updated the cache when content added/removed.
With this PR it also checks the `filetime` for every entry and if is different from the last time it was modified it sets `validity` to `CACHE_NEEDS_UPDATE`.
Means any change inside content (zip. skinzip ...) will now trigger cache update.
Don't know if this is the right way to do it but it works.

Update cache when content changes

---

source/main/Application.h
source/main/gui/GUIManager.cpp
source/main/gui/GUIManager.h
source/main/gui/panels/GUI_MultiplayerClientList.cpp
source/main/gui/panels/GUI_MultiplayerClientList.h
source/main/main.cpp
source/main/network/Network.cpp

Reduces performance hit from the MP client list window. User infos are now cached in the window and only updated when network state changes.

Reduced FPS hit from multiplayer client list window.

---

source/main/physics/ActorManager.cpp

Fixed beams not visible after spawn if truck has no cinecam.

---

source/main/GameContext.cpp
source/main/gfx/EnvironmentMap.cpp

Even if disabled in config, the realtime envmap is fully rendered once after loading terrain, to provide static reflections.
Kudos to NegativeIce for reporting!

Fixed static reflection map being black.

---

source/main/gfx/EnvironmentMap.cpp

Fixed the `Reflections=Yes/No` setting not being respected
Now it works exactly like in 2020.01:
Reflections=No:
Reflections=Yes, ReflectionUpdateRate=0:
Reflections=Yes, ReflectionUpdateRate=1:
Reflections=Yes, ReflectionUpdateRate=2:
etc...

Fixed reflection settings

---

source/main/GameContext.cpp
source/main/GameContext.h
source/main/gui/panels/GUI_TopMenubar.cpp
source/main/physics/SimData.h

There are 3 new menu items in the Simulation menu of top menubar. Both are only visible when not in vehicle.
* **Reload last spawned vehicle** - Works much like trusty old "Reload current vehicle", but it doesn't require you to drive the vehicle. Useful for modding loads which aren't automatically entered on spawn.
* **Activate last spawned vehicle** - Wakes up the vehicle. Again, useful for loads which are spawned sleeping and not auto-entered.
* **Remove last spawned vehicle** - Works like good old "Remove current vehicle" but operates on the last one spawned.

Added "reload/activate last spawned vehicle" to TopMenubar/Simulation menu.

---

source/main/GameContext.cpp
source/main/gfx/GfxActor.cpp
source/main/network/RoRnet.h
source/main/physics/Actor.cpp
source/main/physics/Actor.h
source/main/physics/ActorSpawner.cpp
source/main/physics/Savegame.cpp
source/main/physics/SimConstants.h
source/main/physics/SimData.h

Continued from #2690
Testing vehicle:
[netflare-agoras.zip](https://github.com/RigsOfRods/rigs-of-rods/files/6267505/netflare-agoras.zip)
goes by hand with RigsOfRods/ror-server#109
closes #2664

Display all 10 user flares in multiplayer.

---

source/main/Application.h
source/main/terrain/TerrainObjectManager.cpp

ODEF collmesh with empty name is now non-fatal:
Same thing if mesh isn't found:

(Hotfix) 2 less crashes when loading terrains.

---

source/main/Application.cpp
source/main/Application.h
source/main/gui/panels/GUI_TopMenubar.cpp
source/main/physics/ActorManager.h
source/main/system/CVar.cpp

The UI code was removed by Petr because big values could lead to bad performance (https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/gui/panels/GUI_TopMenubar.cpp#L413-L420)
Still `diag_physics_dt` could be read from RoR.cfg (`PhysicsTimeStep`), so if a big value was set from a user with previous RoR version it could still lead to bad performance.
This completely removes `diag_physics_dt`, sets `PHYSICS_DT` at default 0.5 ms and eliminates user errors.

Removed diag_physics_dt

---

source/main/gui/DashBoardManager.cpp
source/main/gui/DashBoardManager.h
source/main/network/OutGauge.cpp
source/main/physics/Actor.cpp
source/main/physics/Actor.h
source/main/physics/ActorManager.cpp
source/main/physics/ActorSpawner.cpp
source/main/physics/SimData.h
source/main/resources/rig_def_fileformat/RigDef_File.h
source/main/resources/rig_def_fileformat/RigDef_Parser.cpp
source/main/resources/rig_def_fileformat/RigDef_Parser.h
source/main/resources/rig_def_fileformat/RigDef_Serializer.cpp

**Changes**:
* Added new type flag for flares, 'd' (dashboard indicator) - instead of a control number, you enter an input source from our dashboard system: https://docs.rigsofrods.org/vehicle-creation/making-custom-hud/#input-sources
* Restored support for special control number '12' which represents parking brake.
**Example**:
```
flares
7,3,6,   0.12, 0.3,       d, engine_ignition
7,3,6,   0.45, 0.3,       d, engine_battery
7,3,6,   0.72, 0.3,       d, engine_clutch_warning
7,3,6,   0.12, 0.15,      d, parkingbrake
7,3,6,   0.28, 0.15,      d, locked
7,3,6,   0.45, 0.15,      d, low_pressure
7,3,6,   0.68, 0.15,      d, signal_warning
```
**Demonstration**:
Test vehicle: [flareboard.zip](https://github.com/RigsOfRods/rigs-of-rods/files/6308858/flareboard.zip)

Added flare type 'd' (dashboard indicator)

---

source/main/gui/panels/GUI_GameChatBox.cpp

Reported from forum:
> I can't steer, move around, change the view, or do any main command if my cursor is placed anywhere near the bottom part of my screen.
https://forum.rigsofrods.org/threads/2021-04-discussion-thread.3128/#post-14973

Don't check if chat window is mouse hovered

---

cmake/DependenciesConfig.cmake
conanfile.txt

Closes #2667
----------------
Note: on windows the old discord-rpc needs to be removed with `conan remove discord-rpc`

🔧 Migrate Conan packages to Cloudsmith

---

source/main/physics/Actor.h
source/main/physics/ActorForcesEuler.cpp
source/main/physics/ActorSpawner.cpp
source/main/physics/SimData.h

This will now work:
```
wheeldetachers
; wheel_ID, detacher_group
0, 1
0, 2
```
Also, beam break logging (`diag_log_beam_break` in RoR.cfg or TopMenubar/Tools) now logs to ingame console (in addition to classic RoR.log).
Suggested by DannyWerewolf on Discord.

Wheel can now have multiple detacher groups.

---

source/main/AppContext.cpp
source/main/GameContext.cpp
source/main/gameplay/CruiseControl.cpp
source/main/gameplay/EngineSim.cpp
source/main/gameplay/RecoveryMode.cpp
source/main/gameplay/SceneMouse.cpp
source/main/gameplay/VehicleAI.cpp
source/main/gfx/GfxActor.cpp
source/main/gfx/GfxActor.h
source/main/gfx/camera/CameraManager.cpp
source/main/gui/OverlayWrapper.cpp
source/main/gui/panels/GUI_NodeBeamUtils.cpp
source/main/gui/panels/GUI_SimActorStats.cpp
source/main/gui/panels/GUI_TopMenubar.cpp
source/main/gui/panels/GUI_VehicleDescription.cpp
source/main/main.cpp
source/main/physics/Actor.cpp
source/main/physics/Actor.h
source/main/physics/ActorForcesEuler.cpp
source/main/physics/ActorManager.cpp
source/main/physics/ActorSlideNode.cpp
source/main/physics/ActorSpawner.cpp
source/main/physics/Savegame.cpp
source/main/physics/collision/PointColDetector.cpp
source/main/scripting/GameScript.cpp
source/main/scripting/ScriptEngine.cpp
source/main/system/ConsoleCmd.cpp

This is a code cleanup only. No features should change.
Functions in `class Actor` (aka `BeamClass` in script) restored to original format in v0.4.0.8 (year 2013 and prior). Reference: https://github.com/only-a-ptr/rigs-of-rods/blob/retro-0407/source/main/physics/Beam.h
Motivations:
* To have same function names in script and codebase. In recent years it diverged a lot, for no good reason.
* To be able to consistently extend the scripting interface.
* To restore the useful grouping of functions in Actor.h (formerly Beam.h)

:boomerang: Actor (BeamClass) functions renamed to original format.

---

doc/angelscript/BeamClass.h
source/main/scripting/ScriptEngine.cpp

This will allow scripts to determine which section config is loaded on a given truck.
Example usage:
```
BeamClass@ t = game.getCurrentTruck();
game.log("Spawned section config is: " + t.getSectionConfig());
```

Angelscript: added function 'getSectionConfig()' to 'BeamClass'

---

source/main/utils/MeshObject.cpp

**Problem**: when 2 mods (each with it's own bundle) contain mesh with the same file name, they will clash with each other. The first mod loaded will override the mesh for all others until the game is restarted. This applies to props (vehicle) and odefs (terrain).
**Cause**: class MeshObject was searching for the mesh name globally instead of using the mod's resource group. This is classic behavior, some mods might rely on it.
**Fix**: use the mod's resource group, as already done for most resources.
Mods I used for testing:
[agora-meshmix1.zip](https://github.com/RigsOfRods/rigs-of-rods/files/7069858/agora-meshmix1.zip)
[agora-meshmix2.zip](https://github.com/RigsOfRods/rigs-of-rods/files/7069859/agora-meshmix2.zip)

Hotfix: only load prop mesh from own resource group.

---

source/main/gui/panels/GUI_TopMenubar.cpp

Problem:
Load nhelens, start race, back to menu, load nhelens modded:
```
Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
0x00005555557ae73c in RoR::GUI::TopMenubar::DrawSpecialStateBox (this=0x5555571efc88, top_offset=10)
at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gui/panels/GUI_TopMenubar.cpp:864
864	        if (player_actor != nullptr &&
```
```
(gdb) bt
#0  0x00005555557ae73c in RoR::GUI::TopMenubar::DrawSpecialStateBox (this=0x5555571efc88, top_offset=10)
at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gui/panels/GUI_TopMenubar.cpp:864
#1  0x00005555557b11e4 in RoR::GUI::TopMenubar::Update (this=0x5555571efc88)
at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gui/panels/GUI_TopMenubar.cpp:83
#2 …
```

Fixed segfault when switching terrain with active race

---

source/main/resources/odef_fileformat/ODefFileFormat.cpp

Old code was:
https://github.com/RigsOfRods/rigs-of-rods/commit/2046c336068ffd0e024c6b5710fe2113c14cf559
Fixes https://github.com/RigsOfRods/rigs-of-rods/issues/2745
@only-a-ptr Is this correct or we need to be specific? Like
```
if strncmp(ev_type, "",  0)
```

Fixed races not loading when event type is not defined

---

source/main/gui/panels/GUI_GameControls.cpp

In multiplayer exiting controls panel with escape, closed main menu also.

Fixed closing order of controls panel/main menu in MP

---

source/main/GameContext.cpp
source/main/gameplay/EngineSim.cpp
source/main/gfx/camera/CameraManager.cpp
source/main/gui/panels/GUI_ConsoleView.cpp
source/main/gui/panels/GUI_GameChatBox.cpp
source/main/main.cpp
source/main/physics/Actor.cpp
source/main/physics/ActorManager.cpp
source/main/scripting/GameScript.cpp
source/main/scripting/GameScript.h
source/main/system/Console.cpp
source/main/system/Console.h
source/main/terrain/TerrainEditor.cpp

Now if icon is given in `putMessage()` it will show up, if not, per area icons apply as before.
There are a lot, some of them:
Also cleaned up `putMessage()`, except https://github.com/RigsOfRods/rigs-of-rods/blob/d4ace1fb9787359c46697fc39980a12b7703b681/source/main/scripting/ScriptEngine.cpp#L269 to prevent breakage of https://github.com/tritonas00/RoRServerScripts

Revived legacy icons

---

external/angelscript_addons/scriptstdstring/scriptstdstring.cpp
source/main/gui/imgui/OgreImGui.cpp

This annoyed me for quite a while. Apparently some terrain subsystems disable overlays on load, so imgui is never rendered and assert()ed about it.
While at it, I fremoved another nuissance which assert()ed on every exit - a check in AngelScript string subsytem that everything was cleared.

Fixed imgui debug assert - missing EndFrame()

---

source/main/gui/panels/GUI_GameChatBox.cpp
source/main/gui/panels/GUI_SimActorStats.cpp
source/main/gui/panels/GUI_SimPerfStats.cpp
source/main/gui/panels/GUI_SimPerfStats.h
source/main/gui/panels/GUI_TopMenubar.cpp
source/main/main.cpp
source/main/terrain/TerrainEditor.cpp
source/main/utils/InputEngine.cpp
source/main/utils/InputEngine.h

- Replaced welcome message with something more useful:
- Added special box for terrain editing mode
and a tooltip
- Added `getEventCommandTrimmed` to trim EXPL from shortcut names and removed `''` for cleaner text
- Fixed terrain editor objects moving  (introduced with https://github.com/RigsOfRods/rigs-of-rods/pull/2816)
- Fixed stuttering when moving objects in terrain editor
- Fixed typo in icon names in terrain editor
- `EV_COMMON_ENTER_CHATMODE:` use Y explicitly because it interferes with `EV_COMMON_TOGGLE_TERRAIN_EDITOR`
- Αdded PlotHistogram in SimPerfStats and unified theme with SimActorStats and TopMenubar

Various UI changes and terrain editor fixes

---

source/main/GameContext.cpp
source/main/gameplay/SceneMouse.cpp
source/main/gameplay/SceneMouse.h
source/main/gfx/GfxActor.h
source/main/gfx/GfxData.h
source/main/gfx/camera/CameraManager.cpp
source/main/physics/Actor.cpp
source/main/physics/Actor.h
source/main/physics/ActorForcesEuler.cpp
source/main/physics/ActorSpawner.cpp
source/main/physics/ActorSpawner.h
source/main/physics/SimData.h
source/main/physics/air/TurboJet.cpp
source/main/physics/air/TurboJet.h
source/main/physics/air/TurboProp.cpp
source/main/physics/air/TurboProp.h
source/main/physics/flex/FlexAirfoil.cpp
source/main/physics/flex/FlexAirfoil.h
source/main/physics/flex/FlexBody.cpp
source/main/physics/flex/FlexBody.h
source/main/physics/flex/Locator_t.h
source/main/physics/water/ScrewProp.cpp
source/main/physics/water/ScrewProp.h

This PR officially introduces a node limit of 65535 nodes (2^16 - 1). This limit was always present but rather hidden - all node number values were `int` (4 bytes) except `node_t::pos` which was `unsigned short` (2 bytes).
I introduced data type`NodeNum_t` and constant `NODENUM_INVALID` which should be used to address nodes instead of the classic `int` data type and `-1` value, or the newer but only scarcely used `uint16_t` data type and `node_t::INVALID_IDX` value.
2 exceptions:
* Flexbody generation - to be done (just internal - low importance).
* Savegame - to avoid version bump.

Code clarity: Using `NodeNum_t/NODENUM_INVALID` instead of `int/-1`

---

cmake/dependencies-helpers/OpenAL.cmake
cmake/dependencies-helpers/RapidJSON.cmake

- on ubuntu OpenAL does not come with a CMakeConfig
- rapidjson is header only

fix build using system libs

---

source/main/CMakeLists.txt
source/main/gui/panels/GUI_AngelScriptExamples.cpp
source/main/gui/panels/GUI_AngelScriptExamples.h
source/main/gui/panels/GUI_ConsoleView.cpp
source/main/gui/panels/GUI_ConsoleWindow.cpp
source/main/gui/panels/GUI_ConsoleWindow.h
source/main/system/ConsoleCmd.cpp

Added AngelScript shortcuts in console

---

doc/angelscript/InputEngineClass.h
doc/angelscript/global_functions.h
resources/scripts/demo_script.as
source/main/Application.cpp
source/main/Application.h
source/main/CMakeLists.txt
source/main/main.cpp
source/main/resources/ContentManager.cpp
source/main/scripting/GameScript.cpp
source/main/scripting/InputEngineAngelscript.cpp
source/main/scripting/ScriptEngine.cpp
source/main/scripting/ScriptEngine.h
source/main/system/AppCommandLine.cpp
source/main/system/CVar.cpp
source/main/system/Console.h
source/main/terrain/TerrainManager.cpp
source/main/utils/InputEngine.h

This feature branch gives you the ability to run AngelScript scripts on launch and have them running continuously until the game shutdown, in both menu and simulation (both single and multiplayer).
The game interface is the same which terrain scripts use, with new extension: global object `input` which lets you retrieve configured controls and current input states.
There is an example script 'demo_script.as' in the "resources/scripts" directory (or 'resources/scripts.zip' package when installed). You can run it by 2 ways:
* from command line: `ror -runscript demo_script.as` (you can load multiple scripts by using `-runscript` repeatedly)
* from RoR.cfg: `app_custom_scripts=demo_script.as` (you can enter multiple filenames delimited by comma).
Showcase of the example script:
This is …

Basic support for plugin scripts.

---

source/main/physics/ActorSpawner.cpp
source/main/physics/air/TurboProp.cpp
source/main/physics/air/TurboProp.h

Fixes crash when spawning two skyvans with particle system enabled:
```
[RoR|Actor|Error] (Keyword: turboprops2) ItemIdentityException: An object of type 'ParticleSystem' with name 'TurboPropSmoke 0' already exists. in SceneManager::createMovableObject at /home/runner/.conan/data/ogre3d/1.11.6.1/anotherfoxguy/stable/build/feae01c5ea595a814bc5825447abdab1e39d6062/OgreMain/src/OgreSceneManager.cpp (line 4117)
```
Introduced with https://github.com/RigsOfRods/rigs-of-rods/commit/a8ad30bdd42f64874549681eebd599307c4a156f

[TurboProp] Brought back propname

---

source/main/gui/panels/GUI_GameControls.cpp

Makes it more consistent and easier to catch

Bigger shortcut buttons in controls panel

---

source/main/gui/imgui/OgreImGui.cpp

I'm getting debug asserts from DearIMGUI that `NewFrame()/EndFrame()` functions are not being called in sync. It only happens at certain stage of loading certain terrains. Things to know before moving further:
* our DearIMGUI integration is a port of OGRE 1.12's OgreImGuiOverlay, since we're still running at 1.11.6 (last time we checked, MyGUI didn't work with latest ogre).
* `NewFrame()` is invoked [from main()](https://github.com/RigsOfRods/rigs-of-rods/blob/4cd184a9606851ba89e13591c768f27239085e4b/source/main/main.cpp#L872)
* `Render()` is called from within [`Ogre::RenderQueueListener::renderQueueStarted()` callback](https://github.com/RigsOfRods/rigs-of-rods/blob/4cd184a9606851ba89e13591c768f27239085e4b/source/main/gui/imgui/OgreImGui.cpp#L131) implemented in …

Fixing DearIMGUI `NewFrame()/EndFrame()` cycle.

---

source/main/main.cpp

Since it can't be moved at that stage.

Hide mouse when loading terrain

---

source/main/main.cpp

Fixes https://github.com/RigsOfRods/rigs-of-rods/issues/2860
It happened only on `EV_COMMON_REMOVE_CURRENT_TRUCK`, removing from top menu bar works fine.

Fixed crash when deleting actor while holding backspace

---

source/main/gfx/GfxActor.cpp

Fixes https://github.com/RigsOfRods/rigs-of-rods/issues/330
Tested with agora though, since i can't reproduce the tatra bug

Fixed caelum sky rendered black on mirrors

---

source/main/gui/panels/GUI_ConsoleView.cpp

Icon names can be defined from scripts etc.... I corrected some invalid names some time ago, but better be sure.
Also i'm not sure if `Ogre::TextureManager::getSingleton().load` every frame is good practice...

Don't crash on invalid icon name

---

source/main/resources/CacheSystem.cpp

Resource management is hard.
There's usually more than one .truck and possibly several .skin entries in a ZIP file from the repo. Modcache creates a `CacheEntry` for each of these, and it must keep them in sync - when one is loaded, the others must be notified. This was hapenning correctly on unloading, but not on (re)loading.

Fixed skinned vehicles showing pink after reload

---

.github/workflows/build-game.yml

Upgraded to windows-2019 since windows-2016 is no longer supported

👷 Updated windows CI image to windows-2019

---

source/main/terrain/TerrainObjectManager.cpp

Lately i'm getting
```
FATAL ERROR: An internal error occured in Rigs of Rods.
Technical details below: 
RenderingAPIException: Closer detail levels must be added before farther ones in PagedGeometry::addDetailLevel() at /home/babis/Downloads/ror-dependencies/Source/paged-geometry/source/PagedGeometry.cpp (line 365)
```
when loading brutal valley. This fixes it
min is 40 and max 41 which makes the error valid
vegetation density must be set to 20% to reproduce.

Paged: check if farther details level is greater than closer

---

resources/managed_materials/shadows/pssm/on/shadows.material

- Fixes character color glitch with PSSM
Managed to reproduce the issue on my laptop, it also happens with VS 2019
Before:
After:
- Fixes https://github.com/RigsOfRods/rigs-of-rods/issues/361. It happens with new materials, PSSM and reflections on
Before:
After:
Reference: https://ogrecave.github.io/ogre/api/13/_material-_scripts.html#autotoc_md131

Fixed visual glitches with PSSM

---

cmake/GenerateVersionInfo.cmake
source/version_info/CMakeLists.txt

This feature got added in #1387, but it got broken when we switched from semver to rolling releases
Usage: Set `ROR_CUSTOM_VERSION` to `[year].[month]-[prefix]`

:bug: Fixed CMake option for specifying a custom version

---

resources/managed_materials/managed_mats_vehicles.material
resources/managed_materials/shadows/pssm/on/shadows.material
resources/materials/character.material

Setting it globally on `shadows.material` kills survey map (with PSSM on):

Set depth_bias only on character/vehicles

---

.github/workflows/build-game.yml

No longer needed, the DirectX 9 SDK will now be installed by conan

:construction_worker: Remove DirectX SDK install step

---

source/main/gui/panels/GUI_MainSelector.cpp

When a certain category is selected, search box searches on that category, not All.

Fixed selector switching to "All" category when searching

---

cmake/DependenciesConfig.cmake

Update zlib to 1.2.12 due to https://github.com/advisories/GHSA-jc36-42cf-vqwj

:arrow_up: Update zlib to 1.2.12

---

source/main/gui/panels/GUI_MultiplayerClientList.cpp
source/main/network/Network.cpp

- Fixes visibility
Before:
After:
- Fixes not resetting on disconnect, which made it appear always when connecting to another server

Network quality indicator fixes

---

source/main/gui/GUIUtils.cpp
source/main/gui/GUIUtils.h
source/main/gui/panels/GUI_LoadingWindow.cpp
source/main/gui/panels/GUI_MultiplayerSelector.cpp
source/main/gui/panels/GUI_MultiplayerSelector.h

Replaced old spinner with the one from the repo panel
Also replaced "refreshing" message with spinner in mp selector

Replaced old spinner

---

source/main/gfx/GfxActor.cpp

For example Liebherr13HM.
Introduced by 5095ec9263138fd5fb55abb63bf55554d508cdba

Hotfix: game hangs when spawning any truck with hooks.

---

resources/skeleton/config/input.map
source/main/GameContext.cpp
source/main/scripting/InputEngineAngelscript.cpp
source/main/utils/InputEngine.cpp
source/main/utils/InputEngine.h

'E' is generally known as 'use' and what it does here is confusing... and people obviously press it by accident

Removed hotkey COMMON_TOGGLE_RENDER_MODE (Keyboard E)

---

source/main/resources/CacheSystem.cpp
source/main/resources/CacheSystem.h

The check was only done after attempting to load the file contents. It must be done after JSON parsing but before loading contents.

Fixed cache-file version check.

---

source/main/physics/ActorSpawner.cpp
source/main/resources/rig_def_fileformat/RigDef_File.h
source/main/resources/rig_def_fileformat/RigDef_Parser.cpp
source/main/resources/rig_def_fileformat/RigDef_Serializer.cpp

It turns out the `i` flag has a bug: it always makes the hydro invisible, but if it comes as first/single flag, then it also makes the hydro commanded by steering input. That means:
* `ri` will make the hydro respond only to airplane rudder, and invisible.
* `ir` will make the hydro respond to both airplane rudder and steering input, and invisible. This makes it behave a lot different than plain hydro though, and many SimMonsters mods use it as a feature.
To resolve backward compatibility, I added a new flag `j`, which makes the hydro invisible but without the quirks of `i`. The parser still recognizes `i` but internally I'm using only `j` and `n`.
The documentation https://docs.rigsofrods.org/vehicle-creation/fileformat-truck/#hydros needs to be updated:
* `` no flags given -> force `n` …

Added hydro flag `j`, restored bug with `i` for backw. compat.

---

source/main/GameContext.cpp
source/main/gfx/GfxActor.cpp
source/main/gfx/GfxActor.h
source/main/gfx/GfxData.h
source/main/gfx/GfxScene.cpp
source/main/gfx/SimBuffers.h
source/main/network/RoRnet.h
source/main/physics/Actor.cpp
source/main/physics/Actor.h
source/main/physics/ActorManager.cpp
source/main/physics/ActorSpawner.cpp
source/main/physics/SimData.h
source/main/resources/rig_def_fileformat/RigDef_File.h
source/main/resources/rig_def_fileformat/RigDef_Parser.cpp
source/main/resources/rig_def_fileformat/RigDef_Serializer.cpp

Kindly requested from Discord by Flip889#6304 and BRobinson#9257
As a bonus, key-triggered prop animations now propagate over network:
RoRnet was bumped to .44

Prop anims with 'eventlock' now remain active if player leaves vehicle (+multiplayer).

---

.github/workflows/build-game.yml

This removes the need for using `actions/cache` twice

:construction_worker: Disabled conan short paths on gh-actions windows build

---

source/main/Application.cpp
source/main/Application.h
source/main/GameContext.cpp
source/main/system/CVar.cpp

Resolves #2957 
`PM_SOLID` is the default when rendering, `setint gfx_polygon_mode 3`
`PM_WIREFRAME` to show the wireframe `setint gfx_polygon_mode 2`
`PM_POINTS` to show the points of each wireframe `setint gfx_polygon_mode 1`

:sparkles: Added polygon mode (aka render mode) as cvar

---

resources/skeleton/config/Microsoft_X_Box_360_pad.map
resources/skeleton/config/Sony_PLAYSTATION_R_3_Controller.map

New key map X_Box_360 with wireless receiver for linux

New key map X_Box_360 with wireless receiver for linux

---

resources/scripts/AI.as
source/main/GameContext.cpp
source/main/gameplay/VehicleAI.cpp
source/main/gui/panels/GUI_TopMenubar.cpp
source/main/gui/panels/GUI_TopMenubar.h
source/main/scripting/GameScript.cpp
source/main/scripting/GameScript.h
source/main/scripting/bindings/GameScriptAngelscript.cpp

- A new Drag Race mode added which auto configures the settings and makes possible to select two vehicles to perform a drag race. Returning to other modes preserves the previous selections.
Just two waypoints making a line are enough for this mode.
- A new Crash driving mode added which auto configures the settings and makes possible to select two vehicles to perform a crash. Returning to other modes preserves the previous selections.
Again just two waypoints making a line are enough for this mode.
- Fixed setting sectionconfig when skin is also available
- Moved driving mode on top
- Don't allow changing mode when AI is running
- If no preset found, show supported terrains list also (fetchable from json)
- Prefer local file `savegames/waypoints.json` if exists

AI: Added Drag Race and Crash driving modes, fixes and UI improvements

---

source/main/resources/rig_def_fileformat/RigDef_File.h
source/main/resources/rig_def_fileformat/RigDef_Parser.cpp

Quite a few mods use the 'v' beam option to make beams visible, even though they're actually visible by default. This prevents the console from getting spammed by warnings:
I don't really know how the parser works but this seems to do the job.

Parser: Ignore 'v' beam option

---

source/main/gui/panels/GUI_GameControls.cpp
source/main/gui/panels/GUI_GameControls.h
source/main/utils/InputEngine.h

only entries actually present in 'input.map' were shown, other controls were missing.
If you edit an entry which wasn't present in 'input.map' before, it will be added.

Fixed ControlsUI not showing built-in defaults

---

source/main/gui/imgui/OgreImGui.cpp
source/main/gui/imgui/imgui.h
source/main/gui/panels/GUI_MainSelector.cpp

- Slash (/) now focus the search bar in main selector.
- Right/Left arrows now switch categories if search input is empty, no need to unfocus search bar to use them.
- Properly search all categories.
Requested from discord.

Main selector improvements

---

source/main/scripting/GameScript.cpp
source/main/system/ConsoleCmd.cpp
source/main/terrain/Terrain.cpp
source/main/terrain/TerrainEditor.cpp
source/main/terrain/TerrainObjectManager.cpp
source/main/terrain/TerrainObjectManager.h

* Terrain editor: fixed crash when terrain has no objects and user presses `{` or `}` hotkeys. Found by CuriousMike on Discord.
* Console: command `spawnobject` now correctly reports error if file isn't found. Previously it always responded "success, spawned object at..."

Terrain editing fixes

---

source/main/terrain/TerrainObjectManager.cpp
source/main/utils/ConfigFile.cpp

When the map is flawed, there's no point in throwing that errors on the player - I made a bypass where the errors display only during simulation (ODEFs loaded from script or console), not during map loading.

Only display terrain object errors if it's user's fault

---

source/main/gui/panels/GUI_FlexbodyDebug.cpp
source/main/physics/ActorSpawner.cpp
source/main/resources/rig_def_fileformat/RigDef_Regexes.h
source/main/utils/MeshObject.cpp
source/main/utils/MeshObject.h

Fixes:
* https://forum.rigsofrods.org/resources/mercedes-benz-atego-1318-comax.344/ - some flexbodies were missing because truckfile parser was too strict on syntax. Restored to original.
* https://forum.rigsofrods.org/resources/c1-offshore.182/ - segfault due to missing simbuffer update when procesing 'wings'. Only hapenned for vehicles without 'flexbodies' or 'wheels'.

Vehicle spawning fixes

---

source/main/GameContext.cpp

Fixes issue with AI airplanes enabling brake when character gets out.

Do not set brake when exiting AI vehicles

---

source/main/GameContext.cpp

Reported on Discord by The Jesser#8202
Problem: Race display in top menubar tries to access Actor which was already deleted.
Cause: the top menubar is rendered in between removing the actor and updating the simbuffer, so it draws a dangling Actor pointer from the simbuffer.
Broken by: 547227575fa58a5ed9a2218fa78d6297c8906f42 where the race display was moved to top menubar.
Fix: Update simbuffer immediately after removing actor.

Fixed crash when reloading actor during race

---

source/main/GameContext.cpp
source/main/GameContext.h
source/main/gui/panels/GUI_MainSelector.cpp
source/main/gui/panels/GUI_MainSelector.h
source/main/resources/CacheSystem.cpp
source/main/resources/CacheSystem.h
source/main/resources/rig_def_fileformat/RigDef_File.h
source/main/resources/rig_def_fileformat/RigDef_Parser.cpp
source/main/resources/rig_def_fileformat/RigDef_Parser.h
source/main/resources/rig_def_fileformat/RigDef_Regexes.h

Syntax: default_skin <skin_name_with_underscores_for_spaces>
Example: `default_skin Viper_Yellow/Black_Stripe`
This works with classic .skin files (which may be in the mod ZIP itself or separate SKINZIP). When used, the game will display that skin on top of skin selector, instead of the dummy "Default skin" entry. If no other skins are found, the game will apply this skin automatically and won't display the selector at all.
Closes #2990 
Closes #2909
Cache file version was bumped from 11 to 12 because it must remember the skin name.
The selector UI displays the default skin in the details.

Added 'default_skin' directive to truck file format

---

source/main/physics/Actor.h
source/main/physics/ActorForcesEuler.cpp
source/main/physics/SimData.h
source/main/physics/collision/Collisions.cpp
source/main/physics/collision/Collisions.h

Previously only the main camera node activated eventboxes. This was a bad fit for i.e. races vs. the finishing line.
The process of invoking the event boxes was inverted - instead of searching an event box for the camera node, all event boxes close to the actor are searched for a hit with any node. Hits are recorded and next time the recorded colliding node is checked first.
I checked performance impact on Auriga race under Debug. There seems to be no noticeable FPS drop.
Code changes:
* Actor::CalcForcesEulerCompute() - call to UpdateBoundingBoxes() moved here from CalcNodes(). Added call to CalcEventBoxes().
* Actor::CalcEventBoxes() - searches and records hits with eventboxes, as described above.
* Collisions::nodeCollision() - no longer processes event boxes, the parameter was …

Any node now activates script event boxes

---

resources/managed_materials/managed_mats_vehicles.material
resources/managed_materials/shadows/pssm/on/shadows.material
source/main/Application.cpp
source/main/Application.h
source/main/gui/panels/GUI_GameSettings.cpp
source/main/physics/ActorSpawner.cpp
source/main/system/CVar.cpp

After the release of 2022.12, some players apparently prefer the other vehicle materials instead of the current NiceMetal-based materials. This brings those back by adding "Use alternative vehicle materials" to the graphics settings.
~PR is currently a draft as~ I'd like to also fix the slight flickering the materials have, introduced after 2020.01: 
https://streamable.com/3unrvg
After tinkering with the materials a little, I managed to stop the flickering by commenting out all `depth_bias` lines in `managed_mats_vehicles.material` and changing the value in `shadows.material` to `depth_bias -20`. However, with this change vehicles now look like this when the camera is far away:
(Lowered FOV)

Added setting to use alternative vehicle materials

---

source/main/physics/ActorSpawner.cpp

This was a bug introduced with 0e8e64644c685ccdd1904c53260269d1473406a0 - managedmaterial processing got refactored and new logic didn't match the old logic - new checks for missing textures were overzealous and disabled the entire material instead of disabling just the related effect.
Fixes #3005

Fixed white managedmat if specular/damage texture missing

---

source/main/resources/tobj_fileformat/TObjFileFormat.cpp
source/main/resources/tobj_fileformat/TObjFileFormat.h
source/main/scripting/GameScript.cpp
source/main/terrain/TerrainObjectManager.cpp
source/main/terrain/TerrainObjectManager.h

TOBJ fileformat: added `set_default_rendering_distance`
This is a directive - you can place it anywhere and it affects all lines that come after it, much like directives in the truck fileformat do.
The parameter is distance in meters. 0 means infinite distance (object is always rendered). Default value is 0.
Internally, it uses `Ogre::Entity::setRenderingDistance()`, see https://ogrecave.github.io/ogre/api/1.11/class_ogre_1_1_movable_object.html#afe1f2a1009e3f14f36e1bcc9b1b9557e
Examples:
```
; limit distance to 10 meters
set_default_rendering_distance 10.0
; reset to infinite distance
set_default_rendering_distance 0
```
NOTE: I observed there is some glitch in the distance calculation, even with the same distance value, some objects appear faster than others. I debugged my code and …

TOBJ fileformat: added `set_default_rendering_distance`

---

resources/skeleton/config/Bluetooth_LE_XINPUT_compatible_input_device.map
resources/skeleton/config/Bluetooth_XINPUT_compatible_input_device.map
resources/skeleton/config/Controller__Afterglow_Gamepad_for_Xbox_360_.map
resources/skeleton/config/Controller__XBOX_360_For_Windows_.map
resources/skeleton/config/Controller__Xbox_360_Wireless_Receiver_for_Windows_.map
resources/skeleton/config/Controller__Xbox_One_For_Windows_.map
resources/skeleton/config/Logitech_G27_Racing_Wheel_USB.map
resources/skeleton/config/Logitech_G29_Driving_Force_Racing_Wheel_USB.map
resources/skeleton/config/Microsoft_X_Box_360_pad.map
resources/skeleton/config/Microsoft_X_Box_360_pad_0.map
resources/skeleton/config/Saitek_ST290_Pro.map
resources/skeleton/config/Sony_PLAYSTATION_R_3_Controller.map
resources/skeleton/config/Xbox_360_Wireless_Receiver.linux.map
resources/skeleton/config/Xbox_360_Wireless_Receiver.windows.map
resources/skeleton/config/input.map

- Added Steam Deck input map
- Fixed headlight toggle key in all input maps 
`COMMON_TOGGLE_TRUCK_LIGHTS` -> `COMMON_CYCLE_TRUCK_LIGHTS`

Added Steam Deck input map + Fixed headlight toggle key

---

doc/angelscript/Script2Game/GameScriptClass.h
doc/angelscript/Script2Game/SoundClass.h
doc/angelscript/Script2Game/SoundScriptInstanceClass.h
doc/angelscript/Script2Game/SoundScriptTemplateClass.h
doc/angelscript/Script2Game/sound_enums.h
resources/scripts/demo_script.as
source/main/CMakeLists.txt
source/main/ForwardDeclarations.h
source/main/audio/Sound.h
source/main/audio/SoundManager.cpp
source/main/audio/SoundManager.h
source/main/audio/SoundScriptManager.cpp
source/main/audio/SoundScriptManager.h
source/main/gfx/GfxScene.cpp
source/main/main.cpp
source/main/physics/Actor.cpp
source/main/physics/ActorSpawner.cpp
source/main/physics/ActorSpawner.h
source/main/physics/SimData.h
source/main/scripting/GameScript.cpp
source/main/scripting/GameScript.h
source/main/scripting/ScriptEngine.cpp
source/main/scripting/ScriptUtils.h
source/main/scripting/bindings/AngelScriptBindings.h
source/main/scripting/bindings/GameScriptAngelscript.cpp
source/main/scripting/bindings/SoundScriptAngelscript.cpp
source/main/terrain/TerrainObjectManager.cpp

The screenshot shows updated demo script bundled with the game. To run it, open console and say `loadscript demo_script.as`.
New objects: `SoundClass`, `SoundScriptTemplateClass`, `SoundScriptInstanceClass`
New enums: `SoundTrigger`, `ModulationSource`
The principal interface is in the `GameScriptClass` (global object `game`):
```
array<SoundScriptTemplateClass@>@ getAllSoundScriptTemplates()
SoundScriptTemplateClassPtr@ getSoundScriptTemplate(const string &in)
array<SoundScriptInstanceClass@>@ getAllSoundScriptInstances()
SoundClassPtr@ createSoundFromResource(const string &in filename, const string &in rg_name = string())
SoundScriptInstanceClassPtr@ createSoundScriptInstance(const string &in template, int actor_instance_id = -1)
```

Angelscript audio bindings

---

source/main/gameplay/RecoveryMode.cpp
source/main/physics/Actor.cpp
source/main/physics/Actor.h
source/main/physics/ActorManager.cpp
source/main/physics/ActorSpawner.cpp
source/main/resources/rig_def_fileformat/RigDef_Parser.cpp
source/main/resources/rig_def_fileformat/RigDef_Regexes.h

Fixes #3053
Reprint of code comments about `forset` parsing:
```
// --------------------------------------------------------------------------------------------
// BEWARE OF QUIRKS in the following code (they must be preserved for backwards compatibility):
// - a space between the 'forset' keyword and arguments is optional.
// - garbage characters anywhere on the line will silently add node 0 to the set. <<<========= THE NEW ONE!
// - a separator at the end of line will silently add node 0 to the set.
// --------------------------------------------------------------------------------------------
```

Fixed `forset` backwards compatibility

---

source/main/Application.h
source/main/ForwardDeclarations.h
source/main/gui/panels/GUI_MultiplayerSelector.cpp
source/main/gui/panels/GUI_MultiplayerSelector.h
source/main/gui/panels/GUI_RepositorySelector.cpp
source/main/gui/panels/GUI_RepositorySelector.h
source/main/gui/panels/GUI_TopMenubar.cpp
source/main/main.cpp
source/main/network/Network.h
source/main/scripting/GameScript.cpp

At one moment the server had a certificate expired and I realized the game doesn't log anything useful in that situation. The HTTP response code remains '0' in those cases.
Seeing all the copy-pasted and mostly identical `curl_easy*()` calls, I should probably create a helper for it, but at the moment I just uniformly extended all the occurences with an error logging code.

Always log CURL error string

---

source/main/Application.cpp
source/main/Application.h
source/main/CMakeLists.txt
source/main/GameContext.h
source/main/gameplay/RepairMode.cpp
source/main/gameplay/RepairMode.h
source/main/gui/GUIUtils.cpp
source/main/gui/GUIUtils.h
source/main/gui/panels/GUI_GameSettings.cpp
source/main/gui/panels/GUI_TopMenubar.cpp
source/main/gui/panels/GUI_TopMenubar.h
source/main/main.cpp
source/main/system/CVar.cpp
source/main/utils/InputEngine.cpp
source/main/utils/InputEngine.h

I renamed the feature because this is shorter and fits better in UIs and variable names. Hopefully it'll also fit better in player's vocabulary. Fixes #3062
**Changes:**
* new UI box "Live repair active" with optional display of hotkeys. It displays right under the top menubar (like existing "physics paused/terrain editor" boxes). See screenshot below.
* new input event EV_COMMON_LIVE_REPAIR_MODE (default Alt+Backspace) - throws you right into the LiveRepair mode, no need to wait.
* new cvar 'sim_live_repair_interval' (float) - default 2 sec - how long you must hold Backspace and be still before the LiveRepair mode kicks in. Used to be 1sec.
* new cvar 'ui_show_live_repair_controls' (bool) - controls the UI checkbox in "Live repair is active" statebox. Also configurable in GameSettings …

:video_game: Improved 'LiveRepair' (formerly 'interactive repair')

---

source/main/GameContext.cpp
source/main/gameplay/RepairMode.cpp
source/main/gfx/GfxActor.cpp
source/main/gfx/GfxActor.h
source/main/gui/panels/GUI_VehicleButtons.cpp
source/main/main.cpp
source/main/physics/Actor.cpp
source/main/physics/Actor.h
source/main/physics/ActorManager.cpp
source/main/physics/ActorManager.h
source/main/utils/memory/RefCountingObjectPtr.h

Fixed "physics paused" (default hotkey: End) not propagating to linked actors (i.e. trailers).

Fixed actor grouping

---

source/main/gfx/GfxActor.cpp
source/main/gfx/GfxActor.h
source/main/gfx/GfxData.h

This is only visual improvement - the engine shift time is not affected.
Applies to sources: shifterman1, shifterman2, shifterseq, shifterlin.
The transition speed is hardcoded at the moment - I'll try to use the 'shift time' parameter from 'engoption'. UPDATE: I'll leave it as-is for now.
Tested on Ford Mustang https://forum.rigsofrods.org/resources/ford-mustang-1979-1982.712/ - I'm sure PoLi would approve :)

'add_animation' - shift stick now moves smoothly

---

source/main/GameContext.cpp

Broken in https://github.com/RigsOfRods/rigs-of-rods/commit/3111ec97917d6c7eea461d6873687701f6cdb8b2 - adding linked actors to the worklist accidentally overwrites the player actor.

Fix #3079 - Minimap teleport doesn't work if in vehicle

---

source/main/physics/Actor.cpp
source/main/physics/Actor.h
source/main/physics/collision/Collisions.cpp

Fixed #3058 - caused by 539a1b24f50bad880611f245c76b634dbde1ad84
Solution: instead of considering the whole bounding box when evaluating eventboxes, only consider a bounding box around collision cab nodes. It makes more sense physically and also eliminates surprises, as loose cab nodes would be easily visible.

Fixed huge FPS drop when nodes move far away from vehicle

---

resources/scripts/AI.as
source/main/GameContext.cpp
source/main/gameplay/VehicleAI.cpp
source/main/gameplay/VehicleAI.h
source/main/gui/panels/GUI_SurveyMap.cpp
source/main/gui/panels/GUI_SurveyMap.h
source/main/gui/panels/GUI_TopMenubar.cpp
source/main/gui/panels/GUI_TopMenubar.h
source/main/main.cpp
source/main/scripting/GameScript.cpp
source/main/scripting/GameScript.h
source/main/scripting/bindings/GameScriptAngelscript.cpp

- Custom per waypoint speed can be now defined in UI or the json file. Values >= 5 km/h are respected, -1 system default, can be skipped in json.
- Recorder records the speed
- Exporter exports the speed
Code changes:
- Moved vector `ai_waypoints` to `GUI_TopMenubar` so now all `ai_*` vars are in one place and made it a struct
- `std::map<int, float> waypoint_speed` changed type from `int` to `Ogre::String` (way0, way1 ...) so custom speeds are correctly aligned in all repeat times

AI: Per waypoint speed

---

doc/angelscript/Game2Script/script_callbacks.h
source/main/scripting/GameScript.cpp
source/main/scripting/ScriptEngine.cpp
source/main/scripting/ScriptEngine.h
source/main/terrain/Terrain.cpp

One point for @Xploder98 in a friendly Devs vs. Users match :)
Long story short, Xploder mixed up callbacks and the game obligued which resulted in script failure with error asCONTEXT_NOT_PREPARED. This hapenned because our callback system is very confusing:
* we have a legacy "script handler" mechanic in .TOBJ file and classic `game.spawnObject()`, where you pass a function name and it gets invoked on eventbox collision.
* we also have recently introduced `SE_EVENTBOX_ENTER` and `SE_EVENTBOX_EXIT` which work with the classic event callback mechanism `eventCallback()` (and the extended `eventCallbackEx()` version) - it does the same job and even provides some extra data. This works independently of the "script handler" mecahnic described above - you just do …

:angel: Script: Log meaningful error upon callback mixup.

---

CMakeLists.txt
conanfile.py

Now RoR is buildable on Windows in the RelWithDebInfo config without needing to build the deps in RelWithDebInfo
Also moved the files generated by Conan to the `generators` folder so it no longer clutters up the build folder

:bug: Fixed build failing when building RelWithDebInfo && 🔧 Move conan generated files to a subfolder

---

source/main/Application.cpp
source/main/Application.h
source/main/gui/panels/GUI_GameSettings.cpp
source/main/gui/panels/GUI_VehicleButtons.cpp
source/main/system/AppConfig.cpp
source/main/system/CVar.cpp

For those who find the vehicle buttons menu not useful and/or intrusive, this adds "Show vehicle buttons menu" (CVar `ui_show_vehicle_buttons`) to Settings -> Gameplay:
Note: I had to add `WriteVarsHelper(f, "GUI", "ui_");` to `AppConfig.cpp`, otherwise any `ui_` CVar wouldn't get saved to `RoR.cfg`.

Added setting to hide vehicle buttons menu

---

conanfile.py
source/main/scripting/ScriptEngine.cpp

:arrow_up: Updated conan dependencies

---

source/main/physics/flex/FlexMeshWheel.cpp
source/main/physics/flex/FlexMeshWheel.h
source/main/terrain/SurveyMapEntity.h
source/main/terrain/Terrain.cpp
source/main/terrain/TerrainObjectManager.cpp

Lately gcc complains:
```
[ 41%] Building CXX object source/main/CMakeFiles/RoR.dir/physics/flex/FlexMeshWheel.cpp.o
/home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/flex/FlexMeshWheel.cpp: In constructor ‘RoR::FlexMeshWheel::FlexMeshWheel(Ogre::Entity*, RoR::GfxActor*, int, int, int, int, const std::string&, const std::string&, float, bool)’:
/home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/flex/FlexMeshWheel.cpp:86:38: warning: argument 1 value ‘1844674407370955155 ’ exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
86 |     m_indices=(unsigned short*)malloc(m_index_count*sizeof(unsigned short));
|                                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from …
```

Fixed gcc warning

---

source/main/gui/panels/GUI_TopMenubar.cpp

`special_text_centering_weight` added in https://github.com/RigsOfRods/rigs-of-rods/commit/83c1d273ef6dd5e3e057961191dba2bda8e670cf is only for centering live/quick repair special box text
alternatively it could be
```
ImGui::SetCursorPosX(ImGui::GetCursorPosX() + ((content_width / 2) - (text_w / 2)) * special_text_centering_weight);
```
and update `special_text_centering_weight` accordingly -> CBA

Fixed special box text position

---

resources/skeleton/config/Bluetooth_LE_XINPUT_compatible_input_device.map
resources/skeleton/config/Bluetooth_XINPUT_compatible_input_device.map
resources/skeleton/config/Controller__Afterglow_Gamepad_for_Xbox_360_.map
resources/skeleton/config/Controller__XBOX_360_For_Windows_.map
resources/skeleton/config/Controller__Xbox_360_Wireless_Receiver_for_Windows_.map
resources/skeleton/config/Controller__Xbox_One_For_Windows_.map
resources/skeleton/config/Logitech_G27_Racing_Wheel_USB.map
resources/skeleton/config/Logitech_G29_Driving_Force_Racing_Wheel_USB.map
resources/skeleton/config/Microsoft_X_Box_360_pad.map
resources/skeleton/config/Microsoft_X_Box_360_pad_0.map
resources/skeleton/config/Saitek_ST290_Pro.map
resources/skeleton/config/Sony_PLAYSTATION_R_3_Controller.map
resources/skeleton/config/Xbox_360_Wireless_Receiver.linux.map
resources/skeleton/config/input.map

Introduced by me in https://github.com/RigsOfRods/rigs-of-rods/commit/d7474e5cf4f6982e305143a333a782d090fcdb0b
`COMMON_TOGGLE_TRUCK_LIGHTS` was replaced with `COMMON_CYCLE_TRUCK_LIGHTS`, the correct event name is actually `COMMON_TOGGLE_TRUCK_LOW_BEAMS`. This caused lights to toggle in unexpected ways. 
Thanks @MarkROR for bringing this to my attention.

Fixed light toggle behavior

---

source/main/gfx/GfxActor.cpp
source/main/gfx/GfxActor.h
source/main/gfx/SimBuffers.h
source/main/physics/Actor.cpp
source/main/physics/Actor.h
source/main/physics/ActorSpawner.cpp

This allows modder to specify how much (if at all) the shifter anims should be smoothed. Default is 0.4sec. Use 0.0sec to disable.
Useful for the ThomasHDX bus which uses the shifter anim for dashboard digits.

:truck: new 'guisettings' entry 'shifterAnimTime' (seconds)

---

source/main/gui/panels/GUI_TopMenubar.cpp

The hotkeys in orange rectangle now display correctly.

Fixed skeletonview hotkeys in TopMenubar/Tools

---

source/main/gfx/SurveyMapTextureCreator.cpp

Fixes survey map on tall terrains such as [Tuanga Challenge](https://forum.rigsofrods.org/resources/tuanga-challenge.296/) and [Eagles Peak](https://forum.rigsofrods.org/resources/eagles-peak.1053/).
Before:
After:
Doesn't appear to introduce issues with other maps.

Fixed survey map on tall terrains

---

source/main/Application.cpp
source/main/Application.h
source/main/gfx/camera/CameraManager.cpp
source/main/gui/panels/GUI_GameSettings.cpp
source/main/system/CVar.cpp

This adds an "Invert orbit camera" (CVar `io_invert_orbitcam`)  option to Controls settings, inverting mouse and numpad controls. 
In addition, mouse cursor now hides when moving the camera. Also wanted to make the cursor auto hide after a few seconds of inactivity like in previous RoR versions, which apparently broke with the switch to the DearIMGUI-based cursor. Code for this seems to exist but doesn't appear to work correctly: https://github.com/RigsOfRods/rigs-of-rods/blob/26411c1a86ae807a3c6eef504259276baee26f22/source/main/gui/GUIManager.cpp#L294-L300
Moving this code to `CameraManager` causes the mouse to become permanently hidden. 
Old code:
https://github.com/ohlidalp/ror-legacy-svn-trunk/blob/0a55a993899d6a06cdc58fd98b5b675b371eb89a/source/main/gui/GUIManager.cpp#L142C1-L147C3

Added option to invert orbit camera controls

---

source/main/gameplay/EngineSim.cpp

These input events now work in "Manual Shift - Auto Clutch" mode:
```
TRUCK_SHIFT_GEAR_REVERSE  - shift directly to reverse gear
TRUCK_SHIFT_GEAR01        - shift directly to first gear
TRUCK_SHIFT_GEAR02        - shift directly to second gear
TRUCK_SHIFT_GEAR03        - shift directly to third gear
TRUCK_SHIFT_GEAR04        - shift directly to fourth gear
TRUCK_SHIFT_GEAR05        - shift directly to 5th gear
TRUCK_SHIFT_GEAR06        - shift directly to 6th gear
TRUCK_SHIFT_GEAR07        - shift directly to 7th gear
TRUCK_SHIFT_GEAR08        - shift directly to 8th gear
TRUCK_SHIFT_GEAR09        - shift directly to 9th gear
TRUCK_SHIFT_GEAR10        - shift directly to 10th gear
TRUCK_SHIFT_GEAR11        - shift directly to 11th gear
TRUCK_SHIFT_GEAR12        - shift directly to 12th …
```

Enabled direct shifting in "manual shift, auto clutch" mode

---

source/main/Application.h
source/main/GameContext.cpp
source/main/physics/ActorManager.cpp
source/main/physics/ActorSpawner.cpp
source/main/physics/ActorSpawner.h
source/main/resources/CacheSystem.cpp
source/main/resources/CacheSystem.h
source/main/resources/ContentManager.cpp
source/main/resources/rig_def_fileformat/RigDef_File.h
source/main/resources/rig_def_fileformat/RigDef_Parser.cpp
source/main/resources/rig_def_fileformat/RigDef_Parser.h
source/main/resources/rig_def_fileformat/RigDef_Regexes.h
source/main/resources/terrn2_fileformat/Terrn2FileFormat.cpp
source/main/resources/terrn2_fileformat/Terrn2FileFormat.h
source/main/terrain/TerrainObjectManager.cpp
source/main/terrain/TerrainObjectManager.h

Quick 2hr draft - ~BUILDS, NOT TESTED.~ Tested, added example mods.
A new file type "*.assetpack" was added to modcache with all the usual treatment:
- the file is recorded to the cache file (/cache/cache.json),
- it's searchable and selectable via UI (`LT_AssetPack`)
- can have a thumbnail (filename format '{}-mini.*'' where {} is the assetpack file name without extension)
- The file itself can be empty, recognized entries are `assetpack_name` (display name), `assetpack_description` (for display in selector UI) and `assetpack_author` (same syntax as in  .truck file).
- When requested, the game loads the entire containing ZIP/directory (called 'bundle' by jargon).
Assetpacks are referenced by the file name (standard approach) and can be used for both terrains and actors:
- Terrains: in …

New mod type: asset pack (.assetpack)

---

source/main/resources/tobj_fileformat/TObjFileFormat.cpp
source/main/resources/tobj_fileformat/TObjFileFormat.h

This fixes for me road roll angles.
Like you said, they were bad. Yaw was only working ok.
Before:
After:
Track has this road TestC1-Circle-road.tobj, it has a circle with all points: -16, yaw, 0
[TestC1-Circle-road.txt](https://github.com/RigsOfRods/rigs-of-rods/files/14377134/TestC1-Circle-road.txt)
This would be important for SR tracks roads, mainly for better bridge entries.

Add rot_yxz for SR road rotations Y then X, Z

---

source/main/gui/panels/GUI_TopMenubar.cpp
source/main/gui/panels/GUI_TopMenubar.h
source/main/main.cpp
source/main/resources/terrn2_fileformat/Terrn2FileFormat.cpp
source/main/resources/terrn2_fileformat/Terrn2FileFormat.h
source/main/terrain/Terrain.cpp
source/main/terrain/Terrain.h

This makes it possible to include a waypoints (JSON) file with a terrain. The file can have any name and must be listed in the .terrn2 file under [AI Presets] section, for example:
```
[AI Presets]
f1track_09wip_waypoints.json=
```
The format of the JSON file is the same as 'waypoints.json' downloaded from github repo https://github.com/RigsOfRods-Community/ai-waypoints. The game will check if the format is about right.
Tutorial on creating the presets: https://docs.rigsofrods.org/gameplay/vehicle-ai/#creating-waypoint-presets

Added `[AI Presets]` section to terrn2 file format

---

source/main/physics/Actor.cpp
source/main/physics/Actor.h
source/main/physics/collision/Collisions.cpp

Fixes #3121
Fixes #3097
This partially reverts d4ec0a0a1db975574938b176d0f16b9b067ce4d7
* the "is a cabnode" node filter condition was dropped, see `Actor::UpdateBoundingBoxes()`.
* The `ar_cabnodes_bounding_box` got renamed to `ar_evboxes_bounding_box`.

Fixed cars without coll. cabs not activating eventboxes (i.e. race checkpoints)

---

source/main/AppContext.cpp
source/main/Application.cpp
source/main/Application.h
source/main/gui/panels/GUI_GameSettings.cpp
source/main/system/CVar.cpp

Adds `Allow game window resizing` to diagnostic settings. Useful for taking ultrawide or 4:3 screenshots.

Added option to enable window resizing

---

doc/angelscript/Script2Game/BeamClass.h
doc/angelscript/Script2Game/GameScriptClass.h
resources/scripts/example_ImGui_nodeHighlight.as
source/main/physics/Actor.cpp
source/main/physics/Actor.h
source/main/scripting/bindings/ActorAngelscript.cpp

Showcases existing and new API to get node info.
**EXISTING:**
```
* actor.getNodeCount()
* actor.getWheelNodeCount()
* actor.getNodePosition(int nodenum)
```
**NEW:**
```
* actor.isNodeWheelRim(int nodenum)
* actor.isNodeWheelTire(int nodenum)
```

AngelScript: new script 'example_ImGui_nodeHighlight.as'

---

source/main/resources/addonpart_fileformat/AddonPartFileFormat.cpp

`unwanted_flexbodies` -> `unwanted_flares`. Caused `addonpart_unwanted_flare` to hide flexbodies instead.

:bug: Tuning: Fixed `addonpart_unwanted_flare` typo

---

source/main/AppContext.cpp
source/main/utils/ErrorUtils.cpp

To help diagnose #3141, I added extra logging of renderer config and startup.
* Displaying the fatal error dialog will now be logged to RoR.log - see file ErrorUtils.cpp.
* New entries in RoR.log - see file AppContext.cpp, function `SetUpRendering()`
```
00:56:19: [RoR|Startup|Rendering] Loading OGRE renderer plugins config 'C:\Users\Petr\builds\rigs-of-rods\bin\plugins_d.cfg'.
(...)
00:56:19: [RoR|Startup|Rendering] WARNING - invalid 'ogre.cfg', selecting render plugin manually...
00:56:19: [RoR|Startup|Rendering] Auto-selected renderer plugin 'Direct3D9 Rendering Subsystem'
00:56:19: [RoR|Startup|Rendering] Starting renderer 'Direct3D9 Rendering Subsystem' (without auto-creating render window)
(...)
00:56:19: [RoR|Startup|Rendering] Renderer options as reported by OGRE:
Allow DirectX9Ex …
```

Improved diag. logging on renderer startup.

---

source/main/ForwardDeclarations.h
source/main/gui/panels/GUI_VehicleDescription.cpp
source/main/physics/Actor.h
source/main/physics/ActorSpawner.cpp
source/main/physics/SimData.h

Fixes #193
Test mod: [Hughes 500D helicopter](https://forum.rigsofrods.org/resources/hughes-500d.196/)
The result - the controls are actually this weird by design, see my analysis below:
My analysis of the rig-def file:
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<---------------------- TRUCK DEF ----------------------------->  //// F keys (/84) --- Description, if any        <=== comparation with UI
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
commands
set_beam_defaults 12500000, 750, 18000000, 35000000
;fuel consumption engine kill
54,  46, 5.00, 1.000, 1.400, 39, 29, i …
```

Fixed #193 faulty/incomplete command keys on T-screen UI

---

doc/angelscript/Script2Game/globals.h
source/main/GameContext.cpp
source/main/gameplay/RepairMode.cpp
source/main/gameplay/SceneMouse.cpp
source/main/gameplay/ScriptEvents.h
source/main/gui/panels/GUI_VehicleButtons.cpp
source/main/main.cpp
source/main/physics/Actor.cpp
source/main/physics/Actor.h
source/main/physics/ActorForcesEuler.cpp
source/main/physics/ActorManager.cpp
source/main/physics/ActorManager.h
source/main/physics/Savegame.cpp
source/main/physics/SimData.h
source/main/scripting/bindings/ScriptEventsAngelscript.cpp
source/main/terrain/TerrainGeometryManager.cpp

Fixes https://github.com/RigsOfRods/rigs-of-rods/issues/3105.
This was quite an endeavor - it turned out there's no single spot to correctly reset the physics pausd state (or skeletonview state - related). While researching how to add it, I realized scripts may want to know when (un)linking of actors happens, so I added a script event `SE_GENERIC_TRUCK_LINKING_CHANGED` for it.
**What changed:** code changed signifficantly; all data remained the same - code handling hooks/ties/ropes/slidenodes got only cosmetic edits. There are many new sanity/integrity checks in the (un)linking logic which will trigger Asserts on Debug and just prevent damage on Release.
**What to test:** Operation of ties/hooks/ropes/slidenodes, including savegame and abrupt deleting of one of the actors.

Fixed paused actor physics resuming after switching to another actor

---

source/main/resources/CacheSystem.cpp

Fixes #3149
Problem was caused by myself in 74ed1083cb9e53e38096ec96b6a7b1f0b237ce01 - apart from fixing the bug, I also made a cosmetic edit of resource group names - Instead of it being 'bundle $FULLPATH', I made it '{bundle $LOCALPATH}'. But I botched the code, causing exception "invalid string position" to be thrown.
Solution: keep pretifying the resource group names, but account for all locations. I added a location-label to the name to avoid RG name clashes.
* prepackaged mods, i.e. {bundle BIN:\content\simple2-terrain.zip}
* extra mod path, i.e. {bundle EXTRA:\DI_SportsCar.zip}
* mod dirs under user profile, i.e. {bundle USER:\mods\vehicles\Desperado.zip}

Fixed mods not loading from `app_extra_mod_path`

---

source/main/gfx/GfxActor.cpp
source/main/physics/ActorSpawner.cpp

Fixes #3162
Problem introduced by myself in 965d250ff983f0b184698c2ac869f2df6381bb83 - I named beam scene nodes explicitly, but the scheme I used allowed for repetition in case beam visuals were created and then destroyed again during spawn. Unfortunately, for 'hooks' we don't know the visibility flags beforehand so we must always create visuals and then delete them if not desirable.
Changes:
- ActorSpawner.cpp - function `CreateBeamVisuals()` - generate name based on unique beam number instead of the visual count.
- GfxActor.cpp - function `RemoveBeam()` - properly dispose all OGRE objects when deleting beam visuals.

Fixed ties failing to appear if invisible hooks are present

---

doc/angelscript/Script2Game/globals.h
source/main/AppContext.cpp
source/main/Application.cpp
source/main/Application.h
source/main/gui/panels/GUI_GameSettings.cpp
source/main/gui/panels/GUI_GameSettings.h
source/main/main.cpp
source/main/scripting/bindings/MsgQueueAngelscript.cpp
source/main/utils/InputEngine.cpp

Looks up highest res in OGRE's available modes list, then applies.
RoR.log:
```
01:37:17: D3D9 : RenderSystem Option: Video Mode = 800 x 600 @ 32-bit colour
01:37:17: D3D9 : RenderSystem Option: Video Mode = 1024 x 768 @ 32-bit colour
01:37:17: D3D9 : RenderSystem Option: Video Mode = 1152 x 864 @ 32-bit colour
01:37:17: D3D9 : RenderSystem Option: Video Mode = 1280 x 960 @ 32-bit colour
01:37:17: D3D9 : RenderSystem Option: Video Mode = 1280 x 1024 @ 32-bit colour
01:37:17: D3D9 : RenderSystem Option: Video Mode = 1600 x 1024 @ 32-bit colour
01:37:17: D3D9 : RenderSystem Option: Video Mode = 1600 x 1200 @ 32-bit colour
01:37:17: D3D9 : RenderSystem Option: Video Mode = 1920 x 1200 @ 32-bit colour
01:37:17: D3D9 : RenderSystem Option: Video Mode = 1920 x 1440 @ 32-bit colour
01:37:17: …
```

Autodetect highest resolution on first run

---

source/main/gfx/GfxActor.cpp
source/main/gfx/GfxData.h
source/main/physics/ActorSpawner.cpp
source/main/resources/rig_def_fileformat/RigDef_File.h
source/main/resources/rig_def_fileformat/RigDef_Parser.cpp
source/main/utils/BitFlags.h

The `gear*` sources input 0 or 1 depending on the specific gear.
The `autoshifterlin` source works the same as `shifterlin` except it clamps forward gears to 1, so only has D/N/R positions. Fixes #2854
A test truck is attached - only the `gear*` flags are used though, I was lazy to test the shifter.
[propboard.zip](https://github.com/RigsOfRods/rigs-of-rods/files/12502071/propboard.zip)

:truck: New prop anim sources: `gearreverse`, `gearneutral`, `gear#`, `autoshifterlin`

---

source/main/physics/ActorSpawner.cpp
source/main/resources/addonpart_fileformat/AddonPartFileFormat.h

Hi guys,
good to see that RoR is still alive. :)
I'm trying to build RoR on Debian 12 with `gcc (Debian 12.2.0-14) 12.2.0`  but ran into some compiler errors.
This PR fixes some of them, however the following errors do still remain and I am unsure how to fix them:
```console
ninja | grep error
/home/deb/rigs-of-rods/source/main/scripting/bindings/OgreAngelscript.cpp:1647:86: error: invalid ‘static_cast’ from type ‘Ogre::SceneNode* (Ogre::SceneNode::*)() const’ to type ‘Ogre::SceneNode* (Ogre::SceneNode::*)()’
/home/deb/rigs-of-rods/source/main/scripting/bindings/OgreAngelscript.cpp:1648:90: error: invalid ‘static_cast’ from type ‘const Ogre::Vector3& (Ogre::SceneNode::*)() const’ {aka ‘const Ogre::Vector<3, float>& (Ogre::SceneNode::*)() const’} to type ‘const Ogre::Vector3& …
```

Fix building with gcc on Linux

---

source/main/gui/panels/GUI_CollisionsDebug.cpp
source/main/physics/ActorForcesEuler.cpp
source/main/physics/SimData.h
source/main/physics/collision/Collisions.cpp
source/main/resources/odef_fileformat/ODefFileFormat.cpp

Works the same like 'truck', but instead of registering collision from any node, only registers collision from wheel nodes (wheel tire node specifically, which for simpler wheel types is any node).
Requested by DannyWerewolf on Discord: https://discord.com/channels/136544456244461568/189904947649708032/1288229860359016612
See also documentation of the terrain object (.ODEF) file format: https://docs.rigsofrods.org/terrain-creation/object-format/
Attached is a test terrain (modified simple2) which I tested with.
[simple2-truck_wheels-test.zip](https://github.com/user-attachments/files/17157817/simple2-truck_wheels-test.zip)
**What needs testing:** eventboxes of all sorts - spawners, race checkpoints etc...

Terrain objects: new eventbox collision-filter type 'truck_wheels'

---

source/main/AppContext.cpp
source/main/gameplay/SceneMouse.cpp
source/main/gameplay/SceneMouse.h
source/main/gfx/camera/CameraManager.cpp
source/main/gfx/camera/CameraManager.h
source/main/gui/GUIManager.cpp
source/main/gui/OverlayWrapper.cpp
source/main/gui/OverlayWrapper.h
source/main/gui/imgui/OgreImGui.cpp
source/main/gui/imgui/OgreImGui.h
source/main/gui/panels/GUI_CollisionsDebug.cpp
source/main/gui/panels/GUI_FlexbodyDebug.cpp
source/main/gui/panels/GUI_FrictionSettings.cpp
source/main/gui/panels/GUI_GameControls.cpp
source/main/gui/panels/GUI_NodeBeamUtils.cpp
source/main/utils/InputEngine.cpp
source/main/utils/InputEngine.h

Fixes 2 nuissances reported by DannyWerewolf on Discord: https://discord.com/channels/136544456244461568/189904947649708032/1289311318536486982
1. **The new T-panel interferes with other windows** -> I made all optional windows appear in the middle of the screen instead of top left corner of screen. I also supressed it when pause menu is visible (on lower resolutions it may obstruct the menu).
2. **The mouse-grab glitch when you're in windowed mode and switch out and back in** -> this needed deeper dive, but I did it. Fixes #2468
**What needs testing:** The mouse grab, camera controls and airplane dashboard - these needed a small rework of mouse input handling.

Fixed rogue mouse-grab in windowed mode, after switching out & back in

---

source/main/gui/panels/GUI_VehicleInfoTPanel.cpp
source/main/gui/panels/GUI_VehicleInfoTPanel.h

These were originally present in the VehicleButtons pop-up panel. I made them narrow to fit into single row. Unlike other lines the icon isn't a button and the hotkey hint is also dummy (static text, not updated from key bindings)

T-Panel: restored custom-light buttons

---

external/header_only/half/ChangeLog.txt
external/header_only/half/LICENSE.txt
external/header_only/half/README.txt
external/header_only/half/half.hpp
source/main/network/Network.h
source/main/network/RoRnet.h
source/main/physics/Actor.cpp
source/main/physics/ActorManager.cpp

Fixes #2783
I replaced the Ulteq-invented `short int` compression format with a standard half-precision IEEE floats (using https://half.sourceforge.net/). Both are 2-byte formats so network traffic will remain the same.

Fixed multiplayer visual glitch with detached parts "teleporting" around the vehicle

---

source/main/GameContext.cpp
source/main/network/RoRnet.h
source/main/physics/Actor.cpp
source/main/physics/ActorManager.cpp
source/main/physics/ActorManager.h
source/main/physics/ActorSpawnerFlow.cpp
source/main/physics/Savegame.cpp
source/main/physics/SimData.h
source/main/resources/CacheSystem.cpp
source/main/resources/CacheSystem.h
source/main/terrain/TerrainObjectManager.cpp
source/main/utils/Utils.cpp
source/main/utils/Utils.h

Fixes #3166
**Problem1:** When spawning an actor, the cache entry was always looked up via truckfile name, even if it was already known from the Selector UI. This potentially caused mixups.
**Fix2:** Use the entry provided by Selector UI.
**Problem2**: in many scenarios, the game selects an actor by truckfile name alone:
*   savegames
*   preselected truck in RoR.cfg
*   preloaded trucks on terrain (.tobj)
*   Multiplayer spawn notifications
**Fix2**: introduce an optional "Bundle-qualified" syntax, i.e. "mybundle.zip:myactor.truck" (in case of ZIP archive) or "mysubdir:myproject.truck" (in case of subdir) and use it in all the above cases. Because it's optional, it doesn't need a version bump in savegame format or RoRnet protocol. Note that 'bundle' is RoR jargon for a ZIP archive or …

Avoid mixing up truckfiles when filename isn't unique.

---

source/main/physics/Actor.cpp
source/main/physics/Actor.h
source/main/physics/ActorManager.cpp
source/main/physics/ActorSpawner.cpp
source/main/physics/ActorSpawner.h
source/main/physics/ActorSpawnerFlow.cpp
source/main/resources/rig_def_fileformat/RigDef_File.cpp
source/main/resources/rig_def_fileformat/RigDef_File.h
source/main/resources/rig_def_fileformat/RigDef_Parser.cpp
source/main/resources/rig_def_fileformat/RigDef_Parser.h
source/main/resources/rig_def_fileformat/RigDef_Regexes.h

Prevents actor from importing flare states when linked (locked/tied).
Suggested on Discord by DarthCain:
* https://discord.com/channels/136544456244461568/189904947649708032/1313301325538136147 
* https://discord.com/channels/136544456244461568/189904947649708032/1313542914747662397
Syntax:
```
;flaregroups_no_import
;   <flaretype> <controlnumber 1-10>
```
Testing: There are 2 RoR.log messages specifically for testers (`{}` is where values are filled ) - these may be removed later:
* `[RoR|RigDef::Parser] parsed FlaregroupNoImport ({} {})`
* `[RoR|ActorSpawner] processing FlaregroupNoImport ({} {})`

:truck: New section 'flaregroups_no_import <type> <controlnumber>'

---

source/main/gameplay/EngineSim.cpp
source/main/utils/InputEngine.cpp
source/main/utils/InputEngine.h

Fixes #3179
No binding by default - intended for controllers.
@Goetterescu Please download test build from the "Checks" tab above - find it under the "Artifacts" dropdown (ror-win.ZIP)
UPDATE: [Direct download link (you must be signed in).](https://github.com/RigsOfRods/rigs-of-rods/suites/29292867066/artifacts/2023226078)

New input event `EV_TRUCK_CYCLE_GEAR_RANGES`

---

conanfile.py
source/main/ForwardDeclarations.h
source/main/audio/SoundScriptManager.cpp
source/main/audio/SoundScriptManager.h
source/main/gfx/DustPool.cpp
source/main/gfx/DustPool.h
source/main/gfx/GfxActor.cpp
source/main/gfx/GfxActor.h
source/main/gfx/GfxData.h
source/main/gfx/GfxScene.cpp
source/main/gfx/GfxScene.h
source/main/gfx/SimBuffers.h
source/main/gfx/hydrax/Hydrax.cpp
source/main/gfx/hydrax/MaterialManager.cpp
source/main/gfx/hydrax/MaterialManager.h
source/main/gui/panels/GUI_SurveyMap.h
source/main/gui/panels/GUI_TopMenubar.cpp
source/main/gui/panels/GUI_VehicleInfoTPanel.cpp
source/main/main.cpp
source/main/physics/Actor.cpp
source/main/physics/Actor.h
source/main/physics/ActorSpawner.cpp
source/main/physics/ActorSpawner.h
source/main/physics/Savegame.cpp
source/main/physics/SimData.h
source/main/physics/air/TurboJet.cpp
source/main/physics/air/TurboProp.cpp
source/main/terrain/TerrainObjectManager.cpp
source/main/terrain/TerrainObjectManager.h

While fixing #3169 I noticed beacons run when game is paused and also ignore simulation speed, always running at wall time. I remembered there are multiple other issues like this (props/water waves moving when paused) and I figured a way to tackle everything at once - I changed the time input for the entire scene update code (which is already consolidated into `GfxScene::UpdateScene()`) - instead of inputting wall time, I now input the adjusted simulation time, and I input zero if the game is paused or physics are globally paused.
The particles had a custom code to correctly calc. sim. time and skip the update entirely when paused. I reverted all that, expecting the adjusted time input to fix particles, but that didn't work - they don't use that input. I already researched this at #3138 …

Fixed GFX running on wall time instead of sim. time

---

source/main/physics/Actor.cpp
source/main/physics/ActorSpawner.cpp
source/main/physics/Savegame.cpp

Problem: The trains on Train Valley now continuously produce smoke until you activate them.
Fix: shut down the particle emitters when spawning (unified code with custom-particles)
UPDATE: Also fixed savegame issues that manifested on this terrain: https://discord.com/channels/136544456244461568/189904947649708032/1323326091313545300

:bug: Fixed exhausts on predefined actors.

---

source/main/Application.cpp
source/main/Application.h
source/main/gui/GUIManager.cpp
source/main/gui/GUIManager.h
source/main/gui/panels/GUI_GameSettings.cpp
source/main/gui/panels/GUI_GameSettings.h
source/main/gui/panels/GUI_TopMenubar.cpp
source/main/system/CVar.cpp

Since the game is a very loose sandbox, it's impossible to create an UI to satisfy everyone. But to make some space for debate and future enhancements, I've coined these 4 presets. 
**This is a prototype - the preset cvars and values are open for debate.**
Suggested on Discord: https://discord.com/channels/136544456244461568/189904947649708032/1128168306558390383
I added a whole new tab "UI" to the Settings panel: https://discord.com/channels/136544456244461568/189904947649708032/1128419817645424711
I took care to make it data-driven and intuitively readable in code, so that users can read it as reference and UI automatically reflects changes.

:video_game: UI Presets (Novice/Regular/Expert/Minimallist)

---

source/main/gui/panels/GUI_GameSettings.cpp
source/main/gui/panels/GUI_VehicleInfoTPanel.cpp

This PR:
- Restores displaying both mph and km/h (reverts c15069a5fddb8a928969fcf95916c409d362e1b3)
- Mass display now includes pounds
- `Imperial speedometer` under Settings -> Gameplay has been renamed to `Imperial units`. 
The mass/speed/power values are swapped depending on this setting:

Improved T-menu stats display

---

source/main/gui/panels/GUI_GameSettings.cpp

Removed the duplicate `Overview map icons` and `Declutter overview map` settings from the Graphics settings tab, these were moved to the new UI tab.

📐 Removed duplicate settings

---

source/main/Application.cpp
source/main/Application.h
source/main/gui/panels/GUI_GameSettings.cpp
source/main/resources/ContentManager.cpp
source/main/system/CVar.cpp
source/main/utils/MeshObject.cpp

The code for loading LODs got removed at some point

:bug: Fixed LODs not being loaded

---

source/main/gui/OverlayWrapper.cpp
source/main/gui/OverlayWrapper.h
source/main/gui/panels/GUI_GameChatBox.cpp
source/main/utils/InputEngine.cpp

Fixes #3216 - Airplane dashboard not reacting to mouse.
Fixed the chatbox obstructing bottom area of the aerial HUD, even if not open for input.
Fixed throttles sliders slipping off mouse cursor when you make a quicker move.
Additional goodie: I've added a mouse hover highlights to all elements which are interactable by mouse.

Aerial HUD fixes + new mouse-hover highlights

---

source/main/main.cpp

Turns out `UpdateMouseCursorVisibility` never got called lol.

🐛 Fixed mouse auto hiding

---

.gitignore
source/main/scripting/ScriptUtils.h
source/main/utils/memory/RefCountingObjectPtr.h

1. Make and build with clang on linux 18.04 LTS (other versions not tested)
2. Used build desciption for [Linux](https://github.com/RigsOfRods/rigs-of-rods/wiki/Compile-(Linux))
3. gitignore had to be exteded in order to get rid the hundreds of newly generated files in the git staging window.
Building should run without errors
Building fails
OS: Linux 18.04 LTS 64bit
Renderer used: OpenGL

:bug: nullptr type and missing include at compiling on Linux 18.04 LTS

---

source/main/gui/DashBoardManager.cpp
source/main/gui/DashBoardManager.h

Fixes #3230 
This removes intentionally placed update skips which were in the code since beginning of Git history (~11 years).
There is no impact on FPS (mind you, I run under Debug which is order of magnitude slower than usual), so that isn't the reason why those skips were placed. I noticed the dash inputs are jaggy at places, for example when auto-shifting the throttle goes to 0% and then back to 100% in a split second. I added some smoothing to make this look less like a glitch.

Fixed laggy dashboard HUD elements

---

doc/angelscript/Script2Game/BeamClass.h
resources/scripts/example_game_actorForceCinecam.as
source/main/ForwardDeclarations.h
source/main/gfx/camera/CameraManager.cpp
source/main/physics/Actor.cpp
source/main/physics/Actor.h
source/main/physics/ActorForcesEuler.cpp
source/main/scripting/bindings/ActorAngelscript.cpp

Quick doodle for DannyWerewolf on Discord. Allows scripts to force players to use specific cinecam in vehicle. May be useful for race scripts to avoid cheating or simplify passing obstacles where regular 3rd person camera doesn't work well.
See new example script 'example_game_actorForceCinecam.as' - screenshot below shows how to find it:
Reprint of the added doc:
```
/**
* Sets a forced cinecam for this actor; This disables camera hotkeys.
* @param cinecamId Cinecams are numbered from 0, use `getNumCinecams()`; -1 means no cinecam.
* @param flags Flags are reserved for future use.
*/
void setForcedCinecam(int cinecamId, int flags);
/**
* Resets the effect of `setForcedCinecam()`;
*/
void clearForcedCinecam();
/**
* Reports the values submitted by `setForcedCinecam()`;
* @param cinecamId …
```

👼Script: Added 'forced cinecam' state for actors

---

source/main/resources/tobj_fileformat/TObjFileFormat.cpp
source/main/terrain/TerrainEditor.h
source/main/terrain/TerrainObjectManager.cpp

Broken in 3b681f3 - the 'type' parameter from TOBJ file was given a default placeholder value "-" to export correctly, but surveymap expected empty string where icon wasn't desired.
Fixes #3221

Fixed excess icons on survey map

---

doc/angelscript/Script2Game/GenericDocumentClass.h
source/main/resources/CacheSystem.cpp
source/main/scripting/bindings/GenericFileFormatAngelscript.cpp
source/main/utils/GenericFileFormat.cpp
source/main/utils/GenericFileFormat.h

This reverts commit 00fbddd65faeb237c27f9b189a80be4f87305d09 "GenericFileFormat: new `OPTION_NAKEDSTR_USCORES_TO_SPACES`"
Reason: The majority of strings doesn't expect this transformation (i.e. filenames or identifiers) so this completely breaks i.e. addonpart file parsing.
Fixes #3251

Fixed GenericDocument incorrectly parsing filenames (" " vs "_" substitution)

---

doc/angelscript/Script2Game/globals.h
resources/gadgets/engine_tool.as
source/main/gameplay/ScriptEvents.h
source/main/physics/Actor.cpp
source/main/scripting/bindings/ScriptEventsAngelscript.cpp

Reported by [Mike](https://discord.com/channels/136544456244461568/189904947649708032/1343333206069477426) on Discord, upvoted by DannyWerewolf.
Changes:
* When any script uses `setSimAttribute()`, game sends script event `SE_ANGELSCRIPT_MANIPULATIONS` which aborts the  current race.
* When in multiplayer, `setSimAttribute()` logs a warning to console ( appears on screen in the chatbox area) and does nothing.

Prevent cheating via `ActorSimAttr` system (used by engine_tool gadget)

---

.gitignore

Added in https://github.com/RigsOfRods/rigs-of-rods/commit/d9d7f69663df91b126e772454cf2f210c56170b4, prevented the creation of new files in the `source` directory.

Removed "Source"  from .gitignore

---

source/main/gfx/GfxActor.cpp
source/main/physics/ActorSpawner.cpp
source/main/physics/ActorSpawner.h
source/main/physics/ActorSpawnerFlow.cpp

Fixes #3260 
Causes rotation/flickering issues with flare light sources and mirrors.

Revert "GfxActor: fixed OGRE 'deprecated' non-node transforms"

---

source/main/gui/panels/GUI_FlexbodyDebug.cpp
source/main/gui/panels/GUI_FlexbodyDebug.h
source/main/physics/ActorSpawner.cpp
source/main/physics/flex/FlexBody.cpp
source/main/physics/flex/FlexBody.h
source/main/physics/flex/FlexFactory.cpp
source/main/physics/flex/FlexFactory.h
source/main/physics/flex/Locator_t.h
source/main/resources/rig_def_fileformat/RigDef_File.h
source/main/resources/rig_def_fileformat/RigDef_Parser.cpp
source/main/resources/rig_def_fileformat/RigDef_Parser.h
source/main/resources/rig_def_fileformat/RigDef_Regexes.h

This directive affects the previously defined flexbody, like 'forset' does, and manually overrides node bindings for single vertex. The rest of the processing works the same as forset: the game calculates the offset between the nodes and the vertex and maintains it. You can override as many verts as you like, and the nodes used don't need to be in the forset.
Example - Ranges are supported! you can specify any number of verts, the 'verts:' intermezzo is mandatory!:
```
31, 27, 73, -0.0875, 0.5, 0.5, 0, 0, 0, Box69CamaroHood.mesh
forset 11-13, 36, 48-51, 74
; forvert <ref node> <x node> <y node> <vertex number>
forvert 25, 0, 2, verts: 70-71, 28
```
This will be logged to RoR.log:
```
09:36:28: FLEXBODY vertex 70 overriden for nodes REF:25, VX:0, VY:2
09:36:28: FLEXBODY vertex 71 overriden …
```

:truck: New directive 'forvert' (flexbody forset override)

---

conanfile.py

Fixes #3242. The newer version includes [this grass "fix"](https://github.com/RigsOfRods/ogre-pagedgeometry/pull/15) which doesn't actually address that issue.

◀️ Reverted PagedGeo to 1.2.0

---

source/main/resources/addonpart_fileformat/AddonPartFileFormat.cpp

Flare offset Z is actually auto-imported as `1`: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/resources/rig_def_fileformat/RigDef_File.h#L883

:books: Fixed flare comment typo

---

source/main/audio/SoundManager.cpp

While working on the HALFBEAM_ freeforces, I entered an actor with commands and bumped into an assert:
The code hitting this was introduced in https://github.com/RigsOfRods/rigs-of-rods/pull/3182. While it's technically no big deal (locking a mostly unlocked mutex), it's something I have an opinion about, hence why I added the assert.
Thread never really needs to manipulate the refcount, it can always just create a reference (`ActorPtr& myref`) or use `ActorInstanceID_t` to refer to the actor. Doing otherwise IMO hints at bad design, like in this case - the obstruction/occlusion check is done directly from physics thread `CalcCommands()`. While it's completely legit to do OpenAL calls from any thread (audio is a threaded thing by nature), our additional logic shouldn't be invoked ad-hoc …

Hotfix - don't update ActorPtr refcount from a thread.

---

source/main/physics/ActorSpawner.cpp
source/main/physics/ActorSpawner.h

When introducing the `ar_nodes_override_loadweights` array needed for NBUtil tuning/export, I correctly assigned values from nodes with 'l' flag but forgot to assign values from 'set_node_defaults' too.
Fixes https://github.com/RigsOfRods/rigs-of-rods/issues/3298

Hotfix: mishandled `set_node_defaults` weight override

---

source/main/gui/panels/GUI_GameSettings.cpp
source/main/gui/panels/GUI_TopMenubar.cpp
source/main/system/AppConfig.cpp

This lowers the max reflection update rate setting from 6 to 2. High reflection update rate values greatly impact performance, players often max out this setting and ask why their game now runs poorly. The setting doesn't improve reflection quality, only how fast the envmap updates.

 Lowered max reflection update rate setting

---

source/main/physics/Actor.cpp

Bug introduced in 3de983a33879c1e0ae46f229c45d4ce85048c1ed where custom unhooking code was removed in favor of using existing `hookToggle()` function, which was however made for unhooking via user input (= you want the relock timer to restart). This commit extends the function to recognize hard-reset and adjust the timer accordingly (= attempt relocking immediatelly).

Fixed autolocking hooks not relocking on reset

---

source/main/physics/ActorSpawner.cpp
source/main/resources/rig_def_fileformat/RigDef_File.h
source/main/resources/rig_def_fileformat/RigDef_Parser.cpp

Reintroduces `_is_plastic_deform_coef_user_defined`, fixes vehicles like the DI Sportster and Ford Windstar melting at spawn.

🐛 Fixed melting vehicles

---

source/main/physics/ActorSpawner.h
source/main/physics/ActorSpawnerFlow.cpp

Fixes #3307
It indeed did check for engine, but only if it's `outside section/end_section` and for that offending mod it isn't.

Fixed airplane beacons generated on a car wing.

---

source/main/physics/ActorManager.cpp

Fixes #3336
Originally Introduced in #3171

Disabled "bundle-qualified" (including ZIP/dir name) mod lookup for multiplayer.
