RigsOfRods/rigs-of-rods

source/main/main_sim/MainThread.cpp, source/main/physics/BeamData.h, source/main/physics/input_output/RigSpawner.cpp
=> Linux fixes

source/main/terrain/TerrainManager.cpp
Fixed gravity setting not affected in the terrn2 config file.
=> [Fix] Terrain gravity setting now working

source/main/gfx/Water.cpp
Title says it all, an other bug fixed!
=> [Fix] setWaterHeight no more makes water disappear

source/main/gfx/Water.cpp, source/main/gfx/Water.h, source/main/gui/Console.cpp, source/main/terrain/TerrainManager.cpp
Also fixed the bug when changing from terrain didn't make the water
level right.
Added "/setwaterlevel" function to the console also.
=> [Fix] Fixed AngelScript Water level function

source/main/gui/GUIManager.cpp, source/main/gui/panels/GUI_RigSpawnerReportWindow.cpp, source/main/gui/panels/GUI_SimUtils.cpp, source/main/gui/panels/GUI_SimUtils.h, source/main/physics/Beam.cpp
Fixed a little crash when a notification is pushed while the SimUtils pointer is destroyed and added colored text to the RigSpawnerReport
=> Progress on GUIOverhaul

bin/resources/mygui/Chatbox.layout, source/main/gameplay/ChatSystem.cpp, source/main/gameplay/RoRFrameListener.cpp, source/main/gui/GUIManager.cpp, source/main/gui/GUIManager.h, source/main/gui/panels/GUI_GameChatBox.cpp, source/main/gui/panels/GUI_GameChatBox.h, source/main/gui/panels/GUI_GameChatBoxLayout.h, source/main/main_sim/MainThread.cpp
It's working as intended for the moment.
=> [Add] First work on ChatBox (Mostly done)

source/main/gfx/Water.cpp, source/main/main_sim/MainThread.cpp
https://github.com/RigsOfRods/rigs-of-rods/issues/74
=> A little fix for a BackToMenu crash

source/main/gfx/HydraxWater.cpp, source/main/gfx/HydraxWater.h, source/main/gfx/hydrax/Hydrax.cpp
Improved the translation between underwater and normal camera rendering
(smoother) and started cleaning the HydraxWater class
=> [Add] Some Hydrax Improvments

source/configurator/icon.rc, source/main/RoRVersion.h, source/main/gameplay/RoRFrameListener.cpp, source/main/gfx/OgreSubsystem.cpp, source/main/main_sim/icon.rc, source/main/main_sim/main.cpp, source/main/network/IRCWrapper.cpp, source/main/scripting/GameScript.cpp
As said here: https://github.com/RigsOfRods/rigs-of-rods/issues/112
Will not merge until you guys agree.
=> Increased version to 0.4.5 and added the -dev tag

source/main/physics/ApproxMath.h, source/main/physics/flex/FlexBody.cpp
It seems like it's even better than 0.4.0.7
Also Issue #16 is fixed (thanks to only_a_ptr) but I fixed the 0.4.0.7
code rather than reverting to 0.38
=> [CodeChange] Improved Flexbodies performances

source/main/physics/flex/FlexFactory.cpp, source/main/physics/flex/FlexFactory.h, source/rig_file_input_output/RigDef_Regexes.h
- Flexbody cache crash on Auriga
- Vehicle [Martin T64S Custom] meltdown
=> Closes 2 issue tickets

source/main/physics/BeamData.h, source/main/physics/BeamForcesEuler.cpp, source/main/physics/input_output/RigSpawner.cpp
Might fix a whole bunch of issues.
=> Critical fix of triggers/shocks

CMakeDependenciesConfig.txt, CMakeMacros.txt, source/main/CMakeLists.txt, source/main/gfx/OgreSubsystem.cpp, source/main/gui/GUIManager.cpp, source/main/gui/GUIManager.h, source/main/main_sim/MainThread.cpp, source/main/physics/Beam.cpp, source/main/resources/ContentManager.cpp
new deps will be uploaded soon.
=> [Fix] Fixed MyGUI also fixed CMake under windows

source/main/gui/panels/GUI_MainSelector.cpp
This alphabetically sorts maps and vehicules categories and entries.
It leaves "All" and "Fresh" categories at the top of the list.
=> Alphabetically Sort menu's categories and entries.

source/main/physics/collision/PointColDetector.cpp
* Replaced goto with infinite loops.
* Fixed coding style.
=> [Fix] Cleanup PointColDetector.cpp

AUTHORS.md, source/main/gui/panels/GUI_GameAbout.cpp
* Added myself to the list;
* Full names in credits window
=> Credits update

bin/resources/dashboards/default_dashboard3500.layout, bin/resources/dashboards/default_dashboard3500_mph.layout, bin/resources/dashboards/default_dashboard7000.layout, bin/resources/dashboards/default_dashboard7000_mph.layout
Corrected needle and Turbo gauge position, reduced dashboard3500 to same size as dashboard7000.
=> dashboard corrections

README.md, source/main/gui/Console.cpp, source/main/gui/GUIFriction.cpp, source/main/gui/GUIMenu.cpp, source/main/main_sim/MainThread.cpp, source/main/utils/ErrorUtils.cpp, source/main/utils/Language.h, tools/linux/l10n/extract_pot.sh, tools/linux/l10n/from_transifex.sh, tools/linux/l10n/merge_old_translations.sh, tools/linux/l10n/setup_transifex.sh, tools/linux/l10n/to_transifex.sh
- Improved some source strings for translations
- added shell scripts to help with l10n and Transifex
=> Localization - polishment and helper scripts

source/main/physics/input_output/RigSpawner.cpp
Fusedrag+autocalc fixed.
Sloppy /me dropped a few lines while refactoring...
=> Monday's fix.

source/main/datatypes/rig_t.h, source/main/gameplay/RoRFrameListener.cpp, source/main/gfx/PreviewRenderer.cpp, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/BeamForcesEuler.cpp, source/main/physics/input_output/RigSpawner.cpp, source/main/physics/input_output/RigSpawner.h, source/main/physics/input_output/RigSpawner_ProcessControl.cpp, source/main/scripting/ScriptEngine.cpp
* Removed the deprecated skeleton view mode (```skeleton == 1```)
* Removed ```fadeDist``` and ```skeleton_beam_diameter``` from rig_t
=> [Cleanup] Skeleton view

source/main/physics/Beam.cpp
=> [Bugfix] Removes an infinite loop in the syncReset function.

source/main/gui/panels/GUI_SimUtils.cpp
=> [Bugfix] Hides altitude label in truck info for non airplanes

source/main/physics/input_output/RigSpawner.cpp
=> [Bugfix] Wheel axes orientation no longer depends on the spawn rotation.

bin/resources/dashboards/MyGUI_FontsDash.xml, bin/resources/mygui/MapControl.layout, bin/resources/mygui/MapEntity.layout, bin/resources/mygui/MyGUI_FontsEnglish.xml, bin/resources/mygui/PauseMenu.layout
These ones.
```xlm
|  Core  |  Warning  |  ResourceTrueTypeFont: Property 'SpaceWidth' in font 'Default' is deprecated; remove it to use automatic calculation.  |  C:\data\codehg\dependencies\src\MyGUI\mygui-trunk-r4359\MyGUIEngine\src\MyGUI_ResourceTrueTypeFont.cpp  |  206
|  Core  |  Warning  |  ResourceTrueTypeFont: Property 'CursorWidth' in font 'Default' is deprecated; value ignored.  |  C:\data\codehg\dependencies\src\MyGUI\mygui-trunk-r4359\MyGUIEngine\src\MyGUI_ResourceTrueTypeFont.cpp  |  212
|  Core  |  Warning  |  ResourceTrueTypeFont: Property 'Distance' in font 'Default' is deprecated; value ignored.  |  C:\data\codehg\dependencies\src\MyGUI\mygui-trunk-r4359\MyGUIEngine\src\MyGUI_ResourceTrueTypeFont.cpp  |  212
|  Core  |  Warning  |  ResourceTrueTypeFont: Property …
```
=> MyGUI Fixed some warnings

source/main/physics/Beam.cpp
=> [Bugfix] Prevents boats from spawning underwater (#147)

source/main/physics/Beam.cpp
=> [Bugfix] Fixes the engine check light behaviour

source/rig_file_input_output/RigDef_Parser.cpp
=> [Bugfix] Ties with option 'n' are no longer invisible

source/main/physics/input_output/RigSpawner.cpp
=> [Bugfix] Fixes add_animation source 'shifterlin' (#488)

source/rig_file_input_output/RigDef_Parser.cpp, source/rig_file_input_output/RigDef_Regexes.h
resolveEventName() failed due to leading whitespace in the event name
RoR.log: RigSpawner: ERROR (Keyword props) Unknown animation event: command_02
Fixes #132
=> [Bugfix] Fixes add animation parsing (#132)

source/main/physics/input_output/RigSpawner.cpp
Fixes #333 (after https://github.com/RigsOfRods/rigs-of-rods/pull/571 is merged)
Might also fix #394
=> [Bugfix] Fixes the trigger limit parsing on command-style triggers

source/main/gfx/camera/CameraBehaviorFixed.cpp
=> [Bugfix] Brings back the 'Fixed camera' GUI notification

source/main/gameplay/RoRFrameListener.cpp
Fixes #359 (aside from the Audi Quadro flexmesh issue)
The broken flexmeshes are a different issue.
=> [Bugfix] Fixes the reload vehicle feature for most trucks

source/main/physics/input_output/RigSpawner.cpp
Implements this: https://github.com/RigsOfRods/rigs-of-rods/issues/442#issuecomment-153393226
Fixes #442
=> [Bugfix] Fixes shock stability active suspension for right side

source/main/gameplay/RoRFrameListener.cpp, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/BeamFactory.cpp, source/main/physics/BeamFactory.h
20% more FPS with a single TATRA T813 DAKAR
=> [Codechange] Detached the flexbody update routine from updateVisual

source/main/physics/collision/PointColDetector.cpp
From here: https://github.com/only-a-ptr/rigs-of-rods/commit/1015790b32b6d15aa95addeeb73ca0d2a7ba9464
=> [Codechange] Fixes a signed/unsigned mismatch

source/main/physics/BeamForcesEuler.cpp
Leads to earlier activation of (soon to collide with) trucks
=> [Codechange] Less restrained bounding box prediction

source/main/main_sim/MainThread.cpp
=> [Bugfix] Fixes the friction setting menu

source/main/gameplay/BeamEngine.cpp, source/main/gameplay/BeamEngine.h, source/main/physics/Beam.cpp, source/main/physics/input_output/RigSpawner.cpp
Fixes #428
Fixes #392 
@Speciesx, @negativeice, needs to be tested.
=> [Bugfix] Recovered the old turbo mode

source/main/gameplay/RoRFrameListener.cpp
Made use of the Round function in the Utils.cpp
https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/utils/Utils.cpp#L319
Should fix: #634
=> [Bugfix] Fixes calling toString(double) being called on Ogre 1.8

source/main/physics/collision/Collisions.cpp
=> [Bugfix] Fixes event cache not being cleared on exit

bin/resources/skeleton/config/input.map, source/main/gameplay/LandVehicleSimulation.cpp, source/main/utils/InputEngine.cpp, source/main/utils/InputEngine.h
=> [Feature] Added keyboard modifiers for partial throttle / brake input

source/main/resources/CacheSystem.cpp
=> jpg preview picture support

source/main/physics/input_output/RigSpawner.cpp, source/rig_file_input_output/RigDef_Parser.cpp, source/rig_file_input_output/RigDef_Parser.h
Fixes broken camerarail on Henschel train.
=> [Bugfix] Force parser to commit unfinished sections right before end

source/main/gameplay/BeamEngine.cpp
Declutches properly in parking position with gear engaged
=> [Bugfix] More reasonable declutchRPM

source/rig_file_input_output/RigDef_Parser.cpp
=> [Bugfix] Fixes the trigger blocker parsing

source/rig_file_input_output/RigDef_Parser.cpp
This should fix most of the issue with the Liebherr 13HM.
=> [Bugfix] Fixes the trigger action parsing

source/main/physics/Beam.cpp, source/main/physics/Beam.h
=> [Cleanup] Removed some dead code 'floating_origin_enable'

source/main/gameplay/LandVehicleSimulation.cpp
```accl``` was always zero, we need to use ```getAcc()``` here
Also reworked the brake pedal release curve to be more realistic
=> [Bugfix] Fixes the anti roll back brake release logic

source/main/gfx/camera/CameraBehaviorFree.cpp
Fixes: #236 
Related with: #655
=> [Codechange] Allow clipping the terrain in free camera mode

source/main/main_sim/MainThread.cpp
Needs to be tested on Windows.
=> [Bugfix] Prevents segfault on exit

tools/windows/binaries/Debug/plugins_d.cfg, tools/windows/binaries/RelWithDebInfo/plugins.cfg, tools/windows/binaries/Release/plugins.cfg
RenderSystem_Direct3D10 and RenderSystem_Direct3D11
=> Removed unused render

bin/resources/skeleton/config/input.map, source/main/gameplay/RoRFrameListener.cpp, source/main/gui/GUIManager.cpp, source/main/gui/GUIManager.h, source/main/gui/panels/GUI_VehicleDescription.cpp, source/main/gui/panels/GUI_VehicleDescription.h, source/main/utils/InputEngine.cpp, source/main/utils/InputEngine.h
* Adds keyboard shortcut to open the vehicle selector (CTRL + N)
* Adds keyboard shortcut to toggle the truck description (CTRL + T)
Fixes: #245
=> [Feature] Added new keyboard shortcuts (truck description / new vehicle)

source/configurator/Configurator.cpp, source/main/scripting/LocalStorage.h, source/main/utils/ImprovedConfigFile.h
=> [Build fix] Config in RoRConfig :)

source/main/physics/input_output/RigSpawner.cpp
@tritonas00, @Hotrod55 please test.
Related vehicles:
http://www.rigsofrods.com/repository/download/5525
http://www.rigsofrods.com/threads/85448-Desperado-Rock-Bouncer-Buggy
=> [Codechange] Corrects the orientation of FlexBodyWheels when spawned rotated

source/main/utils/utf8/checked.h
Rare issue, observed with: http://www.rigsofrods.com/threads/77547-Jantor-BigMachines
=> [fix] Utf8: do not throw on incomplete last character.

source/main/main_sim/MainThread.cpp
Makes the character face into the driving direction, when exiting a truck.
=> [Codechange] Character disembarks aligned with the truck

source/main/gameplay/SceneMouse.cpp
Makes it a lot easier to select nodes as orbit center.
=> [Codechange] Makes it easier to selectes orbit center nodes

source/main/gameplay/Character.cpp, source/main/physics/collision/Collisions.cpp, source/main/physics/collision/Collisions.h
This completely solves the selector window issue (in combination with #738).
Related with: https://github.com/RigsOfRods/rigs-of-rods/pull/744
=> [Bugfix] Prevent selector window from popping up right after canceling

source/main/datatypes/beam_t.h, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/BeamForcesEuler.cpp
This also changes the `stress` <--> `color` relationship.
=> [Cleanup] Moved the skeleton coloring to a central place

source/main/gameplay/BeamEngine.cpp
=> [Bugfix] Fixes incorrect 'autoselect' mode on engine start

source/main/physics/input_output/RigSpawner.cpp
=> [Bugfix] Fixes shocks always using the default detacher_group

source/main/gameplay/BeamEngine.cpp
=> [Bugfix] Prevents clutch from not being released during upshifts

source/main/physics/input_output/RigSpawner.cpp, source/main/physics/input_output/RigSpawner.h
=> [Bugfix] Fixes the 'set_inertia_defaults' parsing for hydros and rotators

source/rig_file_input_output/RigDef_Parser.cpp, source/rig_file_input_output/RigDef_Regexes.h
Fixes the Chinook: http://www.rigsofrods.com/repository/download/1426
Closes: #763
=> [Bugfix] Fixes parsing of commands with trailing delimiter

source/main/gui/panels/GUI_GameChatBox.cpp, source/main/gui/panels/GUI_GameMainMenu.cpp, source/main/gui/panels/GUI_GamePauseMenu.cpp, source/main/gui/panels/GUI_SimUtils.cpp, source/main/gui/panels/GUI_VehicleDescription.cpp
Fixed some untranslated strings in the new GUI panels
=> Fixed untranslated strings

source/main/resources/ContentManager.cpp, source/main/terrain/TerrainGeometryManager.cpp
Fixed the game trying to place the mapbin file in the install folder and added the ogre version to the mapbin file
Should fix #685
=> mapbin file fixes

source/main/resources/ContentManager.cpp
Fixed #789 If you want to compile with ogre 1.8
=> [Fix] Fixed compiling with ogre 1.8

source/main/terrain/TerrainGeometryManager.cpp
Noticeable speedup when loading maps like Auriga
This PR made it work: #789
=> [Codechange] Reactived the terrain caching (mapbin) on linux

source/main/gui/panels/GUI_MainSelector.cpp
=> [Bugfix] Fixes default skinzip selection in the main selector

source/rig_file_input_output/RigDef_Regexes.h
=> [Bugfix] Less strict exhaust section parsing

doc/angelscript/game.h, source/main/scripting/GameScript.cpp, source/main/scripting/GameScript.h, source/main/scripting/ScriptEngine.cpp, source/main/terrain/TerrainObjectManager.cpp, source/main/terrain/TerrainObjectManager.h
Now you can move an object spawned with AngelScript using
```
game.moveObject("truckshop", position);
```
It doesn't update the collision box
=> Added angelscript function moveObject

source/main/gameplay/Replay.cpp, source/main/gameplay/Replay.h, source/main/gameplay/RoRFrameListener.cpp
The replay panel should be managed by the GUIManager
Fixes: #826
=> [Bugfix] Replay bar does not hide with with GUI

source/main/gui/GUIManager.cpp
=> [Bugfix] Fixes MyGUI.log being created in the wrong path

cmake/DependenciesConfig.cmake, source/configurator/CMakeLists.txt
I made follow changes:
- pthreadVC2 -> pthreadsVC2
- wxWidgets 29 -> wxWidgets 31
- mysocketw -> SocketW
- freetype2311 -> freetype
I've used the same sources like @mikadou and they generate new lib names.
=> few changes for new windows deps

source/main/gui/panels/GUI_SimUtils.cpp
Automatically shows the truck info box, when entering a vehicle, when the truck info is toggled on
=> [Codechange] Auto show truck info when entering a vehicle

source/main/gui/DashBoardManager.cpp
=> [Bugfix] Fixes custom GUI always visible

source/main/MainThread.cpp, source/main/MainThread.h, source/main/gameplay/RoRFrameListener.cpp, source/main/gameplay/RoRFrameListener.h, source/main/gfx/PreviewRenderer.cpp, source/main/gfx/VideoCamera.cpp, source/main/gui/Console.cpp, source/main/gui/GUIMenu.cpp, source/main/gui/GUIMp.cpp, source/main/gui/OverlayWrapper.cpp, source/main/gui/OverlayWrapper.h, source/main/gui/panels/GUI_MainSelector.cpp, source/main/terrain/TerrainManager.cpp
Moved some minor stuff out of the RoRFrameListener
Renamed members
Removed dead code
=> [Cleanup] RoRFrameListener cleanup

source/main/gui/panels/GUI_GameAbout.cpp
Adapted from @AnotherFoxGuy: https://github.com/RigsOfRods/rigs-of-rods/pull/811/commits/5774dfc1c9ac3fc90130d04fddaed7c225fa14fb
Closes: https://github.com/RigsOfRods/rigs-of-rods/pull/811
=> [Codechange] Updated the game credits

source/main/physics/BeamFactory.cpp
Fixes `NETWORKED` trucks not being updated
=> [Bugfix] Reverts flexbody update condition check

source/main/MainThread.cpp, source/main/gameplay/RoRFrameListener.cpp, source/main/physics/BeamFactory.cpp
The `NetworkStreamManager` is now updated while the sim thread is paused
Removed redundant `GUI_Multiplayer` updates
=> [Codechange] Reordered network updates in the game loop

source/main/physics/input_output/RigSpawner.cpp
=> [Bugfix] Fixes broken flextires in multiplayer

source/main/physics/BeamForcesEuler.cpp
This includes rim nodes into the high resolution node collision setting.
=> [Codechange] High-res node collision for all wheel nodes

source/main/physics/Beam.cpp, source/main/physics/BeamData.h, source/main/physics/input_output/RigSpawner.cpp
Does not conflict with the physics simulation and particle effect generation (both depend on the iswheel value)
Better solution for: https://github.com/RigsOfRods/rigs-of-rods/pull/897
=> [Codechange] Better solution for the multiplayer flextire issue

source/main/physics/Beam.cpp, source/main/physics/air/TurboProp.cpp, source/main/physics/air/TurboProp.h
* Fixes `Turboprop` sounds/particles not removed on truck deletion (missing destructor)
* Fixes typo in `cparticles` deletion
Related with: #376
=> [Bugfix] Fixes incomplete sound / particle deletion

source/main/physics/Beam.cpp
=> [Codechange] Disable sounds on truck deletion

source/main/audio/Sound.cpp
=> [Bugfix] Fixes erroneous sound source recomputation

source/main/gameplay/LandVehicleSimulation.cpp
The anti roll back system now stops working when the ignition is cut off.
It now also prevents rolling (back / forth) on flat surfaces.
=> [Codechange] Overworked the anti roll feature

source/main/MainThread.cpp
=> [Bugfix] Prevents spawning the character in mid-air

bin/resources/skeleton/config/input.map, source/main/gameplay/RoRFrameListener.cpp, source/main/gameplay/RoRFrameListener.h, source/main/physics/BeamFactory.cpp, source/main/physics/BeamFactory.h, source/main/utils/InputEngine.cpp, source/main/utils/InputEngine.h
* `EV_COMMON_ENTER_NEXT_TRUCK` (default: `CTRL+RBRACKET`)
* `EV_COMMON_ENTER_PREVIOUS_TRUCK` (default: `CTRL+LBRACKET`)
* `EV_COMMON_REMOVE_CURRENT_TRUCK` (default: `CTRL+DELETE`)
* `EV_COMMON_RESPAWN_LAST_TRUCK` (default: `CTRL+PERIOD`)
=> [Feature] Added new keyboard shortcuts

source/main/gameplay/RoRFrameListener.cpp, source/main/gameplay/RoRFrameListener.h, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/collision/PointColDetector.cpp, source/main/physics/collision/PointColDetector.h
* Trucks now spawn centered with their rotational center
* Trucks now auto avoid other trucks when spawned
=> [Feature] Overworked the truck spawning logic

source/main/physics/Beam.cpp, source/main/physics/input_output/RigSpawner.cpp, source/main/physics/input_output/RigSpawner.h
Fixes: #944
Partly reverts: https://github.com/RigsOfRods/rigs-of-rods/commit/b529d010815a51590f1a0c3df48ce6bb082d6d29
=> [Bugfix] Fixes visual glitch

source/main/gameplay/RoRFrameListener.cpp
* Fixes recently broken truck shops (`m_reload_box` was ignored)
* Fixes temporary visual glitch during spawning
* Improves collision avoidance (e.g. trailers now avoid trucks)
=> [Bugfix] Various truck spawning fixes

source/main/gameplay/Character.cpp
Auto compensates minor height differences (pavements, stairways, ...).
=> [Feature] Improved character collision detection

source/main/MainThread.cpp
Fixes rudder gui stays visible when cycling through boats and trucks
=> [Bugfix] Properly remove overlays & sounds on vehicle change

source/main/gui/panels/GUI_GameChatBox.cpp, source/main/gui/panels/GUI_GameChatBox.h
The chat box no longer disappears while having key focus.
=> [Codechange] Overworked the multiplayer chat box auto-hide logic

source/main/network/Network.cpp
The bandwidth calculation ignored data that was sent out via the 'sendMessageRaw' method
=> [Codechange] Removed duplicate code, fixed bandwidth calculation

source/main/physics/BeamFactory.cpp
'SLEEPING' trucks no longer send data over the network
=> [Codechange] Only active trucks send stream data

source/main/CMakeLists.txt, source/main/ForwardDeclarations.h, source/main/datatypes/rig_t.h, source/main/gfx/Mirror.cpp, source/main/gfx/Mirror.h, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/BeamData.h, source/main/physics/BeamFactory.cpp, source/main/physics/input_output/RigSpawner.cpp
=> [Feature] Brings back traditional mirrors

source/main/gameplay/Replay.h, source/main/gfx/camera/CameraBehaviorOrbit.cpp, source/main/physics/Beam.cpp, source/main/physics/BeamForcesEuler.cpp
* Fixes screen tearing in replay mode (Fixes: #990)
* Fixes orbit camera stuttering in replay mode
* Fixes replay not storing node velocity and forces
=> [Bugfix] Various replay mode fixes

source/main/MainThread.cpp, source/main/gameplay/SceneMouse.cpp, source/main/gui/OverlayWrapper.cpp, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/BeamData.h, source/main/physics/BeamFactory.cpp, source/main/physics/BeamFactory.h, source/main/physics/BeamForcesEuler.cpp, source/main/scripting/ScriptEngine.cpp, source/main/terrain/TerrainObjectManager.cpp, source/main/terrain/map/SurveyMapEntity.cpp, source/main/terrain/map/SurveyMapManager.cpp
Condensed `ACTIVATED`, `DESACTIVATED`, `MAYSLEEP` and `GOSLEEP` into a single state called `SIMULATED`.
=> [Cleanup] Simplified the truck sleeping logic

source/main/gameplay/Character.cpp, source/main/gfx/camera/CameraBehaviorFixed.h, source/main/gfx/camera/CameraBehaviorFree.h, source/main/gfx/camera/CameraBehaviorIsometric.h, source/main/gfx/camera/CameraBehaviorOrbit.cpp, source/main/gfx/camera/CameraBehaviorOrbit.h, source/main/gfx/camera/CameraBehaviorStatic.cpp, source/main/gfx/camera/CameraBehaviorStatic.h, source/main/gfx/camera/CameraBehaviorVehicle.cpp, source/main/gfx/camera/CameraBehaviorVehicleSpline.cpp, source/main/gfx/camera/CameraManager.cpp, source/main/gfx/camera/CameraManager.h, source/main/gui/GUIMenu.cpp, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/BeamFactory.cpp, source/main/utils/IBehavior.h
- Completely fixes the orbit camera stuttering
- Re-enables smooth camera rotation in replay mode
- Enables smooth camera rotation & translation in camera rail mode
- Enables smooth camera transitions when the camera target changes
- Fixes camera glitch when using the vehicle list to change vehicles
- Fixes screen tearing when walking across steps
=> [Codechange] Various camera improvements

source/main/physics/Beam.cpp, source/main/physics/BeamFactory.cpp
* Eliminated `std::bind` (+ 10% fps on the container test map)
* Reordered `Flexable` calculation (+ 7% fps on the 12 car test map)
=> [Codechange] Minor performance improvements

tools/travis/linux/dependencies.sh
also suppress warnings for dependencies to reduce log noise
=> [Tools] Travis: Use Debug build type for dependencies

source/main/physics/input_output/RigSpawner.cpp
=> [Bugfix] Fixes double-sided managed materials

source/main/audio/SoundManager.cpp, source/main/audio/SoundManager.h
=> [Bugfix] Fixes broken sound sources recalculation

source/main/gui/panels/GUI_MainSelector.cpp
=> [Bugfix] Fixes crash in the menu system

source/main/physics/BeamFactory.cpp
Default keys: `CTRL+]` and `CTRL+[`
=> [Codechange] Exclude remote trucks from truck cycle

source/rig_file_input_output/RigDef_Regexes.h
Adresses the bug reported here: http://forum.rigsofrods.org/thread-263-post-2420.html#pid2420
=> [Fix] Special prop dashboard backward compatibility

source/configurator/Configurator.cpp, source/main/audio/Sound.h, source/main/audio/SoundManager.h, source/main/gameplay/CharacterFactory.cpp, source/main/gfx/particle/OgreShaderParticleRenderer.cpp, source/main/gfx/particle/OgreShaderParticleRenderer.h, source/main/gui/panels/GUI_GameSettings.cpp, source/main/physics/BeamFactory.cpp, source/main/utils/Settings.cpp
Thanks to @chilledfrogs for testing and helping.
- RoRConfig doesn't build yet
- only tested without the optional dependencies so far
=> [Fix] Build on OS X

bin/resources/mygui/settings.layout, source/configurator/Configurator.cpp, source/main/gui/panels/GUI_GameSettings.cpp, source/main/gui/panels/GUI_GameSettings.h, source/main/gui/panels/GUI_GameSettingsLayout.h
Remapping feature is not implemented yet, the button only causes confusion.
Also see #1049.
=> [Workaround] Remove Re-map button from controls menu

source/main/gui/panels/GUI_SimUtils.cpp
=> Renamed "Vehicle's destruction" -> "Vehicle destruction"

AUTHORS.md, source/main/gui/panels/GUI_GameAbout.cpp
As I announced on the gitter dev channel I'm officially retiring from RoR development with this PR for personal reasons.
Kudos to all the developers I worked with and the rest of the community that stuck with the project through bad times. We managed to turn a horribly broken project into a respectable open source project again and the future of RoR is looking bright. I enjoyed working on the project but it's now time for me to say good bye.
PS: New maintainers may be needed for:
- RoR Linux build scripts: https://github.com/RigsOfRods/ror-linux-buildscripts
- RoR OS X build scripts: https://github.com/RigsOfRods/ror-osx-buildscripts
- Transifex translations (@AnotherFoxGuy maybe?): https://www.transifex.com/rigsofrods/rigs-of-rods/dashboard/
=> [Doc] Update game credits (Hiradur is retiring)

doc/angelscript/game.h, doc/angelscript/global_functions.h, source/main/gameplay/ScriptEvents.h, source/main/gui/panels/GUI_MessageBox.cpp, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/scripting/GameScript.cpp, source/main/scripting/GameScript.h, source/main/scripting/ScriptEngine.cpp
#298 Added ```game.spawnTruck("shoppingcart.truck" ,vector3(512, 0, 512) , vector3(0, 90, 0));```
Spawns a truck and returns the reference of the Beam object
Added ```game.showMessageBox("Im a box","Do you like it?",true,"Yes",false,true,"No");```
Shows a simple MessageBox
=> More AngelScript features

source/main/physics/input_output/RigSpawner.cpp
=> [Bugfix] Fixes invisible hydros / shocks at spawn

source/main/gameplay/RoRFrameListener.cpp, source/main/physics/BeamFactory.cpp
=> [Bugfix] Fixes videocamera stuttering

source/main/physics/input_output/RigSpawner.cpp
=> [Bugfix] Fixes right side turning signal not blinking

source/main/gameplay/Character.cpp
See: https://github.com/RigsOfRods/rigs-of-rods/pull/1111#issuecomment-245622621
=> [Bugfix] Fixes character walking animation (diagonally)

source/main/terrain/TerrainObjectManager.cpp
Requested by @DarthCainRor 
#374
Now you can add ambient lights to your object by adding this to your odef file
```
;pointlight x, y, z, dirx, diry, dirz, r, g, b, range
pointlight -13, 1, 6, -1, 0, -1, 10, 5, 0, 60
```
```
;spotlight x, y, z, dirx, diry, dirz, r, g, b, range, innerAngle, outerAngle 
spotlight  -13, 1, 6, -1, 0, -1, 10, 5, 0, 60,30,45
```
=> [Feature] Added ambient light

source/main/gfx/OgreSubsystem.cpp, source/main/gui/OverlayWrapper.cpp, source/main/main.cpp, source/main/physics/collision/Collisions.cpp, source/main/resources/CacheSystem.cpp, source/main/utils/ErrorUtils.cpp, source/main/utils/ErrorUtils.h
=> Replaced ShowOgreWebError and ShowWebError with ShowError

source/configurator/Configurator.cpp
=> [RoRConfig] Fixed crash when sys. lang. detect. fails

source/main/physics/BeamForcesEuler.cpp
=> [Bugfix] Fixes auto-centering commands

source/main/utils/WriteTextToTexture.cpp
=> [Bugfix] Fixed a typo

source/main/terrain/TerrainGeometryManager.cpp
Fixes: #1053
Temporary solution until our custom heightfinder supports multiple terrain pages
=> [Bugfix] Brings back old heightfinder

source/main/physics/collision/DynamicCollisions.cpp
=> [Bugfix] Fixes tracked vehicles

source/main/physics/Beam.cpp
Fixes the wheel node count in the truck info box.
=> [Bugfix] Fixes wheel node count calculation

source/main/datatypes/rig_t.h, source/main/physics/Beam.cpp, source/main/physics/RigSpawner.cpp, source/main/physics/RigSpawner.h
=> [Bugfix] Fixes wheels2 in multiplayer

source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/BeamFactory.cpp
Prevents inactive remote trucks from sitting at (0, 0, 0)
=> [Codechange] Periodically update remote sleeping trucks

source/main/Application.cpp, source/main/MainThread.cpp
I don't really understand why, but it does seem to fix the issue.
Related with: https://github.com/RigsOfRods/rigs-of-rods/issues/1163
=> [Bugfix] Fixes 'Vegetation' setting not saved

source/configurator/Configurator.cpp
'FPS-Limiter=0' now means unlimited in both 'RoR' and 'RoRConfig'
=> [Bugfix] Fixes 'FPS-Limiter' stuck at 10

source/main/Application.cpp, source/main/utils/Settings.cpp
Also enables multi threading by default
=> [Bugfix] Fixes 'Multi-threading' setting

source/main/terrain/TerrainManager.cpp
Fixes: #1172
Reference: https://github.com/RigsOfRods/rigs-of-rods/commit/3bd6e735768fcc5cebb96f5939ff02a78d1da75a#diff-39389de445cad8e4eaae81a281ddaa24R722
=> [Bugfix] Fixes Angelscript

source/main/gui/GUIManager.cpp
Reference: https://github.com/RigsOfRods/rigs-of-rods/commit/0dfab15b8cb4ff56d9ae7768959d806d9784fb11#diff-b1651c1035bf3aeba06425e761ba13b4L461
=> [Bugfix] Fixes 'hideGUI' permanently disabling notifications

source/main/gui/panels/GUI_GameAbout.cpp
=> [Bugfix] Fixes 'GameAbout' back button

source/main/physics/Beam.cpp
Fixes auto concatenation of camera rails
=> [Codechange] Properly update the linked beams list

source/main/Application.cpp, source/main/Application.h, source/main/MainThread.cpp, source/main/gui/panels/GUI_GameMainMenu.cpp, source/main/utils/Settings.cpp
Tested with `SkipMainMenu=Yes/No` in both singleplayer and multiplayer.
Related with: #1163
=> [Bugfix] Fixes 'Preselected map' setting

source/main/physics/BeamForcesEuler.cpp
Inter truck beams are never part of a detacher group
Fixes: #1143
=> [Cleanup] Removed unreachable code

source/main/MainThread.cpp, source/main/network/Network.cpp, source/main/network/Network.h
* Fixes broken network shutdown procedure
* Fixes messed up log message output
* Fixes handing of network errors during terrain selection
Fixes: #1151
=> [Bugfix] Fixen broken network shutdown procedure

source/main/gfx/dof/DepthOfFieldEffect.cpp
=> [Bugfix] Fixes crash on 'Back to menu'

source/main/main.cpp
The game now loads the config file first and then checks the command line arguments
=> Fixed the game overwriting the command line arguments

source/main/resources/rig_def_fileformat/RigDef_Parser.cpp
=> [Codechange] Ignore invalid managed_material textures

source/main/gui/panels/GUI_TopMenubar.cpp, source/main/gui/panels/GUI_TopMenubar.h, source/main/network/Network.cpp
Updates the vehicles list in multiplayer when players join or leave.
=> [Bugfix] Properly update vehicles list

source/main/gui/OverlayWrapper.cpp
Fixes: #1220
It's ugly, but it works.
=> [Bugfix] Fixes streched airplane HUD

source/main/gameplay/BeamEngine.cpp, source/main/gameplay/BeamEngine.h
Forbid kickdowns right after forced upshifts
=> [Codechange] Added kickdown delay

source/main/utils/Settings.cpp
=> Fixed translations not loading

source/main/gui/panels/GUI_GameSettings.cpp
=> Fixed the volume slider

source/main/physics/Beam.cpp
=> [Bugfix] Fixes 'tieToggle' and 'lightToggle' forwarding

source/main/network/Network.h, source/main/network/RoRnet.h
I embarrasingly misunderstood how stuff works: http://stackoverflow.com/a/33438292 and most importantly that `#pragma (pack)` isn't windows-specific: https://gcc.gnu.org/onlinedocs/gcc-4.8.4/gcc/Structure-Packing-Pragmas.html
=> :bug: Fix: Bad struct packing in RoRnet.h + Network.h

source/main/MainMenu.cpp, source/main/gameplay/Character.cpp, source/main/gameplay/OutProtocol.cpp, source/main/gameplay/RoRFrameListener.cpp, source/main/gui/panels/GUI_MultiplayerClientList.cpp, source/main/gui/panels/GUI_MultiplayerClientList.h, source/main/main.cpp
=> Fix for building without USE_SOCKETW

source/configurator/Configurator.cpp, source/main/main.cpp, source/main/utils/PlatformUtils.cpp, source/main/utils/PlatformUtils.h
=> Fixed crash on cache-regen if cache directory deleted

source/main/audio/SoundManager.cpp
When the audio device specified in RoR.cfg fails to open for any reason, RoR tries to open system's default audio device. Additionally, the faulty device name is erased from RoR.cfg.
This partially works around the issue with special characters in sound device name.
=> Partial workaround for the "no sound" issues.

.travis.yml
=> Updated travis to trusty

source/main/physics/BeamFactory.cpp
=> Fixed building with VS 2017

source/main/terrain/TerrainManager.cpp
=> Fixed water height not loading

source/configurator/Configurator.cpp
Removes this dialogue box when starting RoRConfig
=> Improved RoRConfig log messages

bin/resources/scripts/races.as, doc/angelscript/game.h
=> Renamed setDirectionArrow => UpdateDirectionArrow

source/main/physics/Beam.cpp, source/main/physics/RigSpawner.cpp, source/main/resources/CacheSystem.cpp, source/main/resources/rig_def_fileformat/RigDef_File.cpp, source/main/resources/rig_def_fileformat/RigDef_File.h, source/main/resources/rig_def_fileformat/RigDef_Parser.cpp, source/main/resources/rig_def_fileformat/RigDef_SequentialImporter.cpp, source/main/resources/rig_def_fileformat/RigDef_Validator.cpp
Fixes spawning of Dodge Magnum #1360
=> Truckfile 'section/end_section' handling fix

source/main/CMakeLists.txt
https://github.com/RigsOfRods/ror-dependencies/pull/18
=> removed unused plugins

source/main/datatypes/wheel_t.h, source/main/gfx/Skidmark.cpp, source/main/gfx/Skidmark.h, source/main/physics/RigSpawner.cpp, source/main/physics/RigSpawner.h
=> Hotfix for flexbodywheels glitch and skidmarks crash.

source/main/gfx/Skidmark.cpp, source/main/gfx/Skidmark.h, source/main/main.cpp
Such a dumb mistake!
I was loading 'skidmarks.cfg' too early (before initializing OGRE resource groups), thus the file was never found and RoR had no skidmark definitions to use.
=> Hotfix for skidmarks

CMakeLists.txt, cmake/GenerateVersionInfo.cmake, source/version_info/CMakeLists.txt, source/version_info/RoRVersionDef.h.in
This can be used to create a custom build without modifying the cmake file
=> ✨ Added CMake option for specifying a custom version

source/configurator/SystemTools.cpp
=> Hotfix for RoRConfig unpacking 'skeleton.zip'

cmake/Install.cmake, source/main/CMakeLists.txt
Fixes RigsOfRods/ror-linux-buildscripts#26
=>  🐛 Fixed installing the game on Linux

CMakeLists.txt, source/main/CMakeLists.txt
Fixes #1419 
Fixes RigsOfRods/ror-linux-buildscripts#27
Fixes RigsOfRods/ror-linux-buildscripts#24
=> 🐛 Fixed installing the resources on Linux

source/main/gameplay/AutoPilot.cpp, source/main/gameplay/RoRFrameListener.cpp, source/main/gfx/DustPool.cpp, source/main/gfx/HydraxWater.cpp, source/main/gfx/HydraxWater.h, source/main/gfx/IWater.h, source/main/gfx/Water.cpp, source/main/gfx/Water.h, source/main/gui/panels/GUI_GameConsole.cpp, source/main/physics/Beam.cpp, source/main/physics/BeamForcesEuler.cpp, source/main/scripting/GameScript.cpp, source/main/terrain/map/SurveyMapTextureCreator.cpp
Fixed by a bit of trial and error - hopefully everything is allright.
Fixes #1318
=> Hydrax water level fix

source/main/resources/ContentManager.cpp
This can be useful when installing the content pack with a script
=> 🔧 Load content from Program Path/content

source/main/gui/panels/GUI_GameSettings.cpp, source/main/gui/panels/GUI_GameSettings.h, source/main/physics/flex/FlexMesh.cpp, source/main/resources/otc_fileformat/OTCFileformat.cpp, source/main/resources/otc_fileformat/OTCFileformat.h
The damn bombinette crash took me almost all day, but I finally figured it out: https://github.com/RigsOfRods/rigs-of-rods/issues/1256#issuecomment-352469930
I'm taking tomorrow off. 😆 
UPDATE: I also slipped a minor internal fix here
=> Miniredmars fixes

source/main/utils/Settings.cpp
=> :bug: Avoid crash on Linux by using real buffer size

source/configurator/SystemTools.cpp, source/main/Application.cpp, source/main/Application.h, source/main/MainMenu.cpp, source/main/audio/MumbleIntegration.h, source/main/audio/SoundScriptManager.cpp, source/main/audio/SoundScriptManager.h, source/main/gameplay/AutoPilot.cpp, source/main/gameplay/AutoPilot.h, source/main/gameplay/BeamEngine.cpp, source/main/gameplay/LandVehicleSimulation.cpp, source/main/gameplay/RoRFrameListener.cpp, source/main/gui/GUIManager.cpp, source/main/gui/OverlayWrapper.cpp, source/main/main.cpp, source/main/physics/Beam.cpp, source/main/physics/BeamFactory.cpp, source/main/physics/BeamForcesEuler.cpp, source/main/physics/RigSpawner.cpp, source/main/physics/air/TurboJet.cpp, source/main/physics/air/TurboProp.cpp, source/main/physics/water/ScrewProp.cpp
=> Fix building without OpenAL/SocketW

source/main/gfx/camera/CameraBehaviorCharacter.cpp, source/main/gui/GUIInputManager.cpp, source/main/gui/imgui/OgreImGui.cpp, source/main/gui/panels/GUI_TopMenubar.cpp
Still a lot of glitches to fix around here.
=> [WIP] Tweaks before v048 (round2)

source/main/audio/SoundScriptManager.h, source/main/physics/air/TurboJet.cpp
Kudos to @tritonas00 for quickly finding and reporting!
=> HOTFIX: jetplane afterburner sound always on

source/main/utils/Settings.cpp
This should do it.
It builds, but I can't test right now. UPDATE: tested, behaves correctly.
=> HOTFIX: Don't save adjusted FOV to RoR.cfg

source/main/Application.cpp, source/main/Application.h, source/main/gui/panels/GUI_GameSettings.cpp, source/main/physics/Beam.cpp, source/main/utils/Settings.cpp
=> Added 'HighResWheelNodeCollisions' to Settings panel

README.md, source/main/resources/ContentManager.cpp
Load the textures before the materials and overlays
Fixes #1462
=>  🐛 Fixed missing textures

resources/particles/dust.particle, resources/particles/particles.material, resources/particles/smoke.particle
Particle improvements by Charger.
Changes made:
- Tire smoke/Dust no longer continues past the vehicle
Before:
After:
- Engine smoke changed from `Point` emitter to `Box`, decreased quota
Before:
After:
=> Improved particles

source/main/CMakeLists.txt, source/version_info/CMakeLists.txt
* Updated wxWidgets vendor name
* Changed copy resources command to target
=> 🔧 Cmake tweaks

source/configurator/SystemTools.cpp
fixing build via automated script on Fedora 27
=> fixing build via automated script on Fedora 27

source/angelscript_addons/scriptany/scriptany.h, source/angelscript_addons/scriptarray/scriptarray.cpp, source/angelscript_addons/scriptarray/scriptarray.h, source/angelscript_addons/scriptbuilder/scriptbuilder.cpp, source/angelscript_addons/scriptbuilder/scriptbuilder.h, source/angelscript_addons/scriptdictionary/scriptdictionary.cpp, source/angelscript_addons/scripthelper/scripthelper.cpp, source/angelscript_addons/scripthelper/scripthelper.h, source/angelscript_addons/scriptmath/scriptmathcomplex.cpp, source/angelscript_addons/scriptmath/scriptmathcomplex.h, source/angelscript_addons/scriptstdstring/scriptstdstring.cpp, source/angelscript_addons/scriptstdstring/scriptstdstring.h, source/main/scripting/CBytecodeStream.cpp, source/main/scripting/CBytecodeStream.h
=> ✨ Updated AngelScript to v2.32.0

source/main/physics/RigSpawner.cpp
=> Fixed custom particles crashing the game

source/main/physics/RigSpawner.cpp
=> Fixed wheels2 not adding rigidity beams

source/main/physics/RigSpawner.cpp
=> Fixed replaceMaterial skinzip option crashing RoR

source/main/main.cpp
=> Fixed unzipping terrain causing materials not to load

source/main/gfx/camera/CameraManager.cpp
=> Fixed resetting the camera in first person pointing upwards

CMakeLists.txt, cmake/cotire.cmake, source/angelscript_addons/CMakeLists.txt, source/configurator/CMakeLists.txt, source/main/CMakeLists.txt, source/main/gui/GUIInputManager.cpp, source/main/terrain/TerrainObjectManager.cpp, source/main/utils/Settings.cpp, source/main/utils/WriteTextToTexture.cpp
=> 🔧 Added cotire

source/main/CMakeLists.txt, source/main/plugins.cfg.in
=> Fixes ror-dependencies config

source/main/gfx/EnvironmentMap.cpp
=> Hotfix: Crash on loading map

source/main/Application.h
=> Hotfix: Embarrassing stack overflow in class Str

source/main/physics/RigSpawner.cpp
=> Fixed segfault in 'calcShocks2'

source/main/physics/BeamForcesEuler.cpp
- Better handling of uphill starts with manual shifting
- Better activation logic
=> Traction Control: Improved logic

source/main/gameplay/LandVehicleSimulation.cpp, source/main/gameplay/OutProtocol.cpp, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/RigSpawner.cpp
The `wheelslip` and `fade_speed` parameters in the TractionControl section are obsolete as of now.
=> ABS and TC cleanup

source/main/resources/otc_fileformat/OTCFileformat.cpp
Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/1568
=> Fixed page layer crash

source/main/resources/otc_fileformat/OTCFileformat.cpp
Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/1600, Mountainside Gravel and Mountainside reverse; when combined with https://github.com/RigsOfRods/rigs-of-rods/pull/1602
=> Fixed OTC page config error

source/main/gameplay/BeamEngine.cpp
Feels much more  natural this way.
=> More realistic idle mixture logic

source/main/gui/panels/GUI_TopMenubar.cpp
Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/1617
=> Colorized vehicle list

source/main/terrain/TerrainManager.cpp
The simplest mistake - value from terrn2 file was never propagated to live terrain 😊
=> Hotfix: Terrain gravity definition (terrn2)

source/main/physics/collision/Collisions.cpp
Certainly not slower than before.
=> Minor cleanup

source/main/gameplay/BeamEngine.cpp
- More natural rev up
- Allows to pull start the engine
Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/1623
=> Advanced engine startup

source/main/gameplay/Road2.cpp, source/main/physics/collision/Collisions.cpp, source/main/physics/collision/Collisions.h, source/main/terrain/TerrainObjectManager.cpp
`enableCollisionTri`, `removeCollisionBox` and `removeCollisionTri` were basically unused and made no sense in their current form.
=> Minor collisions cleanup

source/main/Application.cpp, source/main/Application.h, source/main/datatypes/node_t.h, source/main/gui/panels/GUI_GameSettings.cpp, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/BeamForcesEuler.cpp, source/main/utils/Settings.cpp
- Fixes ground collision issues of nodes which are not wheel nodes
- Makes the 'HighResWheelNodeCollisions' setting obsolete
Goodbye 'collTestTimer'!
=> Increased node vs. ground collision accuracy (10x)

source/main/gameplay/LandVehicleSimulation.cpp, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/RigSpawner.cpp
Anti roll back now takes the wheel diameter into account
=> Improved anti roll back

source/main/physics/BeamFactory.cpp
This is really not worth the extra cluttering
=> Classic case of premature optimization

source/main/gameplay/LandVehicleSimulation.cpp
The brakes are now disengage as one would expect.
=> Improved starting behaviour on flat terrain

source/main/datatypes/wheel_t.h, source/main/gfx/Skidmark.cpp, source/main/gfx/Skidmark.h, source/main/physics/Beam.cpp
We don't need to keep track of the skidmark data.
=> Simplified the wheel_t structure

source/main/physics/Beam.h, source/main/physics/BeamForcesEuler.cpp
Fixes the oddity that the driveshaft speed calculation is based off the radius of the first wheel in the wheel section.
=> Minor Wheel/Axle cleanup

source/main/gfx/GfxActor.cpp
- Only visible in the beam debug view
- Replaces the compression text in the beam debug view
=> Reintroduced beam stress visualization

source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/BeamFactory.cpp, source/main/physics/BeamForcesEuler.cpp, source/main/physics/BeamSlideNode.cpp
Based on: https://github.com/RigsOfRods/rigs-of-rods/commit/d3ffea00e12c0f00aebf1e25ff20655cb6bef146
=> Separate calcForcesEulerCompute into smaller functions

source/main/physics/BeamForcesEuler.cpp, source/main/physics/Differentials.cpp
This completes: https://github.com/RigsOfRods/rigs-of-rods/pull/1673
=> Simplified and improved the open diff

source/main/gameplay/SceneMouse.cpp, source/main/physics/Beam.h
We should have had this for years ...
=> ✨ Allow switching player vehicle via middle click

source/main/physics/BeamForcesEuler.cpp
This should also fix issues with wheels that have little to no ground contact
=> Simplified the traction control logic

source/main/gameplay/BeamEngine.h, source/main/gui/panels/GUI_SimUtils.cpp, source/main/gui/panels/GUI_SimUtils.h
Replaced the almost useless maximum / minimum g-force output with more useful engine output data.
Adds the following stats to the sim utils panel:
- Engine torque
- Gearbox RPM
- Gear ratio
=> Small SimUtils revamp

source/main/gameplay/BeamEngine.h, source/main/gui/panels/GUI_SimUtils.cpp
Fixes both the wheel slip detection and the gear ratio calculation on the simutils panel
=> SimUtils wheel slip / gear ratio

resources/skeleton/config/input.map, source/main/gameplay/BeamEngine.cpp, source/main/gameplay/BeamEngine.h, source/main/gameplay/LandVehicleSimulation.cpp, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/BeamForcesEuler.cpp, source/main/physics/Differentials.h, source/main/physics/RigSpawner.cpp, source/main/utils/InputEngine.cpp, source/main/utils/InputEngine.h
This also introduces new keyboard shortcuts and status messages for the drivetrain.
=> Introduced transfer cases

source/main/physics/RigSpawner.cpp, source/main/physics/RigSpawner.h, source/main/physics/RigSpawner_ProcessControl.cpp, source/main/resources/rig_def_fileformat/ReadMe.txt, source/main/resources/rig_def_fileformat/RigDef_File.cpp, source/main/resources/rig_def_fileformat/RigDef_File.h, source/main/resources/rig_def_fileformat/RigDef_Parser.cpp, source/main/resources/rig_def_fileformat/RigDef_Parser.h, source/main/resources/rig_def_fileformat/RigDef_Regexes.h, source/main/resources/rig_def_fileformat/RigDef_Serializer.cpp, source/main/resources/rig_def_fileformat/RigDef_Serializer.h
This introduces two new truck file sections. One for inter-axle differentials and one for transfer cases.
=> Parser upgrade: 'TransferCase' / 'interaxles'

source/main/physics/Beam.cpp
=> Fixed possible nullptr dereference

source/main/physics/RigSpawner_ProcessControl.cpp, source/main/resources/rig_def_fileformat/ReadMe.txt, source/main/resources/rig_def_fileformat/RigDef_File.cpp, source/main/resources/rig_def_fileformat/RigDef_Parser.cpp, source/main/resources/rig_def_fileformat/RigDef_Regexes.h, source/main/resources/rig_def_fileformat/RigDef_Serializer.cpp
Example:
```
transfercase
;default driven axle, alternate axle, alternate ratio, 2wd lo mode
2, 1, 3.0, 1
```
=> Converted 'TransferCase' directive into section

source/main/gameplay/BeamEngine.h, source/main/gameplay/LandVehicleSimulation.cpp
More stable and less dependent on the FPS.
=> Reworked the cruise control logic

resources/skeleton/config/input.map, source/main/gameplay/RoRFrameListener.cpp, source/main/gui/OverlayWrapper.cpp, source/main/gui/OverlayWrapper.h, source/main/utils/InputEngine.cpp, source/main/utils/InputEngine.h
Closes: https://github.com/RigsOfRods/rigs-of-rods/issues/1672
=> ✨ Added exclusive dashboard toggle hotkey

source/main/gameplay/RoRFrameListener.cpp
This is how it was meant to be like.
=> Different truck reset rotation limit

source/main/datatypes/beam_t.h, source/main/gfx/GfxActor.cpp, source/main/gfx/GfxActor.h, source/main/gui/panels/GUI_TopMenubar.cpp, source/main/physics/BeamForcesEuler.cpp
Adds a shocks debug view mode:
- Contraction / Extension (in %)
- Spring rate
- Damping
- Velocity (in m/s)
=> ✨ Experimental shocks debug info mode

source/main/gameplay/Character.cpp, source/main/gui/panels/GUI_TopMenubar.cpp
=> Fixed build without socketw

source/main/gameplay/RoRFrameListener.cpp, source/main/utils/ForceFeedback.cpp
We already check if a force feedback device exists in main.cpp
=> Minor force feedback cleanup

source/main/physics/BeamFactory.cpp
or else the game will freeze as soon as two trucks become active
=> Don't create thread pool with less than 2 threads

source/main/gameplay/AircraftSimulation.cpp, source/main/gameplay/BeamEngine.cpp, source/main/gameplay/LandVehicleSimulation.cpp, source/main/gameplay/OutProtocol.cpp, source/main/gameplay/RoRFrameListener.cpp, source/main/gameplay/VehicleAI.cpp, source/main/physics/Beam.cpp, source/main/physics/BeamForcesEuler.cpp
Trailers were always using the brake force of the towing truck.
=> Fixed the trailer brakeforce logic

source/main/gfx/GfxActor.cpp, source/main/physics/Beam.cpp, source/main/physics/BeamFactory.cpp, source/main/physics/BeamFactory.h, source/main/physics/BeamForcesEuler.cpp
Fixes: https://github.com/RigsOfRods/rigs-of-rods/pull/1598
Replaces: https://github.com/RigsOfRods/rigs-of-rods/pull/1747
Prevents deadlocks and segfaults.
=> Various threading fixes

source/main/physics/collision/PointColDetector.cpp, source/main/physics/collision/PointColDetector.h
It introduced some nasty segfaults. :blush:
=> Partly reverts the PointCD cleanup

source/main/physics/collision/DynamicCollisions.cpp, source/main/physics/collision/PointColDetector.cpp, source/main/physics/collision/PointColDetector.h
This is how https://github.com/RigsOfRods/rigs-of-rods/pull/1753 should have been like from the beginning.
=> PointColDetector cleanup

source/main/physics/BeamFactory.cpp
Mainly leftovers from: https://github.com/RigsOfRods/rigs-of-rods/pull/1598
=> ActorManager header cleanup

source/main/network/RoRnet.h
-> https://github.com/RigsOfRods/ror-server/pull/55
=> Fixed broken actor stream register

source/main/terrain/TerrainManager.cpp
Took me a while to see the obvious.
=> Fixed another Travis warning

source/main/physics/Beam.cpp
Properly resets the:
- Wheel torque
- Turn indicators
- Input shaft RPM
- (Locked) Differentials
=> Fixed a few truck reset issues

source/main/audio/SoundScriptManager.cpp, source/main/audio/SoundScriptManager.h, source/main/gameplay/SkinManager.cpp, source/main/network/Network.cpp
Reported by Coverity Scan.
Closes: https://github.com/RigsOfRods/rigs-of-rods/pull/1790
Closes: https://github.com/RigsOfRods/rigs-of-rods/pull/1792
Closes: https://github.com/RigsOfRods/rigs-of-rods/pull/1793
=> Fixed various resource leaks

source/main/gameplay/LandVehicleSimulation.cpp
=> Removed logically dead code

source/configurator/Configurator.cpp, source/main/gameplay/SkinManager.cpp, source/main/gfx/OgreSubsystem.cpp, source/main/network/Network.cpp, source/main/resources/CacheSystem.cpp, source/main/resources/CacheSystem.h, source/main/resources/terrn2_fileformat/Terrn2Fileformat.cpp, source/main/scripting/GameScript.cpp, source/main/scripting/OgreScriptBuilder.cpp, source/main/utils/InputEngine.cpp, source/main/utils/InputEngine.h
=> Fixed passing of big parameters by value

source/main/physics/air/TurboProp.cpp
Reported by Coverity Scan.
Follow-up of: https://github.com/RigsOfRods/rigs-of-rods/pull/1794
=> Removed dead code

source/main/datatypes/node_t.h, source/main/gfx/GfxActor.cpp, source/main/physics/Beam.cpp, source/main/physics/collision/Collisions.cpp
This should effectively prevent random puffs and screeches, if the tire only slips for a few milliseconds.
=> Attempt to improve the tire smoke/screech logic

source/main/gameplay/Character.cpp, source/main/gameplay/Character.h, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/BeamFactory.cpp
`HideNetLabels=Yes` will hide all net labels.
=> Added 'HideNetLabels' option

conanfile.txt, source/main/CMakeLists.txt
Forgot about this commit https://github.com/RigsOfRods/ogre-caelum/commit/034fe73bb0a6035122bd2bf6b035245c37e5cfa4
=> 🔧 Renamed Caelum to ogre-caelum

CMakeLists.txt, source/version_info/CMakeLists.txt
=> 📐 CMake cleanup

source/main/resources/CacheSystem.cpp
With 8.5 GiB content 18 instead of 28 seconds for a full cache regen.
=> ✨ Much faster content hashing

source/main/utils/Utils.cpp
This should solve: https://github.com/RigsOfRods/rigs-of-rods/pull/1823#issuecomment-441781087, and further improve the read speeds.
=> Fixed possible stack overflow

source/main/gameplay/RoRFrameListener.cpp, source/main/gameplay/RoRFrameListener.h, source/main/physics/Beam.cpp
Also improved the pressure change logic.
=> Fixed wheels2 spawn pressure

source/main/gameplay/BeamEngine.h, source/main/gameplay/RoRFrameListener.cpp, source/main/gfx/GfxActor.cpp, source/main/gfx/SkyManager.cpp, source/main/gfx/camera/CameraManager.cpp, source/main/gfx/hydrax/Real.cpp, source/main/gui/panels/GUI_MultiplayerSelector.cpp, source/main/network/Network.cpp, source/main/physics/BeamFactory.cpp, source/main/physics/RigSpawner.cpp, source/main/physics/flex/FlexBody.cpp, source/main/physics/flex/FlexBody.h, source/main/physics/flex/FlexFactory.cpp, source/main/physics/flex/FlexObj.cpp, source/main/resources/CacheSystem.cpp, source/main/resources/rig_def_fileformat/RigDef_Parser.cpp, source/main/resources/rig_def_fileformat/RigDef_SequentialImporter.cpp, source/main/scripting/GameScript.cpp, source/main/scripting/OgreScriptBuilder.cpp, source/main/utils/Settings.cpp
Fixes:
* pink managedmaterial glitch on Gavrils, see https://github.com/RigsOfRods/rigs-of-rods/issues/1609#issuecomment-442240938
* Crash at exit
* VisualStudio compiler warnings
=> Misc fixes

source/main/Application.cpp, source/main/Application.h, source/main/gameplay/Character.cpp, source/main/gameplay/Character.h, source/main/gameplay/RoRFrameListener.cpp, source/main/gfx/DustManager.cpp, source/main/gfx/GfxActor.cpp, source/main/gfx/GfxActor.h, source/main/gui/panels/GUI_GameSettings.cpp, source/main/terrain/TerrainObjectManager.cpp, source/main/terrain/map/SurveyMapEntity.cpp, source/main/terrain/map/SurveyMapEntity.h, source/main/terrain/map/SurveyMapManager.cpp, source/main/terrain/map/SurveyMapManager.h, source/main/utils/Settings.cpp
=> Fixed broken overview map icons

source/main/terrain/map/SurveyMapManager.cpp, source/main/terrain/map/SurveyMapManager.h
Leftover from the old automatic fade transition between the different modes.
=> Overview map alpha logic cleanup

source/main/gui/panels/GUI_TeleportWindow.cpp, source/main/main.cpp, source/main/terrain/map/SurveyMapManager.cpp, source/main/terrain/map/SurveyMapTextureCreator.cpp, source/main/terrain/map/SurveyMapTextureCreator.h
This also fixes the issue that the teleport window was affected by zoom into the texture.
=> SurveyMapTextureCreator cleanup

resources/skeleton/config/input.map, source/main/gui/panels/GUI_TeleportWindow.cpp, source/main/terrain/map/SurveyMapEntity.cpp, source/main/terrain/map/SurveyMapEntity.h, source/main/terrain/map/SurveyMapManager.cpp, source/main/terrain/map/SurveyMapManager.h, source/main/terrain/map/SurveyMapTextureCreator.cpp, source/main/terrain/map/SurveyMapTextureCreator.h, source/main/utils/InputEngine.cpp, source/main/utils/InputEngine.h
Massive simplifications, render quality improvements, new hide button.
=> Yet another overview map overhaul

source/main/terrain/TerrainGeometryManager.cpp, source/main/terrain/TerrainGeometryManager.h, source/main/terrain/TerrainManager.cpp, source/main/terrain/TerrainManager.h
Might come in handy at some point.
=> Added 'GetMaxHeight' helper

source/main/resources/otc_fileformat/OTCFileformat.cpp, source/main/resources/otc_fileformat/OTCFileformat.h, source/main/resources/terrn2_fileformat/Terrn2Fileformat.cpp, source/main/terrain/TerrainGeometryManager.cpp
Simple, clean and side-effect free.
Closes: #1849
Closes #1841
=> 🎮 Support terrains without otc file

source/main/MainMenu.cpp, source/main/MainMenu.h, source/main/gameplay/RoRFrameListener.cpp
Nobody wants to listen to coil whine in the main menu.
=> Unified the frame limiter code

source/main/Application.cpp, source/main/Application.h, source/main/physics/RigSpawner.cpp, source/main/utils/Settings.cpp
Reference: https://github.com/RigsOfRods/rigs-of-rods/pull/1879#discussion_r240253128
=> Renamed 'gfx_simple_materials'

source/main/gfx/OgreSubsystem.cpp, source/main/main.cpp, source/main/utils/Settings.cpp
Closes: https://github.com/RigsOfRods/rigs-of-rods/pull/1875
=> 🔧 Create missing folders

CMakeLists.txt
=> 🔧 Fixed debug build on windows

source/main/Application.cpp, source/main/Application.h, source/main/physics/RigSpawner.cpp, source/main/utils/Settings.cpp
The whole `static int counter` thing didn't make much sense anymore, since you can spawn more than one truck.
=> Simplified the video camera settings

source/main/Application.cpp, source/main/gfx/GfxActor.cpp, source/main/physics/RigSpawner.cpp, source/main/resources/terrn2_fileformat/Terrn2Fileformat.cpp, source/main/terrain/TerrainObjectManager.cpp, source/main/utils/ConfigFile.cpp, source/main/utils/ConfigFile.h
I was going to fix something from our backlog, but my Debug build gave me enough assertion failures to keep me busy all night.
=> Some minor fixes

source/main/physics/Beam.cpp, source/main/physics/BeamData.h, source/main/physics/RigSpawner.cpp, source/main/resources/rig_def_fileformat/RigDef_File.cpp, source/main/resources/rig_def_fileformat/RigDef_File.h, source/main/resources/rig_def_fileformat/RigDef_Parser.cpp
Suggested by Charger on Discord chat.
I should really be :sleeping:, but I really wanted to do this myself.
=> Truckfile: new 'ties' option 's' (disable self lock)

source/main/Application.cpp, source/main/Application.h, source/main/gfx/DustManager.cpp, source/main/gui/panels/GUI_GameSettings.cpp, source/main/utils/Settings.cpp
Doesn't really make sense to allow to disable it anymore.
=> Removed the minimap setting

source/main/Application.cpp, source/main/Application.h, source/main/gfx/OgreSubsystem.cpp, source/main/gui/panels/GUI_GameSettings.cpp, source/main/utils/Settings.cpp
Automatically resets the render system override setting after usage.
=> Improved the render system override logic

source/main/gui/GUIManager.cpp, source/main/main.cpp, source/main/resources/ContentManager.cpp, source/main/utils/ErrorUtils.cpp, source/main/utils/InputEngine.cpp, source/main/utils/Language.h
Fixes: https://github.com/RigsOfRods/rigs-of-rods/pull/1898, for the case when the mofilereader cannot be found.
=> Fixed the 'NOLANG' build path

source/main/gameplay/RoRFrameListener.cpp, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/collision/Collisions.cpp, source/main/physics/collision/Collisions.h
Makes the teleport feature aware of collision meshes.
=> 🎮 Improved teleport surface detection logic

source/main/gfx/Water.cpp, source/main/gui/panels/GUI_GameConsole.cpp, source/main/gui/panels/GUI_MultiplayerClientList.cpp, source/main/physics/Beam.cpp
https://github.com/RigsOfRods/rigs-of-rods/issues/1908
=> Added missing include

source/main/gameplay/Character.cpp
Nothing fancy, but the impact on gameplay is actually pretty significant:
=> 🎮 Character vs. submesh collisions

source/main/gameplay/RoRFrameListener.cpp
`getSurfaceHeight` on steroids. :smile:
=> 🎮 Smart vehicle exit

source/main/gameplay/Character.cpp, source/main/gameplay/RoRFrameListener.cpp, source/main/physics/collision/Collisions.cpp, source/main/physics/collision/Collisions.h
* Fixed character position when exiting a vehicle inside of a building
* Fixed character spawn position on `Miniredmars`
* Simplified the initial character spawn
=> Minor character collision fixes

source/main/terrain/TerrainObjectManager.cpp
Reference: https://forums.ogre3d.org/viewtopic.php?t=71366
=> Attempt to fix Directx9EX related crashes

tools/CI/upload-CI-build.sh
=> :bug: Added missing lib to itch.io build

resources/skeleton/config/input.map, source/main/gameplay/RoRFrameListener.cpp, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/BeamFactory.cpp
This utilizes the existing command forwarding logic to handle the toggle tie command.
=> 🎮 Improved tie toggle logic

source/main/physics/collision/Collisions.cpp
Decreases the lookup time up to 10 times
=> Minor optimization

source/main/gui/panels/GUI_GameSettings.cpp, source/main/resources/CacheSystem.cpp, source/main/resources/CacheSystem.h
Manually clearing the cache is sometimes the only option to fix certain bugs. Example: https://github.com/RigsOfRods/rigs-of-rods/issues/1939
=> Added 'Clear cache' button

BUILDING.md, DEPENDENCIES.md, cmake/DependenciesConfig.cmake, source/configurator/CMakeLists.txt, source/main/gui/panels/GUI_GameAbout.cpp
=> 📐 Removed wxWidget leftovers

source/main/gfx/DustManager.cpp, source/main/gfx/GfxActor.cpp, source/main/gfx/GfxActor.h
The animator event keys now affect all vehicles connected to the player.
=> 🎮 Improved the animator event logic

source/main/gameplay/BeamEngine.cpp, source/main/gameplay/BeamEngine.h, source/main/gui/panels/GUI_SimUtils.cpp
The SimUtils engine torque / power output display wasn't updated correctly with activated cruise control.
=> 🐛 Fixed torque / power display with cruise control

source/main/Application.cpp, source/main/Application.h, source/main/gui/panels/GUI_GameSettings.cpp, source/main/gui/panels/GUI_GameSettings.h, source/main/physics/RigSpawner.cpp, source/main/utils/Settings.cpp
Back from the 0.3x days, practically dead.
=> 📐 Removed dead feature: 'resourceIncludePath'

source/main/Application.cpp, source/main/Application.h, source/main/gui/panels/GUI_GameSettings.cpp, source/main/physics/Beam.cpp, source/main/physics/BeamFactory.h, source/main/physics/BeamForcesEuler.cpp, source/main/utils/Settings.cpp
Mainly for testing purposes. But also interesting for regular players, if they want to see the effects of higher physics fps.
=> 🎮 Adjustable physics time step

source/main/datatypes/node_t.h, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/BeamConstants.h, source/main/physics/BeamForcesEuler.cpp, source/main/physics/RigSpawner.cpp, source/main/physics/collision/PointColDetector.cpp, source/main/physics/collision/PointColDetector.h
Automatically turns any ground contactable node into a contacter node.
=> 🎮 Advanced contacter logic

source/main/physics/Beam.cpp
=> Fixed hook/tie/rope reset

source/main/gameplay/SkinManager.cpp, source/main/network/Network.cpp
=> 🔧 Fixed some resource leaks

source/main/gui/panels/GUI_GameSettings.cpp
Moved the more important stuff up
=> Reordered the 'diag' settings

.gitmodules, source/CMakeLists.txt, source/main/CMakeLists.txt
This should also improve the cmake configure time 
Closes #1966
=> 🔧 Replaced FetchContent with git submodules

resources/scripts/base.as, source/main/gameplay/RoRFrameListener.cpp, source/main/gameplay/RoRFrameListener.h, source/main/physics/BeamForcesEuler.cpp, source/main/physics/collision/Collisions.cpp, source/main/physics/collision/Collisions.h, source/main/scripting/GameScript.cpp
A little Christmas present: Races are now once again enabled by default.
=> 🐛 Fixed broken race event logic

source/main/gameplay/Character.cpp
I can't find a better solution than to revert this part of the cleanup.
Reference: https://github.com/RigsOfRods/rigs-of-rods/pull/1918
=> Fixes camera jitter on some maps

resources/scripts/races.as, source/main/gameplay/RoRFrameListener.cpp, source/main/gameplay/RoRFrameListener.h, source/main/scripting/GameScript.cpp, source/main/scripting/GameScript.h, source/main/scripting/ScriptEngine.cpp, source/main/terrain/TerrainObjectManager.cpp, source/main/terrain/TerrainObjectManager.h
We no longer show all checkpoints on the overview map, but only those of the currently active race.
=> ✨ Only show relevant race icons

source/main/physics/RigSpawner.cpp
Reference: [SDSArgo_1.zip](http://archives.rigsofrods.net/repo/files/repofiles-4th-batch/SDSArgo_1.zip)
=> Fixed segfault on missing material

source/main/utils/Settings.cpp
Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/1982
=> 🐛 Fixed the shadow quality setting

source/main/CMakeLists.txt, source/main/plugins.cfg.in
=> 🐛 Fixed missing rendersystems

source/main/gfx/OgreSubsystem.cpp
Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/1960
=> 🔧 Attempt to fix the 'Rendering Device' setting

source/main/gameplay/RoRFrameListener.cpp
It does not really solve the underlying issue, but it fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/1859
At least as long as you don't have multiple instances of the same truck in the scene.
=> 🐛 Hot-fixed the truck reload (from disk) feature

source/main/gfx/IWater.h, source/main/gfx/Water.cpp, source/main/gfx/Water.h, source/main/terrain/TerrainManager.cpp
Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/1983
=> 🐛 Fixed the 'WaterBottomLine' terrn param

resources/OgreCore/OgreDebugPanel.overlay, resources/overlays/3d_dashblend.overlay, resources/overlays/3d_dashboard.overlay, resources/overlays/airdashboard.overlay, resources/overlays/airneedles.overlay, resources/overlays/boatdashboard.overlay, resources/overlays/boatneedles.overlay, resources/overlays/credits.overlay, resources/overlays/directionarrow.overlay, resources/overlays/engine.overlay, resources/overlays/loader.overlay, resources/overlays/machinedashboard.overlay, resources/overlays/needles.overlay, resources/overlays/various.overlay
https://github.com/RigsOfRods/rigs-of-rods/issues/1761
=> overlays update

source/main/gfx/OgreSubsystem.cpp
RoR will now show the default config dialog if something went wrong
=> 🐛 Fixed RoR crashing on invalid ogre.cfg

source/main/resources/CacheSystem.h, source/main/resources/ContentManager.cpp
The incremental cache update now also detects changes to the file sizes.
=> 🔧 Improved the cache validity check

source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/BeamFactory.cpp
|:---------:| :------:|
| ![pivot-before](https://user-images.githubusercontent.com/9437207/50605648-26919f00-0ec3-11e9-85ba-35d04c7b5b57.jpg) | ![pivot-after](https://user-images.githubusercontent.com/9437207/50605647-26919f00-0ec3-11e9-8660-3b3513d8e211.jpg) |
=> 🔧 Simplified and improved calculation of the pivot point

source/main/physics/RigSpawner.cpp
Fixes the automatic camera alignment on things like the '2ton-concretepipe poli'.
=> 🐛 Fixed the camera alignment on various loads

resources/mygui/Utils.layout, source/main/gui/panels/GUI_SimUtils.cpp, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/BeamFactory.cpp
Closes: https://github.com/RigsOfRods/rigs-of-rods/issues/242
=> 🎮 Revived the top speed indicator

source/main/gfx/GfxActor.cpp, source/main/gfx/GfxActor.h, source/main/gui/panels/GUI_TopMenubar.cpp, source/main/physics/BeamData.h, source/main/physics/BeamForcesEuler.cpp, source/main/physics/RigSpawner.cpp
Adds a rotators debug view mode:
* Turn rate (in rpm)
* Angular error (in milliradians)
=> ✨ Rotators debug info mode

source/main/physics/collision/Collisions.cpp, source/main/physics/collision/Collisions.h, source/main/terrain/TerrainGeometryManager.h, source/main/terrain/TerrainManager.cpp, source/main/terrain/TerrainManager.h, source/main/terrain/map/SurveyMapManager.cpp, source/main/terrain/map/SurveyMapManager.h
|:---------:| :------:|
| ![box-1](https://user-images.githubusercontent.com/9437207/50738700-6a441b80-11d7-11e9-9cb7-d2b4d7c2802f.jpg) | ![box-2](https://user-images.githubusercontent.com/9437207/50738701-6b754880-11d7-11e9-959d-a6b0d0d6b38d.jpg) |
| ![rock-1](https://user-images.githubusercontent.com/9437207/50738696-66b09480-11d7-11e9-98c9-74bc4735f459.jpg) | ![rock-2](https://user-images.githubusercontent.com/9437207/50738698-687a5800-11d7-11e9-9e72-b33b78e234fa.jpg) |
=> ✨ The overview map automatically crops into the terrain

source/main/terrain/TerrainGeometryManager.cpp, source/main/terrain/map/SurveyMapManager.cpp, source/main/terrain/map/SurveyMapTextureCreator.cpp, source/main/terrain/map/SurveyMapTextureCreator.h
We now pass te actual terrain height into the texture generator.
=> 🔧 Fixed the overview map on 'Ladoga Challenge'

source/main/gfx/GfxActor.cpp, source/main/gfx/GfxActor.h, source/main/gui/panels/GUI_TopMenubar.cpp
=> ✨ Submesh debug info mode

source/main/gfx/camera/CameraManager.cpp
This will pick even better camera angles.
=> 🔧 Various smaller static camera improvements

source/main/gfx/camera/CameraManager.cpp
- Fixes performances issues
- Fixes camera height issues with long vehicles (Buses, ...)
- Fixes flickering with fast and huge vehicles (Airplanes, ...)
=> 🔧 Final static cam revamp

source/main/resources/CacheSystem.cpp
Quit early and double the search speed.
=> 🔧 Optimized search for duplicate cache entries

source/main/gui/panels/GUI_MainSelector.cpp, source/main/resources/CacheSystem.cpp, source/main/resources/CacheSystem.h
- Removed the file hashing (it really makes no sense to hash the zips ...)
- Even better duplicate detection (now also handles files inside of folders)
- Prevents double deletion of obsolete files in the cache
- Much faster cache generation
=> 🔧 Further improved the duplicate detection

source/main/resources/CacheSystem.cpp, source/main/resources/CacheSystem.h
Fixes: https://github.com/RigsOfRods/rigs-of-rods/pull/2059
=> 🐛 Fixed typo

source/main/gameplay/RoRFrameListener.cpp, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/BeamFactory.cpp, source/main/physics/BeamForcesEuler.cpp, source/main/physics/RigSpawner.cpp
Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/2058
=> 🐛 Fixed the 'ropes' feature

source/main/physics/Beam.cpp, source/main/physics/BeamData.h, source/main/physics/RigSpawner.cpp
Ropes and ties need to have their own multilock counter
=> 🔧 Made the multilock feature compatible with ropes

source/main/physics/RigSpawner.cpp, source/main/physics/RigSpawner.h
This also improves the way managed materials are resolved for beams.
=> 🔧 Fixed the beam color of 'ropes'

source/main/Application.cpp, source/main/Application.h, source/main/gui/GUIUtils.cpp, source/main/gui/panels/GUI_GameSettings.cpp, source/main/physics/BeamForcesEuler.cpp, source/main/utils/Settings.cpp
=> 🎮 Added analog input smoothing/sensitivity settings

source/main/Application.cpp, source/main/Application.h, source/main/gui/GUIUtils.h, source/main/gui/panels/GUI_GameSettings.cpp, source/main/gui/panels/GUI_MultiplayerSelector.cpp, source/main/utils/Settings.cpp
Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/2035
=> 🔧 Various multiplayer lobby improvements

source/main/physics/BeamForcesEuler.cpp
This should reduce the amount of unnecessary truck resets.
=> 🔧 Better anti-explosion guard

source/main/resources/CacheSystem.cpp
Requires a full cache regen to take effect.
=> 🔧 Fixed the wheel entries in the cache

source/main/gfx/GfxActor.cpp, source/main/gfx/GfxActor.h, source/main/gui/panels/GUI_TopMenubar.cpp, source/main/physics/Beam.h, source/main/physics/SlideNode.cpp, source/main/physics/SlideNode.h
=> ✨ Slidenodes debug info mode

source/main/physics/BeamForcesEuler.cpp
Fixes: https://github.com/RigsOfRods/rigs-of-rods/pull/2041
=> 🔧 Fixed the commands2 press once logic

resources/skeleton/config/input.map, source/main/gameplay/RoRFrameListener.cpp, source/main/utils/InputEngine.cpp, source/main/utils/InputEngine.h
=> 🎮 New FOV reset shortcut

source/main/gfx/camera/CameraManager.cpp
This should make the free camera mode a lot more pleasant to use.
=> 🔧 Tuned the free camera movement speed

source/main/gameplay/RoRFrameListener.cpp, source/main/gameplay/Road2.cpp, source/main/physics/collision/Collisions.cpp, source/main/physics/collision/Collisions.h, source/main/terrain/TerrainObjectManager.cpp, source/main/terrain/TerrainObjectManager.h
- Teleport support
- Dynamic object list update
- Object removal support (truck remove shortcut)
Reverts some parts of: https://github.com/RigsOfRods/rigs-of-rods/commit/c10eff05d22aa4ca71f8e357a519f790b7befb78
=> 🔧 Minor terrain editor improvements 

source/main/gameplay/RoRFrameListener.cpp, source/main/gameplay/RoRFrameListener.h
We can run the same ground collisions avoidance logic for all spawn methods.
=> 🔧 Duplicate code removal

source/main/MainMenu.cpp, source/main/gameplay/AircraftSimulation.cpp, source/main/gameplay/LandVehicleSimulation.cpp, source/main/gameplay/RoRFrameListener.cpp, source/main/gfx/camera/CameraManager.cpp, source/main/gfx/camera/CameraManager.h, source/main/gui/panels/GUI_TopMenubar.cpp, source/main/gui/panels/GUI_TopMenubar.h, source/main/network/Network.cpp, source/main/physics/Beam.cpp, source/main/physics/BeamFactory.cpp, source/main/physics/BeamFactory.h, source/main/physics/Savegame.cpp
- Fixed the performance issue with the new 'Saves' tab in the top menu
- Fixed camera not being updated after loading a savegame
- Fixed camera not being updated during sync reset
- Fixed cruise control being disabled during soft reset
- Fixed wheel speed not being handled correctly
- Fixed main menu save game shortcut picking the wrong file
- Shrinked the save game file size (and improved the load speeds)
**Not compatible with existing savegames**
=> 🔧 Various savegame related improvements

source/main/gfx/GfxActor.cpp, source/main/gfx/Skidmark.cpp, source/main/gfx/Skidmark.h, source/main/physics/Beam.cpp, source/main/physics/Beam.h
- Fixed the skidmark generation on the wheels on the right hand side of the truck
- Attempt to fix excessive skidmark generation during slow motion
- Attempt to fix the 'huge spark' issue
- Removed some dead code
=> 🔧 Particle & skidmark fixes

source/main/gameplay/SkinManager.cpp, source/main/gameplay/SkinManager.h, source/main/physics/Savegame.cpp
**Not compatible with existing savegames**
=> 🔧 Fixed skin/section config missing in savegames

source/main/gameplay/RoRFrameListener.cpp, source/main/physics/Savegame.cpp
- Only restore the time of day if the terrain is changed
- Reset the terrain preset after usage
=> 🔧 Small savegame fixes

source/main/physics/air/TurboJet.cpp, source/main/physics/air/TurboProp.cpp
Fixes: https://github.com/RigsOfRods/rigs-of-rods/pull/2116
=> 🔧 Fix turbo- jet/prop cleanup

resources/caelum/RoRSkies.os, source/main/Application.cpp, source/main/Application.h, source/main/gameplay/Character.cpp, source/main/gfx/GfxActor.cpp, source/main/gfx/GfxActor.h, source/main/gfx/camera/CameraManager.cpp, source/main/gfx/camera/CameraManager.h, source/main/gui/GUIUtils.cpp, source/main/gui/panels/GUI_GameSettings.cpp, source/main/gui/panels/GUI_TopMenubar.cpp, source/main/gui/panels/GUI_TopMenubar.h, source/main/physics/BeamFactory.cpp, source/main/utils/Settings.cpp
**Note:** Requires `make zip_and_copy_resources` to update the default caelum config.
=> 🎮 Realtime top menu settings

source/main/gui/panels/GUI_LoadingWindow.cpp, source/main/gui/panels/GUI_LoadingWindow.h
Improves on: https://github.com/RigsOfRods/rigs-of-rods/pull/2124
=> 🔧 Decreased loading window overhead

source/main/gui/panels/GUI_TopMenubar.cpp, source/main/gui/panels/GUI_TopMenubar.h
Moved all system calls out of the rendering loop.
=> 🔧 Top menu optimization

source/main/utils/MeshObject.cpp, source/main/utils/MeshObject.h
This emerged out of the attempt to fix: https://github.com/RigsOfRods/rigs-of-rods/issues/2118, apparently caused by: https://github.com/RigsOfRods/rigs-of-rods/commit/0b577792fc3a33b5d6322976a0b6458e7224a0a8.
This basically just removes dead code.
=> 📐 MeshObject cleanup

source/main/gameplay/Character.cpp, source/main/physics/BeamFactory.cpp
They broke in: https://github.com/RigsOfRods/rigs-of-rods/commit/ca4af0f6b194cab6f93eef3be1c8ea73535987a5
=> 🐛 Fixed various net label issues

source/main/RoRPrerequisites.h, source/main/gfx/GfxActor.cpp, source/main/gfx/GfxActor.h, source/main/physics/BeamFactory.cpp, source/main/physics/BeamFactory.h, source/main/physics/RigSpawner.cpp, source/main/physics/RigSpawner.h, source/main/resources/CacheSystem.cpp, source/main/resources/ContentManager.cpp, source/main/resources/ContentManager.h
Solution: One global custom resource group for all mods.
* Properly fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/2118
* Fixes the newly introduced issues of: https://github.com/RigsOfRods/rigs-of-rods/commit/d80de3da1d1b5c20a789577d9bc9ce38d347820b
* Adds a new `/mods` folder. Deprecates `/packs`, removes the `/terrains` and `/vehicles`.
You can organize your content (in folders) inside of the `/mods` folder as you like.
=> 🔧 Another attempt to fix the resource group handling

source/main/resources/ContentManager.cpp
We might as well use the global actor group for this.
=> 📐 Removed duplicate code

source/main/resources/rig_def_fileformat/RigDef_Parser.cpp
Related: https://github.com/RigsOfRods/rigs-of-rods/issues/1609#issuecomment-442240938
Related: https://github.com/RigsOfRods/rigs-of-rods/commit/6cf1d458318d180c0c4987f668ab99ce06ca0025
=> 🐛 Attempt to fix the managed material bug

source/main/resources/CacheSystem.cpp
1. We failed to destroy all temporary resource groups during cache regen:
* Fixes `ItemIdentityException: Entity is not animated in Entity::getAnimationState`
2. We falsely reported unzipped content as not loaded:
* Fixes missing actors on maps (Community Map, North St Helens, ...)
=> 🐛 Fixed broken resource handling

source/main/Application.cpp, source/main/Application.h, source/main/MainMenu.cpp, source/main/gui/panels/GUI_GameSettings.cpp, source/main/gui/panels/GUI_LoadingWindow.cpp, source/main/gui/panels/GUI_LoadingWindow.h, source/main/resources/CacheSystem.cpp, source/main/resources/CacheSystem.h, source/main/resources/ContentManager.cpp, source/main/utils/Settings.cpp
Closes: https://github.com/RigsOfRods/rigs-of-rods/pull/2083
=> 🎮 In-game cache regen (main menu only)

source/main/gui/panels/GUI_MainSelector.cpp, source/main/gui/panels/GUI_MainSelector.h, source/main/resources/CacheSystem.cpp, source/main/resources/CacheSystem.h, source/main/utils/Utils.cpp, source/main/utils/Utils.h
* Further improves the speed of incremental cache updates
* Improves the content selection in the 'fresh' category
=> 📐 Reduced the timestamp mess

source/main/gameplay/RoRFrameListener.cpp, source/main/gui/panels/GUI_GameConsole.cpp, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/BeamFactory.cpp, source/main/physics/RigSpawner.cpp, source/main/physics/RigSpawner.h
Clean rewrite of the actor spawn position and rotation logic.
=> 📐 Simplified the 'ResetPosition' logic

source/main/Application.cpp, source/main/Application.h, source/main/gfx/GfxActor.cpp, source/main/gui/panels/GUI_GameSettings.cpp, source/main/gui/panels/GUI_TopMenubar.cpp, source/main/utils/Settings.cpp
=> 🎮 Additional debug view settings

source/main/gui/panels/GUI_MainSelector.cpp, source/main/resources/CacheSystem.cpp, source/main/resources/CacheSystem.h
=> 🔧 Removed 'rollon' from the selector window

source/main/physics/BeamFactory.cpp, source/main/resources/CacheSystem.cpp, source/main/resources/CacheSystem.h, source/main/resources/rig_def_fileformat/RigDef_Parser.cpp, source/main/resources/rig_def_fileformat/RigDef_Parser.h
The group is either `RGN_TEMP` or `RGN_CONTENT`.
=> 🔧 Fixed the resource exists lookup

source/main/physics/Beam.cpp
Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/2151
=> 🐛 Fixed infinite recursion

source/main/gfx/DustManager.cpp, source/main/gfx/DustManager.h, source/main/gfx/GfxActor.cpp, source/main/gfx/GfxActor.h
Fixes: https://github.com/RigsOfRods/rigs-of-rods/commit/b6f694965cf225f34f2dafb147334545c3292832
=> 🐛 Fixed particles on paused actors

source/main/physics/BeamFactory.cpp, source/main/physics/BeamFactory.h
I think it's time to ditch the 20% overscale of the static bounding boxes.
=> 🔧 Simplified bounding box checks

source/main/resources/rig_def_fileformat/RigDef_Parser.cpp
Roughly 3% faster truck file parsing.
=> 🔧 Slightly faster keyword parsing

source/main/Application.cpp, source/main/Application.h, source/main/gui/panels/GUI_MultiplayerSelector.cpp, source/main/gui/panels/GUI_MultiplayerSelector.h, source/main/network/Network.cpp, source/main/utils/Settings.cpp
The hash of the user token was never supposed to be stored in the RoR.cfg.
=> 🐛 Fixed the user token logic

source/main/gfx/camera/CameraManager.cpp, source/main/physics/collision/Collisions.cpp, source/main/physics/collision/Collisions.h
Selects close to perfect positions, inside and outside of buildings.
=> ✨ Further improved static camera

resources/skeleton/config/input.map, source/main/gameplay/LandVehicleSimulation.cpp, source/main/gameplay/RoRFrameListener.cpp, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/utils/InputEngine.cpp
- Trailer parking brake vs. parking brake
- Respawn last truck vs. blink left
=> 🔧 Fixed some input map conflicts

source/main/resources/CacheSystem.cpp
=> 🔧 Disable console echo during cache regen

source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/BeamFactory.cpp, source/main/physics/BeamFactory.h, source/main/scripting/ScriptEngine.cpp, source/main/terrain/TerrainManager.cpp
> this recalcs the masses, useful when the gravity was changed...
Of course ... :man_facepalming: 
... https://github.com/ulteq/ror-legacy-svn-trunk/commit/195974824166515bc38e3f52c8387a653be4b837
=> 📐 Removed ridiculous code

source/main/gui/panels/GUI_MainSelector.cpp, source/main/gui/panels/GUI_MainSelector.h
This will remember the previously selected category and entry.
=> 🔧 Remember last selector window selection

source/main/gameplay/Character.h, source/main/gameplay/RoRFrameListener.cpp
Finishes: https://github.com/RigsOfRods/rigs-of-rods/pull/2214
=> 🔧 Minor cleanup

source/main/gameplay/CharacterFactory.cpp, source/main/gameplay/CharacterFactory.h, source/main/gameplay/RoRFrameListener.cpp
Related with segfault 1 in: https://github.com/RigsOfRods/rigs-of-rods/issues/2178
=> 🐛 Fixed actor coupling segfault in multiplayer

source/main/gameplay/Character.cpp, source/main/gameplay/Character.h, source/main/network/Network.cpp, source/main/physics/Beam.cpp
Goes hand in hand with: https://github.com/RigsOfRods/ror-server/pull/78
=> 🔧 Another attempt to reduce the network latency

source/main/physics/Beam.cpp, source/main/physics/Beam.h
It was a pretty desperate idea in the first place.
=> 🔧 Simplified position interpolation

source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/physics/BeamFactory.cpp
Less deformation on remote actors.
=> 🔧 Improved node position compression

source/main/gameplay/RoRFrameListener.cpp
It now automatically picks the closest match.
=> 🔧 Further improved cache entry lookup

source/main/gameplay/Character.cpp, source/main/physics/Beam.cpp, source/main/physics/Beam.h
Does the job for now. We can improve this later on.
Fixes: https://github.com/RigsOfRods/rigs-of-rods/pull/2234
=> 🔧 Fixed flaws in the stream time offset calculation

source/main/network/Network.cpp, source/main/network/RoRnet.h
Goes hand in hand with: https://github.com/RigsOfRods/ror-server/pull/80
=> 🔧 Recv fix

source/main/physics/BeamFactory.cpp
- The new stream data interpolation is not yet capable of handling variable update rates
- For now all trucks (including the sleeping ones) need to send regular stream data updates
=> 🐛 Fixed multiplayer conflict with sleeping trucks

source/main/gameplay/RoRFrameListener.cpp
The bug was introduced with: https://github.com/RigsOfRods/rigs-of-rods/commit/3c0e95bcd2a37c1686374377627a11f45b18addc
=> 🐛 Fixed bug in the savegame logic

source/main/Application.cpp, source/main/Application.h, source/main/gui/panels/GUI_GameSettings.cpp, source/main/scripting/GameScript.cpp, source/main/utils/Settings.cpp
This new setting allows you to disable the automatic race result submission
=> 🔧 Added disable online api setting

source/main/gameplay/RoRFrameListener.cpp
Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/2257
=> 🐛 Fixed custom particle key conflict

source/main/gameplay/RoRFrameListener.cpp, source/main/physics/Beam.h
Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/2252
=> 🐛 Fixed skin selection on vehicle reload

source/main/gui/panels/GUI_VehicleDescription.cpp
Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/2248
=> 🐛 Fixed the vehicle description output

resources/overlays/directionarrow.overlay, resources/overlays/various.overlay, resources/scripts/races.as, source/main/gameplay/RoRFrameListener.cpp, source/main/gameplay/RoRFrameListener.h, source/main/gfx/DustManager.cpp, source/main/gfx/DustManager.h, source/main/gui/OverlayWrapper.cpp, source/main/gui/OverlayWrapper.h, source/main/scripting/GameScript.cpp, source/main/scripting/GameScript.h, source/main/scripting/ScriptEngine.cpp
Quick & dirty solution to get basic lap time info.
=> 🎮 Revived the lap-time overlay

source/main/physics/Beam.cpp, source/main/physics/BeamFactory.cpp, source/main/physics/BeamFactory.h
- Better stream data handling
- Better net time offset calculation
- Actors now spawn simultaneously on all clients
Requires: https://github.com/RigsOfRods/ror-server/commit/0bce96692a65d286d04e73fc001feec4e8c63550
=> 🔧 Network delay fix

resources/scripts/races.as
The "you needed.." part always confused me.
=> Changed race finish message

source/main/gameplay/RoRFrameListener.cpp, source/main/gameplay/RoRFrameListener.h, source/main/gameplay/SceneMouse.cpp
=> 🎮 Terrain editor object selection via mouse

source/main/gfx/GfxActor.cpp, source/main/gfx/GfxActor.h, source/main/physics/collision/DynamicCollisions.cpp, source/main/physics/flex/FlexBody.cpp, source/main/physics/flex/FlexBody.h
They broke in: https://github.com/RigsOfRods/rigs-of-rods/commit/5aa586c015ebb91cb5792c7a064db8975b752f60
=> 🐛 Fixed the damage texture blending

source/main/terrain/TerrainObjectManager.cpp
Reverts: https://github.com/RigsOfRods/rigs-of-rods/commit/b4b5f740e8987d9c617450ab084c6a71805d1b89
Reference: https://github.com/RigsOfRods/ogre-pagedgeometry/blob/1cbdace762be50eda6a20047ca9e917f38beb958/source/TreeLoader3D.cpp#L122
=> 🐛 Fixed paged geometry scaling issue

source/main/gui/panels/GUI_GameConsole.cpp
Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/2285
=> 🐛 Various console fixes

source/main/physics/Beam.h, source/main/scripting/ScriptEngine.cpp
Useful to monitor the actual vehicle speed on race events.
=> 🔧 Added actor 'getSpeed()' script function

source/main/resources/CacheSystem.cpp
=> Build fix for 32-bit Linux

source/main/gui/GUIInputManager.cpp, source/main/gui/GUIManager.cpp, source/main/gui/GUIManager.h, source/main/gui/panels/GUI_TopMenubar.h
It's ugly, but it works.
Related with: https://github.com/RigsOfRods/rigs-of-rods/issues/2205
=> 🔧 TopMenubar input grabbing hack

source/main/gfx/GfxActor.cpp
Fixes: https://github.com/RigsOfRods/rigs-of-rods/issues/2305
=> 🐛 Fixed rotators debug view crash

source/main/gui/DashBoardManager.cpp, source/main/gui/DashBoardManager.h
Fixes #2315
Update: Just tested with debugger, it works exactly as supposed to.
=> Eliminated "minus zero" value on dashboards

source/main/gfx/DustManager.cpp, source/main/gfx/GfxActor.cpp, source/main/gfx/GfxActor.h, source/main/physics/Beam.cpp, source/main/physics/BeamFactory.cpp, source/main/physics/RigSpawner.cpp, source/main/physics/RigSpawner_ProcessControl.cpp, source/main/physics/flex/FlexAirfoil.cpp, source/main/physics/flex/FlexAirfoil.h
Fixes #2306
Quick and dirty fix, no time left to test.
=> Wing visuals now updated asynchronously

source/main/physics/RigSpawner.cpp, source/main/physics/RigSpawner_ProcessControl.cpp, source/main/physics/flex/FlexAirfoil.cpp, source/main/physics/flex/FlexFactory.cpp, source/main/physics/flex/FlexFactory.h, source/main/physics/flex/FlexMesh.cpp, source/main/physics/flex/FlexMeshWheel.cpp, source/main/physics/flex/FlexObj.cpp, source/main/resources/CacheSystem.cpp, source/main/resources/ContentManager.cpp, source/main/resources/ContentManager.h, source/main/terrain/TerrainObjectManager.cpp, source/main/utils/MeshObject.cpp, source/main/utils/MeshObject.h
Fixes #2280 
Turns out we don't need OGRE's STRICT mode, just one extra flag for resource groups (and no bugs on our end).
=> Fixed resource name conflicts between mods

resources/managed_materials/shadows/pssm/on/depthshadows.program, resources/managed_materials/shadows/pssm/on/shared/pssm_shared.program, source/main/resources/ContentManager.cpp, source/main/resources/ContentManager.h
Introduced by https://github.com/RigsOfRods/rigs-of-rods/pull/2294
=> Fixed crash when PSSM are enabled

source/main/gui/panels/GUI_MainSelector.cpp
=> Selector GUI: Don't reset sectionconfig when choosing skin

source/main/physics/flex/FlexFactory.cpp
Introduced by https://github.com/RigsOfRods/rigs-of-rods/issues/2243
Kudos to @CuriousMike56 for reporting and @tritonas00 for investigating.
=> Fixed re-loading [flexbody/mesh]wheels

source/main/gui/panels/GUI_MainSelector.cpp, source/main/gui/panels/GUI_MainSelector.h
Selector UI was resetting the sectionconfig when LT_Skin mode was activated.
Fixes #2361
=> Fixed sectionconfig not working with skins

tools/CI/upload-CI-build.sh, tools/linux/RunRoRConfig
- Removed leftover `RunRoRConfig`
- Removed leftover wxWidgets libs
- Fixed https://github.com/RigsOfRods/rigs-of-rods/issues/2321
=> Travis cleanup

source/main/gameplay/RoRFrameListener.cpp
Fixes https://github.com/RigsOfRods/rigs-of-rods/issues/2379
=> :bug: Fixed rotation logging

source/main/Application.h
=> 🐛 Fixed the game logging mp_player_token

resources/SkyX/SkyXDefault.skx, source/main/gfx/skyx/VClouds/DataManager.cpp, source/main/gui/panels/GUI_GameSettings.cpp, source/main/terrain/TerrainManager.cpp
- Fixed https://github.com/RigsOfRods/rigs-of-rods/pull/2147#issuecomment-458121206 and removed duplicated code (thanks to @paroj https://github.com/paroj/SkyX/commit/4b68e3ce77e958073fb734eb38bb6ca199bf1f17)
- Forced unlimited sight range (fixes https://github.com/RigsOfRods/rigs-of-rods/issues/2389)
- Changed initial time to make things brighter at startup
Before:
After:
=> SkyX fixes

resources/dashboards/default_dashboard.layout, resources/dashboards/default_dashboard3500.layout, resources/dashboards/default_dashboard3500_analog.layout, resources/dashboards/default_dashboard3500_analog_mph.layout, resources/dashboards/default_dashboard3500_mph.layout, resources/dashboards/default_dashboard7000.layout, resources/dashboards/default_dashboard7000_analog.layout, resources/dashboards/default_dashboard7000_analog_mph.layout, resources/dashboards/default_dashboard7000_mph.layout, resources/dashboards/default_dashboard_boat.layout
Fixes https://github.com/RigsOfRods/rigs-of-rods/issues/619
Reference:
http://mygui.info/docs/struct_my_g_u_i_1_1_widget_style.html#ab5d1c9327d5b4f00dd432c2634b902bb
=> Fixed SpeedoNeedle overlapping

doc/angelscript/BeamClass.h, source/main/gameplay/AircraftSimulation.cpp, source/main/gameplay/AutoPilot.cpp, source/main/gameplay/AutoPilot.h, source/main/gfx/GfxActor.cpp, source/main/gfx/GfxActor.h, source/main/gui/OverlayWrapper.cpp, source/main/gui/OverlayWrapper.h, source/main/physics/Beam.cpp, source/main/physics/Beam.h, source/main/scripting/ScriptEngine.cpp
Fixes #1560
UPDATE: Original solution scrapped, see https://github.com/RigsOfRods/rigs-of-rods/pull/2403#issuecomment-518029318
=> Fixed air dashboard showing previous vehicle's state

conanfile.txt
=> Use OpenSSL 1.1.1

source/main/gfx/GfxActor.cpp, source/main/gfx/GfxActor.h, source/main/physics/RigSpawner.cpp, source/main/physics/air/AeroEngine.h, source/main/physics/air/TurboJet.cpp, source/main/physics/air/TurboJet.h, source/main/physics/air/TurboProp.h
Finished late at night, not tested, beware.
=> Turbojet fixes and cleanups

source/main/gfx/OgreSubsystem.cpp
This fixes the issue with players resizing the game window and breaking the GUI
=> 🔧 Set window border to fixed

conanfile.txt
=> 🔧 Update OGREdeps to 2019-04 

source/main/network/Network.cpp, source/main/physics/BeamFactory.cpp, source/main/scripting/GameScript.cpp, source/main/scripting/OgreScriptBuilder.cpp, source/main/utils/Utils.cpp, source/main/utils/Utils.h
See https://github.com/RigsOfRods/rigs-of-rods/issues/2419
=> Bugfix: send hashed user token to server API

source/main/gui/panels/GUI_GameAbout.cpp
=> Updated game credits

source/main/resources/CacheSystem.cpp, source/main/resources/ContentManager.cpp
=> Fixed unzipping mods causing materials not to load

source/main/physics/Beam.cpp, source/main/physics/CmdKeyInertia.cpp, source/main/physics/CmdKeyInertia.h
See #2435
One fix and usual slew of unnecessary cleanups. I did them in small chunks to make reviewing easier.
=> Hotfix: Hydro inertia reset upon vehicle reset

conanfile.txt, source/main/Application.cpp, source/main/Application.h, source/main/CMakeLists.txt, source/main/gameplay/RoRFrameListener.cpp, source/main/gui/panels/GUI_GameSettings.cpp, source/main/main.cpp, source/main/terrain/TerrainManager.cpp, source/main/utils/Settings.cpp, source/main/utils/Utils.cpp, source/main/utils/Utils.h
=> 🎮 Added Discord Rich Presence

source/main/gui/OverlayWrapper.cpp, source/main/gui/OverlayWrapper.h
=> Aero dashboard: hide unused throttles & starters

cmake/3rdparty/pmm.cmake
See https://github.com/AnotherFoxGuy/pmm/releases/tag/1.7.0 for the changelog
=> ⬆️ Upgrade PMM to 1.7.0

source/main/terrain/TerrainObjectManager.cpp
=> Fixed crash when collision mesh is not defined in odef

resources/managed_materials/managed_mats_vehicles_nicemetal.material, resources/managed_materials/managed_mats_vehicles_transparent_nicemetal.material, resources/managed_materials/nicemetal_mm.cg, resources/managed_materials/nicemetal_mm.program, source/main/Application.cpp, source/main/Application.h, source/main/gui/panels/GUI_GameSettings.cpp, source/main/physics/RigSpawner.cpp, source/main/utils/Settings.cpp
Since I don't see the NiceMetal shader getting shadow support anytime soon (https://github.com/RigsOfRods/rigs-of-rods/issues/2444#issuecomment-532035335) and it really needs to be included in upstream, I figured it would be best to just add a settings option to toggle them for now.
Closes #2444
=> Added settings option to enable classic (NiceMetal) shader

CMakeLists.txt, cmake/GenerateVersionInfo.cmake, source/main/main.cpp, source/version_info/CMakeLists.txt, source/version_info/RoRVersion.cpp.in, source/version_info/RoRVersionDef.h.in
Closes #2415
**Changes**
* CMake will now automatically generate a version number based on the date of the build
* Moved the user dir on windows to `My Games/Rigs of Rods`
=> ✨ Switched from semver to rolling releases

source/main/utils/Utils.cpp
=> Improved Discord Rich Presence

source/main/network/RoRnet.h
This is preparation for the next release.
Supporting PR: https://github.com/RigsOfRods/ror-server/pull/100
=> Bump RoRNet version to 2.42

source/main/gui/panels/GUI_TopMenubar.cpp
See https://github.com/RigsOfRods/rigs-of-rods/pull/2481#issuecomment-579423118
=> Hide 'physics paused' box with GUI

source/main/utils/Settings.cpp
=> Include joinsever option when showing cmdline usage

source/main/gui/imgui/imgui.cpp
It was cleared in every frame.
=> Fixed scrolling via mouse wheel while in simulation

source/main/gui/panels/GUI_SimActorStats.cpp
also added new line before G-forces
=> Swapped Kw/HP in SimActorStats panel

source/main/gui/panels/GUI_MultiplayerClientList.cpp
=> Cleaned up MP Client List window size code

source/main/ForwardDeclarations.h, source/main/gameplay/RoRFrameListener.cpp, source/main/gui/GUIManager.cpp, source/main/gui/GUIManager.h
Introduced in e23ea80ad43e7650c0aae5de8a5ed25be18be043
Reported by @tritonas00 👍
=> Hotfix: Truck stats not being updated

source/main/gui/panels/GUI_SimActorStats.cpp
two are enough, and also made the window auto resizable
=> Removed extra decimals in SimActorStats panel

source/main/gui/panels/GUI_ConsoleView.cpp
Also cleaned up icon drawing code
=> Added script icon

source/main/gui/panels/GUI_ConsoleView.cpp, source/main/gui/panels/GUI_ConsoleView.h
=> Cleaned up icon drawing code

source/main/scripting/GameScript.cpp
=> Prevent potential segfault

source/main/gameplay/RoRFrameListener.cpp
fixes https://github.com/RigsOfRods/rigs-of-rods/issues/2513
introduced in https://github.com/RigsOfRods/rigs-of-rods/commit/c8b5ebaf66c87ade96d477fcd7631ec5f89d9c01
needs testing first
=> Don't update simulation when paused+multiplayer

source/main/gui/GUIManager.h, source/main/gui/panels/GUI_ConsoleView.cpp, source/main/gui/panels/GUI_MainSelector.cpp
=> Updated highlight text color

source/main/gui/GUIManager.cpp, source/main/gui/GUIManager.h, source/main/gui/panels/GUI_ConsoleView.cpp, source/main/gui/panels/GUI_GameAbout.cpp, source/main/gui/panels/GUI_MainSelector.cpp, source/main/gui/panels/GUI_SimActorStats.cpp
and changed Close Button color also
thanks @CuriousMike56 for feedback
=> Resurrected blue text color

source/main/gui/panels/GUI_MainSelector.cpp
fixes https://github.com/RigsOfRods/rigs-of-rods/issues/2535
=> Selector: ignore invalid mini images

source/main/gui/panels/GUI_SimActorStats.cpp
=> SimActorStats: Removed dead decimals 

source/main/CMakeLists.txt, source/main/gui/GUIManager.cpp, source/main/gui/GUIManager.h, source/main/gui/panels/GUI_GameControls.cpp, source/main/gui/panels/GUI_GameControls.h, source/main/gui/panels/GUI_TopMenubar.cpp, source/main/utils/InputEngine.cpp, source/main/utils/InputEngine.h
=> Added Game Controls panel

source/main/gameplay/RoRFrameListener.cpp, source/main/gfx/GfxScene.cpp, source/main/gfx/GfxScene.h, source/main/gfx/camera/CameraManager.cpp, source/main/gui/GUIUtils.cpp, source/main/gui/panels/GUI_GameSettings.cpp, source/main/gui/panels/GUI_TopMenubar.cpp, source/main/system/CVar.cpp, source/main/system/CVar.h, source/main/system/Console.h, source/main/utils/Settings.cpp
Some much needed fixes after merging #2486 -  sorry about being sloppy.
* Restored trace logging of CVars (formerly GVars)
* Fixed 'app_screenshot_format' getting corrupted, causing crash upon screenshot.
* Fixed FOV being saved to configfile even if not supposed to - again.
=> CVar fixes

source/main/gui/panels/GUI_TopMenubar.cpp
=> Fixed "Toggle/Cycle with" text in TopMenubar

conanfile.txt, source/main/CMakeLists.txt
Note: please remove the old version of openssl with `conan remove openssl`
=> Updated Conan packages

source/main/gui/panels/GUI_ConsoleView.cpp, source/main/gui/panels/GUI_ConsoleView.h
Original draft code from Petr, edited and applied in notification/chat area.
Demo video: https://streamable.com/opiw67
=> Fade out expired messages

source/main/gfx/GfxScene.cpp
- Fixes first comment in https://github.com/RigsOfRods/rigs-of-rods/issues/2566
- Fixes controlling cinecam fov from top menu
Introduced with https://github.com/RigsOfRods/rigs-of-rods/commit/9b037a8a48ef8c08e7204e2752e15e4389aacc1f
=> Cinecam fov fixes

source/main/MainMenu.cpp
fixes https://github.com/RigsOfRods/rigs-of-rods/issues/2337
=> Process script commands after terrain is loaded

source/main/RoRPrerequisites.h, source/main/datatypes/node_t.h, source/main/gameplay/Character.h, source/main/gameplay/SceneMouse.h, source/main/gfx/MovableText.h, source/main/gfx/SurveyMapTextureCreator.h, source/main/gui/panels/GUI_GameSettings.cpp, source/main/gui/panels/GUI_LoadingWindow.h, source/main/gui/panels/GUI_TopMenubar.h, source/main/network/Network.h, source/main/physics/BeamData.h, source/main/physics/Differentials.h, source/main/utils/ImprovedConfigFile.h, source/main/utils/PlatformUtils.h, source/main/utils/Str.h, source/main/utils/Utils.h, source/main/utils/WriteTextToTexture.h
Fixes building RoR without cotire. Thanks @paroj for exposing the issue.
=> Added missing includes

source/main/gui/panels/GUI_LoadingWindow.cpp, source/main/gui/panels/GUI_LoadingWindow.h
Brings back ulteq's https://github.com/RigsOfRods/rigs-of-rods/pull/2127
=> Fixed slow cache regen

source/main/gameplay/RoRFrameListener.cpp
Fixes https://github.com/RigsOfRods/rigs-of-rods/issues/2378
=> Untie actor before removal

source/main/gameplay/RoRFrameListener.cpp
- Moved editor output file to logs dir
- Editor output file is also now written when we are in `EDITOR_MODE` and exit RoR
Requested from discord
=> Editor output file changes

.travis.yml, CMakeLists.txt, cmake/DependenciesConfig.cmake, source/angelscript_addons/CMakeLists.txt, source/main/CMakeLists.txt, source/main/phc.h, source/main/physics/Savegame.cpp
=> 🔧 Replaced cotire with target_precompile_headers

tools/CI/upload-CI-build.sh
Should fix https://github.com/RigsOfRods/rigs-of-rods/issues/2586
=> Updated libraw version for bionic

source/main/physics/air/TurboJet.cpp
Demo video: https://streamable.com/pgiwaz
=> Added turbojet reverse

source/main/GameContext.cpp
Should fix https://github.com/RigsOfRods/rigs-of-rods/issues/2583
=> Unlock actor before remove

source/main/resources/rig_def_fileformat/RigDef_Parser.cpp
increase maximum gear limit in RoR
=> Increase maximum gear limit(unlimited in future)

.travis.yml, tools/CI/upload-CI-build.sh
This will now automatically install the latest version of cmake and conan
=> 🔧 Use AnotherFoxGuy/ci-scripts for installing devtools

source/main/gui/imgui/OgreImGuiOverlay.cpp, source/main/gui/imgui/imgui.h, source/main/gui/imgui/imgui_draw.cpp
=> Unicode support in UI

cmake/Macros.cmake
Now zip_and_copy_resources will properly update the zip when a file has been changed
=> 🐛 Fixed zip_and_copy_resources not re-zipping on a file update

source/main/gui/GUIManager.h, source/main/gui/GUIUtils.cpp, source/main/gui/GUIUtils.h, source/main/gui/panels/GUI_ConsoleView.cpp, source/main/gui/panels/GUI_ConsoleView.h, source/main/gui/panels/GUI_MainSelector.cpp, source/main/physics/Actor.cpp
=> Restored text coloring in SelectorUI

source/main/gui/panels/GUI_SimActorStats.cpp
shamelessly copy-pasting Petr's code  :blush:
=> Enable vehicle name color in actor stats

source/main/Application.cpp, source/main/Application.h, source/main/GameContext.cpp, source/main/GameContext.h, source/main/gfx/Renderdash.cpp, source/main/gfx/Renderdash.h, source/main/gui/GUIManager.cpp, source/main/gui/GUIUtils.cpp, source/main/gui/GUIUtils.h, source/main/gui/panels/GUI_ConsoleView.cpp, source/main/gui/panels/GUI_DirectionArrow.cpp, source/main/gui/panels/GUI_DirectionArrow.h, source/main/gui/panels/GUI_GameSettings.cpp, source/main/gui/panels/GUI_MainSelector.cpp, source/main/gui/panels/GUI_SimActorStats.cpp, source/main/gui/panels/GUI_TopMenubar.cpp, source/main/main.cpp, source/main/network/Network.cpp, source/main/network/Network.h, source/main/physics/ActorManager.cpp, source/main/physics/Savegame.cpp, source/main/physics/SimData.h, source/main/physics/flex/FlexFactory.cpp, source/main/physics/flex/FlexFactory.h, source/main/resources/CacheSystem.cpp, source/main/resources/CacheSystem.h, source/main/system/AppCommandLine.cpp, source/main/system/CVar.cpp, source/main/system/ConsoleCmd.cpp, source/main/terrain/TerrainObjectManager.cpp
TODO:
* ...
DONE:
*  keep nicknames in chat visible after player disconnects - now shown as "Myname [offline]: Hello!"
*  bugfix - values from commandline (MP server, terrain, vehicle) propagate to RoR.cfg
* bugfix - preselected vehicle spawns with cab not visible
*  ui - remove the PhysicsTimeStep slider from TopMenubar
* bugfix - some vehicles (i.e. Desperado) lose prop visuals on respawn.
*  ui - remove the PhysicsTimeStep slider from GameSettings, too
GEEKY:
=> Final touches before release (well, almost)

source/main/gfx/camera/CameraManager.cpp
Fixes:
which started since https://github.com/RigsOfRods/rigs-of-rods/pull/2047
=> Fixed airplane artifacts with static cam

source/main/physics/Actor.cpp
Closes https://github.com/RigsOfRods/rigs-of-rods/issues/2480
=> Changed speedometer to wheel speed

source/main/main.cpp
Save scene when we exit simulation
=> Auto save on exit

source/main/gui/panels/GUI_TopMenubar.cpp
Fixes #2668 
Replaced `fmt::memory_buffer` with `fmt::format`
=> 🐛 Fixed broken vehicle-list

source/main/gui/panels/GUI_MainSelector.cpp
=> Enlarged selector buttons

source/main/main.cpp
Main menu not showing when https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/network/Network.cpp#L427 happens
=> Fixed main menu not showing after connect failure

source/main/AppContext.cpp
=> Fixed window icon

source/main/gui/imgui/OgreImGui.cpp, source/main/gui/imgui/imgui.h, source/main/gui/imgui/imgui_widgets.cpp
Trying to fix https://github.com/RigsOfRods/rigs-of-rods/issues/2699 on Windows
=> Added ImGuiKey_KeyPad numbers

source/main/gui/panels/GUI_ConsoleView.cpp, source/main/gui/panels/GUI_GameChatBox.cpp, source/main/main.cpp
Also added icon and updated savegame terrain mismatch error in multiplayer.
=> Enabled errors in notification area

source/main/gfx/GfxActor.cpp, source/main/gui/panels/GUI_GameSettings.cpp, source/main/network/OutGauge.cpp, source/main/physics/Actor.cpp, source/main/physics/Actor.h, source/main/physics/ActorManager.cpp, source/main/physics/ActorSpawner.cpp, source/main/physics/Savegame.cpp
Fixes https://github.com/RigsOfRods/rigs-of-rods/pull/2729#issuecomment-815129570
Explanation: https://github.com/RigsOfRods/rigs-of-rods/pull/2729#issuecomment-815137570
=> Hotfix: eliminate RoR.log spam "Invalid flare ID: -1 ..."

source/main/gui/panels/GUI_GameSettings.cpp, source/main/gui/panels/GUI_GameSettings.h
"Update cache" button moved under "General".
Separated "Simulation settings" from "General" to it's own tab "Gameplay".
=> Settings UI now uses actual tabs

source/main/gui/panels/GUI_MultiplayerSelector.cpp, source/main/gui/panels/GUI_MultiplayerSelector.h
=> Serverlist UI - doubleclick and tabs

source/main/Application.cpp, source/main/Application.h, source/main/gui/GUIManager.cpp, source/main/gui/GUIManager.h, source/main/gui/panels/GUI_GameSettings.cpp, source/main/gui/panels/GUI_MessageBox.cpp, source/main/gui/panels/GUI_MessageBox.h, source/main/main.cpp, source/main/physics/Savegame.cpp, source/main/system/CVar.cpp
You can disable it in RoR.cfg: "sim_quickload_dialog=No" - This is what the "Always ask" checkbox does.
Suggested by **`XD_DominicXD#0746`** on Discord.
=> Added "Are you sure?" UI dialog for QuickLoad hotkey (optional)

source/main/GameContext.cpp, source/main/GameContext.h, source/main/gui/panels/GUI_TopMenubar.cpp, source/main/terrain/TerrainManager.cpp, source/main/terrain/TerrainManager.h
Works like "reload current vehicle" - reloads all resources in the Zip/directory.
=> "Reload current terrain" action.

source/main/gui/panels/GUI_GameSettings.cpp
Fixes https://github.com/RigsOfRods/rigs-of-rods/pull/2747#issuecomment-833150030
Code copied from multiplayer selector
=> Fixed Settings window always scrolling

source/main/gfx/IWater.h, source/main/gfx/Water.cpp, source/main/gfx/Water.h, source/main/gui/panels/GUI_TopMenubar.cpp, source/main/gui/panels/GUI_TopMenubar.h
For simple water, when waves are enabled in settings:
https://user-images.githubusercontent.com/2660424/122416541-7ed49280-cf91-11eb-87cf-f64776cdd906.mp4
With reflection:
=> Added waves height slider

source/main/gfx/Water.h, source/main/gui/panels/GUI_TopMenubar.cpp, source/main/gui/panels/GUI_TopMenubar.h
Show waves slider only in single player and if the terrain has water.
=> Waves slider fixes

source/main/resources/rig_def_fileformat/RigDef_Parser.cpp, source/main/utils/Utils.cpp, source/main/utils/Utils.h
=> Hotfix: Number parsing in truck file was sensitive to locale (regional settings) 

resources/scripts/races.as, source/main/AppContext.cpp, source/main/gui/panels/GUI_ConsoleView.cpp
For cleaner output and less spam.
https://user-images.githubusercontent.com/2660424/127962064-49ee639b-b312-4188-970e-54e1a943502c.mp4
=> Draw notices with same prefix in same line

source/main/Application.cpp, source/main/Application.h, source/main/GameContext.cpp, source/main/gui/panels/GUI_TopMenubar.cpp, source/main/system/CVar.cpp
https://user-images.githubusercontent.com/2660424/131869416-ce18bd42-2640-409f-963d-dfdfabe5d9e3.mp4
=> Caelum: added automatic time cycle

resources/overlays/directionarrow.overlay, resources/scripts/races.as, source/main/gui/GUIManager.h, source/main/gui/panels/GUI_DirectionArrow.cpp, source/main/gui/panels/GUI_TopMenubar.cpp
Also lap times color varies depending the time difference, like before.
=> Remade race text overlay with ImGui

source/main/gui/DashBoardManager.cpp, source/main/physics/Savegame.cpp
Fixes https://github.com/RigsOfRods/rigs-of-rods/issues/2740
And bumps file format version to 3
=> Fixed dashboard state after loading savegame - save/restore blink

source/main/main.cpp
Fixes a very old bug with rorbot character stuttering at high fps
=> Fixes player character stuttering at high FPS

source/main/audio/SoundScriptManager.cpp, source/main/gameplay/ChatSystem.cpp, source/main/gameplay/TorqueCurve.cpp, source/main/gfx/Skidmark.cpp, source/main/network/Network.cpp, source/main/physics/ActorManager.cpp, source/main/physics/CmdKeyInertia.cpp, source/main/resources/CacheSystem.cpp, source/main/resources/odef_fileformat/ODefFileFormat.cpp, source/main/resources/otc_fileformat/OTCFileFormat.cpp, source/main/resources/skin_fileformat/SkinFileFormat.cpp, source/main/resources/terrn2_fileformat/Terrn2FileFormat.cpp, source/main/scripting/GameScript.cpp, source/main/scripting/LocalStorage.cpp, source/main/scripting/OgreScriptBuilder.cpp, source/main/system/AppConfig.cpp, source/main/system/Console.cpp, source/main/utils/ConfigFile.cpp, source/main/utils/ConfigFile.h, source/main/utils/ImprovedConfigFile.h, source/main/utils/Utils.cpp, source/main/utils/Utils.h
=> Log parsing errors for TERRN2/OTC formats

.github/workflows/linux-native.yml
to ensure the snapcraft build keeps working
=> add github action for linux sysdeps build

.github/workflows/linux-native.yml
This makes it easier to debug if something fails
=> :construction_worker: Split up steps in linux-native

source/main/GameContext.cpp, source/main/physics/Actor.cpp
=> Fixed crash due to invalid icon

source/main/gui/panels/GUI_MultiplayerClientList.cpp
=> Added uid in player list

cmake/DependenciesConfig.cmake
=> ⬆️ Updated angelscript to 2.35.0

source/main/resources/skin_fileformat/SkinFileFormat.cpp
=> Tolerate missing } in .skin file format, with warning.

resources/managed_materials/managed_mats_vehicles.material, resources/managed_materials/shadows/pssm/on/shadows.material, resources/materials/character.material
Since we can't do it properly lets build with VS 2017 for last time and remake with OGRE 13/RTSS integrated PSSM4 on next release
=> Removed recently added depth_bias from materials

resources/managed_materials/managed_mats_vehicles.material, resources/managed_materials/shadows/pssm/on/shadows.material, resources/materials/character.material
Tested by four people, intel, amd and nvidia gpu
Fixes visual glitches in character, vehicles (https://github.com/RigsOfRods/rigs-of-rods/issues/361) and terrains
=> Fixed pssm glitches

cmake/DependenciesConfig.cmake
Because of https://github.com/RigsOfRods/rigs-of-rods/issues/2891
=> Use ois 1.4

source/main/gfx/SurveyMapTextureCreator.cpp, source/main/gui/panels/GUI_MultiplayerClientList.cpp, source/main/gui/panels/GUI_MultiplayerClientList.h
Just an icon, nothing fancy.
Before:
After:
=> Αdded icon in network quality warning

source/main/Application.cpp, source/main/Application.h, source/main/gui/panels/GUI_GameSettings.cpp, source/main/physics/ActorSpawner.cpp, source/main/system/CVar.cpp
Always use classic (nicemetal) materials. They look better (cg shaders), they receive light and they don't glitch with PSSM, because they don't receive shadows, only cast.
https://discord.com/channels/136544456244461568/274653814467067916/977568484210917476
https://discord.com/channels/136544456244461568/274653814467067916/977608390874390539
https://discord.com/channels/136544456244461568/274653814467067916/977593552186011719
=> Use nicemetal materials

source/main/gui/panels/GUI_TopMenubar.cpp
=> Don't show top menu bar in free cam

source/main/physics/ActorManager.cpp
Fixes https://github.com/RigsOfRods/rigs-of-rods/issues/2911
=> Fixed glitch when hidding remote vehicle

source/main/gui/GUIUtils.cpp, source/main/gui/GUIUtils.h, source/main/gui/panels/GUI_TopMenubar.cpp
=> Strip color tags from actor names in top menubar.

source/main/physics/ActorManager.cpp
Requested from discord: https://discord.com/channels/136544456244461568/189904947649708032/987831822547288094
=> Removed delay from EV_COMMON_RESET_SIMULATION_PACE and EV_COMMON_REPLAY_FORWARD

source/main/GameContext.cpp
Reported from the forum https://forum.rigsofrods.org/threads/2022-04-discussion-thread.3615/#post-18094
=> Fixed character not exiting hidden moving remote actor

source/main/gui/panels/GUI_SurveyMap.cpp
Keep mini map minimal and show all hints in the big map
=> Cleanup survey map UI

source/main/GameContext.cpp, source/main/gui/panels/GUI_TopMenubar.cpp, source/main/system/CVar.cpp
Might not be the best solution but I think a scroll bar works nicely for this.
https://user-images.githubusercontent.com/46073351/198513521-14122c34-5634-4998-8e13-4856f60d8539.mp4
=> :sparkles: Added polygon mode to tools menu

source/main/gui/DashBoardManager.cpp
Mod for testing:
[agora-dashfix.zip](https://github.com/RigsOfRods/rigs-of-rods/files/10033460/agora-dashfix.zip)
1. Unzip it
2. Load in game
3. Change something in the .layout file, save
4. Reload in game using top menubar
=> Fixed dash '.layout' not reloading with vehicle.

.github/workflows/build-game.yml, cmake/DependenciesConfig.cmake, cmake/DependenciesFunctions.cmake, source/main/CMakeLists.txt
Note the new remote requires conan to have revisions enabled
You can enable it by running `conan config set general.revisions_enabled=1`
=> ⬆️ Updated conan packages for conan V2

source/main/Application.cpp, source/main/Application.h, source/main/CMakeLists.txt, source/main/GameContext.cpp, source/main/gfx/EnvironmentMap.cpp, source/main/gfx/GfxActor.cpp, source/main/gfx/GfxActor.h, source/main/gfx/GfxData.h, source/main/gui/GUIManager.cpp, source/main/gui/GUIManager.h, source/main/gui/imgui/OgreImGuiOverlay.cpp, source/main/gui/imgui/imconfig.h, source/main/gui/panels/GUI_FlexbodyDebug.cpp, source/main/gui/panels/GUI_FlexbodyDebug.h, source/main/gui/panels/GUI_TopMenubar.cpp, source/main/physics/ActorSpawner.cpp, source/main/physics/flex/FlexBody.cpp, source/main/physics/flex/FlexBody.h, source/main/physics/flex/FlexFactory.cpp, source/main/physics/flex/Locator_t.h, source/main/resources/rig_def_fileformat/RigDef_File.h, source/main/system/CVar.cpp, source/main/utils/MeshObject.cpp, source/main/utils/Utils.cpp, source/main/utils/Utils.h
This tool lets you inspect individual vertices and their generated bindings. Just hover mouse pointer over a vertex and see. Click the vertex to toggle persistent visibility.
Closes #2923.
Vehicle on display: https://forum.rigsofrods.org/resources/honda-accord.281/
=> Created flexbody debug view + GUI

source/main/gui/panels/GUI_TopMenubar.cpp
The result can be copy pasted directly in https://github.com/RigsOfRods-Community/ai-waypoints/blob/main/waypoints.json, for convenience.
=> AI: export ready to use json formatted waypoint list

source/main/gui/panels/GUI_FlexbodyDebug.cpp, source/main/physics/ActorSpawner.cpp
Fixes #2999
FlexbodyDebug UI was adjusted to handle this.
=> Restored spawning props with missing mesh file.

source/main/gui/panels/GUI_MainSelector.cpp, source/main/resources/CacheSystem.h
=> SelectorUI: added advanced search tooltip

source/main/gameplay/CruiseControl.cpp, source/main/gameplay/EngineSim.cpp, source/main/gameplay/EngineSim.h, source/main/gameplay/VehicleAI.cpp, source/main/gui/panels/GUI_VehicleButtons.cpp, source/main/network/OutGauge.cpp, source/main/physics/Actor.cpp, source/main/physics/ActorForcesEuler.cpp, source/main/physics/ActorManager.cpp, source/main/physics/Savegame.cpp
Fixes both issues reported in #3021
Note you still need to turn on engine ignition and hit starter.
=> Electric car bugfixes.

source/main/ForwardDeclarations.h, source/main/GameContext.cpp, source/main/gameplay/RecoveryMode.cpp, source/main/gui/panels/GUI_FlexbodyDebug.cpp, source/main/gui/panels/GUI_TopMenubar.cpp, source/main/gui/panels/GUI_VehicleButtons.cpp, source/main/physics/Actor.cpp, source/main/physics/Actor.h, source/main/physics/ActorForcesEuler.cpp, source/main/physics/ActorManager.cpp, source/main/physics/ActorManager.h, source/main/physics/SimData.h, source/main/scripting/GameScript.cpp
Reported on Discord: https://discord.com/channels/136544456244461568/189904947649708032/1088897322466938902
=> Hotfix: AngelScript `game.pushMessage()` param 'instance_id' not handled correctly

doc/angelscript/Script2Game/GameScriptClass.h, doc/angelscript/Script2Game/globals.h, resources/scripts/demo_script.as, source/main/Application.cpp, source/main/Application.h, source/main/ForwardDeclarations.h, source/main/gui/panels/GUI_AngelScriptExamples.cpp, source/main/gui/panels/GUI_CollisionsDebug.cpp, source/main/gui/panels/GUI_FrictionSettings.cpp, source/main/gui/panels/GUI_GameControls.cpp, source/main/gui/panels/GUI_RepositorySelector.cpp, source/main/gui/panels/GUI_ScriptMonitor.cpp, source/main/gui/panels/GUI_ScriptMonitor.h, source/main/gui/panels/GUI_TextureToolWindow.cpp, source/main/gui/panels/GUI_TopMenubar.cpp, source/main/main.cpp, source/main/resources/CacheSystem.cpp, source/main/scripting/GameScript.cpp, source/main/scripting/GameScript.h, source/main/scripting/ScriptEngine.cpp, source/main/scripting/ScriptEngine.h, source/main/scripting/bindings/GameScriptAngelscript.cpp, source/main/scripting/bindings/MsgQueueAngelscript.cpp, source/main/system/CVar.cpp, source/main/terrain/TerrainObjectManager.cpp, source/main/utils/GenericFileFormat.h, source/main/utils/Utils.cpp, source/main/utils/Utils.h
Suggested on Discord: https://discord.com/channels/136544456244461568/189904947649708032/1108018422102622299 - the request was specifically for AI script. I made a solution for any script, though I focused mainly on the AI.
Angelscript API changes:
* added enum `ScriptCategory`
* added `game.setAI*()` counterparts to `game.getAI*()` funcs.
* updated `game.pushMessage()` to handle script params correctly.
* added docs for everything AI
Demo script updated to showcase the feature and provide useful hints:
```
if (ImGui::Button("Start DAF semitruck in follow-mode"))
{
// the filename
// first parameter is index - only use 0/1 for drag race and crash modes. Otherwise use 0.
game.setAIVehicleName(0, "b6b0UID-semi.truck");
// 0) Normal driving mode
// 1) Race
// 2) Drag Race
// 3) Crash driving …
```
=> Added ✉️ `MSG_APP_UN/LOAD_SCRIPT_REQUESTED`

doc/angelscript/Script2Game/GameScriptClass.h, resources/scripts/demo_script.as, source/main/scripting/GameScript.cpp, source/main/scripting/GameScript.h, source/main/scripting/bindings/GameScriptAngelscript.cpp
Minimum work (~ 2.5hrs) and unlimited possibilities. The user can now create, read, detect and delete text files in existing resource locations like "Cache" for the cache folder and "Scripts" for the scripts folder. Access to random files via absolute paths is not possible (game will report "access denied"). To see it in action, open ingame console and say `loadscript demo_script.as` - it showcases the new feature. To test security, say `as game.createTextResourceFromString("boo", "C:\boo.txt", "Cache")` in the console and see what happens.
Here is a reprint of the documentation:
```
//The global object 'game':
/**
* Checks if the resource file exists in the given group.
* KNOWN LIMITATION: If existing file is deleted externally, this function will still report it exists until the …
```
=> :angel: script: write/read/delete text files (resources) as string

source/main/Application.cpp, source/main/Application.h, source/main/gui/panels/GUI_MultiplayerSelector.cpp, source/main/physics/ActorManager.cpp, source/main/system/CVar.cpp
Requested on Discord: https://discord.com/channels/136544456244461568/189904947649708032/1128103513952637089
=> Cvar 'mp_cyclethru_net_actors(bool)' - for cycling with `CTRL + [` and `CTRL + ]`

source/main/system/CVar.cpp
=> :wrench: "Show controls in live repair box" now saved to RoR.cfg

resources/materials/SkyGLSL.frag, resources/materials/SkyGLSL.vert, resources/materials/SkyHLSL.frag, resources/materials/SkyHLSL.vert, resources/materials/ror.material, source/main/Application.cpp, source/main/Application.h, source/main/GameContext.cpp, source/main/gfx/GfxScene.cpp, source/main/gui/panels/GUI_GameSettings.cpp, source/main/gui/panels/GUI_TopMenubar.cpp, source/main/gui/panels/GUI_TopMenubar.h, source/main/main.cpp, source/main/system/AppConfig.cpp, source/main/terrain/Terrain.cpp
https://www.shadertoy.com/view/4sKGWt ported to Ogre and edited to fit RoR
- Sandstorm setting renamed to Basic
- Moving couds
- Sun size, cloud density and ambient light UI sliders
- (SHIFT) +/- control scene ambient light and sky color
Future plans:
- Sun rotation and sync with RoR main light position
- Add a moon, stars, post effects maybe like rain/snow/lightnings/fireworks
- Export shader settings to terrn2 options
=> Replaced Sandstorm sky with new shader

conanfile.py
=> :arrow_up: Updated Pagedgeometry to 1.2.2

source/main/system/ConsoleCmd.cpp
A minor quality of life improvement - I realized this while testing https://github.com/RigsOfRods/ror-server/pull/158
=> Console: pass `!cmd` server commands to netchat.

source/main/resources/addonpart_fileformat/AddonPartFileFormat.cpp, source/main/resources/addonpart_fileformat/AddonPartFileFormat.h, source/main/utils/GenericFileFormat.h
Fixes #3201 
Tested with Honda Accord + Crazy Ricer Kit from the repository, see https://github.com/RigsOfRods/rigs-of-rods/issues/3201#issuecomment-2561532151
=> Fixed addonpart issues

source/main/AppContext.cpp, source/main/Application.cpp
Fixed #3202 - uninitialized pointer access :/
=> Fixed crash on resizing game window in main menu

source/main/gfx/Water.cpp, source/main/gfx/Water.h, source/main/network/Network.cpp
=> Fixed water reflection being stuck when physics are paused (#3212)

source/main/gui/panels/GUI_GameSettings.cpp
Suggested by Zentro in https://github.com/RigsOfRods/rigs-of-rods/pull/3207#discussion_r1912273666
=> 📐 Renamed LOD setting

doc/angelscript/Script2Game/TerrainClass.h, source/main/GameContext.cpp, source/main/gameplay/AutoPilot.cpp, source/main/gameplay/Character.cpp, source/main/gfx/camera/CameraManager.cpp, source/main/physics/Actor.cpp, source/main/physics/collision/Collisions.cpp, source/main/resources/terrn2_fileformat/Terrn2FileFormat.cpp, source/main/resources/terrn2_fileformat/Terrn2FileFormat.h, source/main/scripting/GameScript.cpp, source/main/scripting/ScriptEngine.cpp, source/main/scripting/bindings/TerrainAngelscript.cpp, source/main/system/ConsoleCmd.cpp, source/main/terrain/ProceduralRoad.cpp, source/main/terrain/Terrain.cpp, source/main/terrain/Terrain.h, source/main/terrain/TerrainObjectManager.cpp, source/main/utils/ConfigFile.cpp, source/main/utils/ConfigFile.h
To go with existing `SpawnPosition`.
Fixes 3226.
=> Added option `SpawnRotation` (degrees) to 'terrn2' file format (section [General])

source/main/terrain/TerrainObjectManager.h
Uninitialized variable 😅 
Fixes #3226
=> Hotfix: Character sometimes spawn rotated wrong.

source/main/physics/ActorSpawner.cpp, source/main/resources/addonpart_fileformat/AddonPartFileFormat.cpp, source/main/resources/addonpart_fileformat/AddonPartFileFormat.h, source/main/resources/tuneup_fileformat/TuneupFileFormat.cpp, source/main/resources/tuneup_fileformat/TuneupFileFormat.h
I've added cinecam position tweaking `addonpart_tweak_cinecam <cinecam ID> <posX> <posY> <posZ>` to the addonpart file format, based on the node tweaking code.
~~The new position is applied, however its not resetting to the original position when the addonpart is removed.~~ Fixed
=> ✨  Added `addonpart_tweak_cinecam`

resources/gadgets/script_editor.as
**Problem:** When any folding region got folded, all error markers jumped into bad positions.
**Cause:** bad condition in `determineLineIdxForMessage`, causing all folding regions to be considered "after the message" and thus updating it's line index accordingly.
**Problem2:** There was no "build errors" window - user had to scroll all around the file to see the error markers.
**Solution:** Added "build errors" panel with [go to] buttons for each message.
**Problem3:** The error markers usually obstruct everything on following line, which can be annoying.
**Solution:** Added visibility checkbox to every line in the "build errors" window.
=> :scroll: script_editor gadget: Fixed jumpy error markers, added panel.

source/main/physics/ActorSpawner.cpp, source/main/physics/ActorSpawner.h
=> Fixed false 'invalid node' error for wheel rigidity nodes.
